import {transaction,query} from './db.ts';
import {StoreError,uuid,iso} from './errors.ts';
import {rubles,sumRubles} from '../lib/money.ts';
import {orderListQuery,managerPage,escapeLike,type OrderList,type InventoryItem,type StockHistory} from '../lib/manager-workspace.ts';
import {dashboardOrderFilters} from './dashboard.ts';
export function orderListWhere(params:URLSearchParams){let input;try{input=orderListQuery(params);}catch(e){throw new StoreError('LIST_FILTER',e instanceof Error?e.message:'Некорректный фильтр.');}const values:unknown[]=[],parts=['true'];const add=(sql:string,value:unknown)=>{values.push(value);parts.push(sql.replaceAll('?',`$${values.length}`));};if(input.q)add("(o.number ILIKE ? OR o.customer_name ILIKE ? OR o.customer_email ILIKE ? OR o.customer_phone ILIKE ?)",'%'+escapeLike(input.q)+'%');if(input.kind!=='all')add('o.kind=?',input.kind);if(input.payment!=='all')add('o.payment_status=?',input.payment);if(input.delivery!=='all')add('o.delivery_status=?',input.delivery);if(input.task!=='all')parts.push('('+dashboardOrderFilters[input.task]+')');if(input.from)add("o.created_at >= ?::date::timestamp AT TIME ZONE 'Europe/Moscow'",input.from);if(input.to)add("o.created_at < (?::date+1)::timestamp AT TIME ZONE 'Europe/Moscow'",input.to);return{input,values,where:parts.join(' AND ')};}
export async function listManagerOrders(params:URLSearchParams):Promise<OrderList>{const{input,values,where}=orderListWhere(params);return transaction(async c=>{const total=Number((await c.query(`SELECT count(*) n FROM ar_orders o WHERE ${where}`,values)).rows[0].n),pages=Math.max(1,Math.ceil(total/20)),page=Math.min(input.page,pages);const items=(await c.query(`SELECT id,number,kind,status,payment_status,delivery_status,created_at,customer_name,product_total_rubles,shipping_cost_rubles FROM ar_orders o WHERE ${where} ORDER BY created_at DESC,id DESC LIMIT 20 OFFSET $${values.length+1}`,[...values,(page-1)*20])).rows.map(r=>({id:r.id,number:r.number,kind:r.kind,status:r.status,paymentStatus:r.payment_status,deliveryStatus:r.delivery_status,createdAt:iso(r.created_at)!,customerName:r.customer_name,productTotalRubles:rubles(r.product_total_rubles),shippingCostRubles:r.shipping_cost_rubles===null?null:rubles(r.shipping_cost_rubles),totalRubles:r.shipping_cost_rubles===null?null:sumRubles([r.product_total_rubles,r.shipping_cost_rubles])}));return{items,total,page,pages,pageSize:20,query:{...input,page}};});}
export async function managerInventory():Promise<{items:InventoryItem[]}>{return{items:(await query(`SELECT s.id sku_id,s.product_id,s.article,s.name,s.status,p.name product_name,p.status product_status,p.is_demo,coalesce(st.on_hand,0) on_hand,coalesce(st.reserved,0) reserved FROM ar_skus s JOIN ar_products p ON p.id=s.product_id LEFT JOIN ar_stock st ON st.sku_id=s.id ORDER BY lower(s.article),s.id`)).rows.map(r=>({skuId:r.sku_id,productId:r.product_id,article:r.article,name:r.name,productName:r.product_name,status:r.status,productStatus:r.product_status,isDemo:r.is_demo,onHand:r.on_hand,reserved:r.reserved,available:r.on_hand-r.reserved}))};}
export async function managerStockHistory(params:URLSearchParams):Promise<StockHistory>{const id=uuid(params.get('sku'));let requested;try{requested=managerPage(params.get('page'));}catch{throw new StoreError('LIST_FILTER','Некорректная страница.');}return transaction(async c=>{const total=Number((await c.query('SELECT count(*) n FROM ar_stock_movements WHERE sku_id=$1',[id])).rows[0].n),pages=Math.max(1,Math.ceil(total/20)),page=Math.min(requested,pages);const items=(await c.query(`SELECT m.id,m.created_at,m.stock_delta,m.reserved_delta,m.reason,m.order_id,m.actor_id,o.number FROM ar_stock_movements m LEFT JOIN ar_orders o ON o.id=m.order_id WHERE m.sku_id=$1 ORDER BY m.created_at DESC,m.id DESC LIMIT 20 OFFSET $2`,[id,(page-1)*20])).rows.map(r=>({id:r.id,at:iso(r.created_at)!,stockDelta:r.stock_delta,reservedDelta:r.reserved_delta,reason:r.reason,orderId:r.order_id,orderNumber:r.number,byManager:Boolean(r.actor_id)}));return{items,total,page,pages};});}
