import {getSession,CommerceError} from './commerce';
import {node} from './manager-page';
import {aiSource} from '../lib/ai-text';
import {SLIDE_TYPES,imageFileUrl,type ImageAsset,type ImageSettings,type ImageJob,type ImagePreview,type ImageBudget,type SlideType} from '../lib/ai-images';
import type {EditorData,EditorPhoto} from '../lib/product-editor';
import '../styles/ai-image-studio.css';

export function aiImageStudio(dialog:HTMLDialogElement,hooks:{id:()=>string;data:()=>EditorData;busy:(busy:boolean)=>void;apply:(photos:EditorPhoto[])=>void;error:(error:unknown)=>void}){
 const $=<T extends HTMLElement=HTMLElement>(selector:string)=>dialog.querySelector<T>(selector)!;
 const input=(name:string)=>$<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>('[data-aii-'+name+']');
 let assets:ImageAsset[]=[],jobs:ImageJob[]=[],selectedSources:string[]=[],styleId:string|null=null,editOf:string|null=null,selectedJob:string|null=null,quote:ImagePreview|null=null,budget:ImageBudget|null=null,working=false,epoch=0,timer:ReturnType<typeof setTimeout>|undefined;
 let pageBefore:string|null=null,nextBefore:string|null=null,covers:{id:string;number:string;settings:ImageSettings}[]=[];const selectedResults=new Set<string>();let pending:{fingerprint:string;key:string}|null=null;
 let actorId='',historyRequest=0;let opener:HTMLElement|null=null;const storeKey=()=>`autoreelz.image-studio.${actorId}.${hooks.id()}`;
 function settings():ImageSettings{return{type:input('type').value as SlideType,headline:input('headline').value,lines:input('lines').value,footnote:input('footnote').value,facts:input('facts').value,wishes:input('wishes').value,changes:input('changes').value,background:input('background').value,accent:input('accent').value,sourceIds:[...selectedSources],styleId,coverId:input('anchor').value||null,editOf};}
 function remember(){try{sessionStorage.setItem(storeKey(),JSON.stringify({settings:settings(),pending}));}catch{}}
 function error(value:unknown){const box=$('[data-aii-error]');box.textContent=value instanceof TypeError||value instanceof SyntaxError?'Не удалось связаться со студией. Проверьте историю и повторите запрос с теми же параметрами: второй платный вызов не создастся.':value instanceof Error?value.message:'Не удалось выполнить действие.';box.hidden=false;if(value instanceof CommerceError&&(value.status===401||value.status===403))hooks.error(value);}
 function invalidate(){historyRequest++;quote=null;$('[data-aii-cost]').hidden=true;$<HTMLInputElement>('[data-aii-confirm]').checked=false;remember();buttons();}
 function buttons(){
  $<HTMLFieldSetElement>('[data-aii-fields]').disabled=working;
  dialog.setAttribute('aria-busy',String(working));$('[data-aii-operation]').textContent=working?'Выполняем действие…':'';
  for(const selector of ['[data-aii-all-history]','[data-aii-older]','[data-aii-latest]','[data-aii-refresh]'])($<HTMLButtonElement>(selector)).disabled=working;
  const anchor=covers.find(c=>c.id===input('anchor').value);for(const key of ['background','accent','wishes'] as const){input(key).disabled=working||!!anchor;if(anchor)input(key).value=anchor.settings[key];}
  $<HTMLInputElement>('[data-aii-style-upload]').disabled=working||!!anchor;
  const job=jobs.find(j=>j.id===selectedJob),reviewed=$<HTMLInputElement>('[data-aii-reviewed]').checked;
  $<HTMLButtonElement>('[data-aii-generate]').disabled=working||!quote||!budget?.enabled||!$<HTMLInputElement>('[data-aii-confirm]').checked||Number(budget.remainingUsd)<Number(quote.reservedUsd);
  $<HTMLButtonElement>('[data-aii-cover]').disabled=working||!reviewed||job?.state!=='completed'||job.productId!==hooks.id()||job.plan.settings.type!=='cover';
  $<HTMLButtonElement>('[data-aii-revise]').disabled=working||job?.state!=='completed'||job.productId!==hooks.id();
  $<HTMLButtonElement>('[data-aii-apply]').disabled=working||!reviewed||!selectedResults.size;
 }
 async function call<T>(action:string,payload:object):Promise<T>{const current=epoch;const session=await getSession();const response=await fetch('/api/manager/ai-images',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':session.csrfToken},body:JSON.stringify({action,...payload}),signal:AbortSignal.timeout(45000)});const body=await response.json();if(current!==epoch)throw Error('Форма обновлена. Откройте историю заново.');if(!response.ok)throw new CommerceError(body.error?.message??'Не удалось выполнить действие.',response.status,body.error?.code);return body;}
 async function run(work:()=>Promise<void>){if(working)return;working=true;buttons();$('[data-aii-error]').hidden=true;try{await work();}catch(e){error(e);}finally{working=false;buttons();}}
 function budgetText(){if(!budget)return;const money=(s:string)=>'$'+Number(s).toFixed(4);$('[data-aii-budget]').textContent=(budget.simulation?'Проверка интерфейса без ИИ. ':'')+`Бюджет изображений на весь пилот: ${money(budget.usedUsd)} из $${Number(budget.limitUsd).toFixed(2)}. Резервы включены.`+(budget.enabled?'':' Платная генерация выключена или требует проверки.');$('[data-aii-confirm-copy]').textContent=budget.simulation?'Подтверждаю параметры тестового задания без передачи данных во внешний сервис.':'Понимаю, что выбранные фото и текст будут переданы OpenAI, и согласен на платный запрос.';}
 function showOriginal(){const first=assets.find(a=>a.id===selectedSources[0]),image=$<HTMLImageElement>('[data-aii-original]');image.hidden=!first;if(first){image.src=imageFileUrl(first.id);$<HTMLAnchorElement>('[data-aii-original-link]').href=imageFileUrl(first.id);}else{image.removeAttribute('src');$('[data-aii-original-link]').removeAttribute('href');}}
 function gallery(){const box=$('[data-aii-gallery]');box.replaceChildren();
  const ownIds=new Set(assets.map(a=>a.id));selectedSources=selectedSources.filter(id=>ownIds.has(id));
  for(const asset of assets){const label=node('label','','aii-source'),check=node('input'),image=node('img');check.type='checkbox';check.checked=selectedSources.includes(asset.id);image.src=imageFileUrl(asset.id);image.alt='';image.loading='lazy';label.append(image,check,node('span',asset.name));check.addEventListener('change',()=>{if(check.checked&&selectedSources.length>=4){check.checked=false;error(Error('Можно выбрать до четырёх фото товара.'));return;}selectedSources=check.checked?[...selectedSources,asset.id]:selectedSources.filter(id=>id!==asset.id);invalidate();showOriginal();});box.append(label);}
  const photos=[...hooks.data().photos,...hooks.data().variants.flatMap(v=>v.photos)].filter((p,i,a)=>a.findIndex(v=>v.id===p.id)===i);
  for(const photo of photos){const button=node('button','','aii-source'),image=node('img');button.type='button';image.src='/api/manager/product-image?id='+encodeURIComponent(photo.id)+'&thumbnail=1';image.alt=photo.alt||'Фото галереи';button.append(image,node('span','Взять из галереи'));button.addEventListener('click',()=>void run(async()=>{if(selectedSources.length>=4)throw Error('Сначала снимите выбор одного из четырёх исходников.');const asset=await call<ImageAsset>('import',{productId:hooks.id(),fileId:photo.id});if(!assets.some(a=>a.id===asset.id))assets.push(asset);if(!selectedSources.includes(asset.id))selectedSources.push(asset.id);gallery();invalidate();}));box.append(button);}
  showOriginal();
 }
 function selectJob(job:ImageJob){selectedJob=job.id;$<HTMLInputElement>('[data-aii-reviewed]').checked=false;const image=$<HTMLImageElement>('[data-aii-result]');image.hidden=!job.result;$('[data-aii-placeholder]').hidden=!!job.result;if(job.result){image.src=imageFileUrl(job.result.id);$<HTMLAnchorElement>('[data-aii-result-link]').href=imageFileUrl(job.result.id)+'&full=1';}else{image.removeAttribute('src');$('[data-aii-placeholder]').textContent=job.message;}
  const original=job.plan.references.find(r=>r.role==='product');if(original){const source=$<HTMLImageElement>('[data-aii-original]');source.src=imageFileUrl(original.asset.id);$<HTMLAnchorElement>('[data-aii-original-link]').href=imageFileUrl(original.asset.id);source.hidden=false;}
  const download=$<HTMLAnchorElement>('[data-aii-download]');download.hidden=!job.result;if(job.result){download.href=imageFileUrl(job.result.id,true);download.download='autoreelz-slide.png';}history();buttons();$('.aii-preview').scrollTop=0;
 }
 function history(){const list=$('[data-aii-history]'),opened=new Set([...list.querySelectorAll<HTMLDetailsElement>('details[open]')].map(n=>n.dataset.job));list.replaceChildren();if(!jobs.length)list.append(node('p','Здесь сохранятся задания и все варианты.','dash-help'));
  for(const job of jobs){const card=node('article','','aii-job');card.dataset.selected=String(job.id===selectedJob);if(job.result){const image=node('img');image.src=imageFileUrl(job.result.id);image.alt=job.plan.settings.headline;image.loading='lazy';card.append(image);}else card.append(node('span',job.state==='queued'?'В очереди':'…'));
   const copy=node('div');copy.append(node('p',job.plan.productName),node('strong',`№${job.number} · ${SLIDE_TYPES[job.plan.settings.type]}`),node('p',job.message),node('p',job.chargedUsd===null?`Резерв $${Number(job.reservedUsd).toFixed(2)}`:`Учтено $${Number(job.chargedUsd).toFixed(5)}`));if(job.provider==='simulation')copy.append(node('p','Макет проверки интерфейса — не результат ИИ.'));if(job.approved)copy.append(node('p','Обложка серии'));card.append(copy);
   const actions=node('div','','aii-actions'),view=node('button','Посмотреть','dash-button');view.type='button';view.addEventListener('click',()=>selectJob(job));actions.append(view);
   if(job.result&&job.productId===hooks.id()){const label=node('label','','dash-checkbox'),check=node('input');check.type='checkbox';check.checked=selectedResults.has(job.id);check.setAttribute('aria-label',`Добавить слайд №${job.number}`);check.addEventListener('change',()=>{if(check.checked)selectedResults.add(job.id);else selectedResults.delete(job.id);$<HTMLInputElement>('[data-aii-reviewed]').checked=false;buttons();});label.append(check,node('span','Выбрать для товара'));actions.append(label);}
   if(['queued','preparing'].includes(job.state)){const cancel=node('button','Отменить до отправки','dash-button');cancel.type='button';cancel.addEventListener('click',()=>void run(async()=>{await call('cancel',{id:job.id});await refresh();}));actions.append(cancel);}
   if(job.productId!==hooks.id()){const open=node('a','Открыть редактор этого товара','dash-button');open.href='/manager/products/edit?id='+encodeURIComponent(job.productId);actions.append(open);}card.append(actions);
   const details=node('details');details.dataset.job=job.id;details.open=opened.has(job.id);details.append(node('summary','Параметры, исходники и расход'),node('p',`${job.plan.model} · ${job.plan.size} · ${new Date(job.createdAt).toLocaleString('ru-RU')}`));if(job.plan.settings.editOf)details.append(node('p','Правка предыдущего варианта; исходный результат сохранён.'));const refs=node('div','','aii-reference-links');job.plan.references.forEach((ref,i)=>{const a=node('a',`${ref.role==='product'?'Исходник':ref.role==='style'?'Образец стиля':'Предыдущий вариант'} ${i+1}`);a.href=imageFileUrl(ref.asset.id)+'&full=1';a.target='_blank';a.rel='noopener';refs.append(a);});details.append(refs,node('pre',job.plan.prompt));card.append(details);list.append(card);
  }
 }
 function anchorChoices(){const select=$<HTMLSelectElement>('[data-aii-anchor]'),value=select.value;select.replaceChildren(new Option('Новый стиль',''));covers.forEach(j=>select.append(new Option(`Обложка №${j.number}`,j.id)));if(covers.some(j=>j.id===value))select.value=value;}
 async function refresh(){const current=epoch,serial=++historyRequest;const response=await fetch('/api/manager/ai-images?productId='+encodeURIComponent(hooks.id())+($<HTMLInputElement>('[data-aii-all-history]').checked?'&scope=all':'')+(pageBefore?'&before='+pageBefore:''),{credentials:'same-origin',cache:'no-store',signal:AbortSignal.timeout(20000)});const body=await response.json();if(!response.ok)throw new CommerceError(body.error?.message??'История недоступна.',response.status);if(current!==epoch||serial!==historyRequest)return;
  const changed=JSON.stringify(jobs)!==JSON.stringify(body.jobs);actorId=body.actorId;jobs=body.jobs;assets=body.assets;budget=body.budget;covers=body.covers;nextBefore=body.nextBefore;$('[data-aii-older]').hidden=!nextBefore;$('[data-aii-latest]').hidden=!pageBefore;for(const job of jobs.filter(j=>j.productId===hooks.id()))for(const ref of job.plan.references)if(ref.asset.kind==='source'&&!assets.some(a=>a.id===ref.asset.id))assets.push(ref.asset);
  budgetText();if(changed){anchorChoices();history();}if(selectedJob){const job=jobs.find(j=>j.id===selectedJob);if(job?.result&&$<HTMLImageElement>('[data-aii-result]').hidden)selectJob(job);}buttons();
 }
 async function poll(){clearTimeout(timer);if(!dialog.open)return;try{if(!working&&document.visibilityState==='visible')await refresh();}catch(e){error(e);}if(dialog.open)timer=setTimeout(()=>void poll(),3000);}
 function restore(s:ImageSettings){selectedSources=[...s.sourceIds];styleId=s.styleId;editOf=s.editOf;for(const key of ['type','headline','lines','footnote','facts','wishes','changes','background','accent'] as const)input(key).value=s[key];input('anchor').value=s.coverId??'';$('[data-aii-changes-field]').hidden=!editOf;styleView();gallery();invalidate();}
 function styleView(){const box=$('[data-aii-style]');box.replaceChildren();if(styleId){const image=node('img');image.src=imageFileUrl(styleId);image.alt='Образец оформления';box.append(image);} $<HTMLButtonElement>('[data-aii-clear-style]').hidden=!styleId;}
 async function upload(files:File[],style=false){const current=epoch;await run(async()=>{if(!style&&selectedSources.length+files.length>4)throw Error('Выберите не больше четырёх исходников.');for(const file of files){const session=await getSession(),body=new FormData();body.append('productId',hooks.id());body.append('file',file);const response=await fetch('/api/manager/ai-image-file',{method:'POST',headers:{'X-CSRF-Token':session.csrfToken},body,signal:AbortSignal.timeout(45000)}),asset=await response.json();if(current!==epoch)return;if(!response.ok)throw new CommerceError(asset.error?.message??'Файл не загружен.',response.status);if(!assets.some(a=>a.id===asset.id))assets.push(asset);if(style)styleId=asset.id;else if(!selectedSources.includes(asset.id))selectedSources.push(asset.id);gallery();styleView();invalidate();}});}
 function close(){dialog.close();hooks.busy(false);clearTimeout(timer);remember();opener?.focus();}
 $('[data-aii-close]').addEventListener('click',close);dialog.addEventListener('cancel',event=>{event.preventDefault();close();});
 $('[data-aii-refresh]').addEventListener('click',()=>void run(refresh));
 $('[data-aii-older]').addEventListener('click',()=>void run(async()=>{pageBefore=nextBefore;selectedResults.clear();selectedJob=null;await refresh();}));
 $('[data-aii-latest]').addEventListener('click',()=>void run(async()=>{pageBefore=null;selectedResults.clear();selectedJob=null;await refresh();}));
 $('[data-aii-all-history]').addEventListener('change',()=>void run(async()=>{pageBefore=null;selectedResults.clear();selectedJob=null;await refresh();}));
 $<HTMLInputElement>('[data-aii-upload]').addEventListener('change',event=>{const input=event.target as HTMLInputElement,files=[...input.files??[]];input.value='';void upload(files);});
 $<HTMLInputElement>('[data-aii-style-upload]').addEventListener('change',event=>{const input=event.target as HTMLInputElement,files=[...input.files??[]];input.value='';void upload(files,true);});
 $('[data-aii-clear-style]').addEventListener('click',()=>{styleId=null;styleView();invalidate();});
 for(const key of ['headline','lines','footnote','facts','wishes','changes','background','accent'])input(key).addEventListener('input',invalidate);
 input('type').addEventListener('change',()=>{if(!editOf)input('headline').value=input('type').value==='cover'?hooks.data().name:SLIDE_TYPES[input('type').value as SlideType];invalidate();});input('anchor').addEventListener('change',invalidate);
 $('[data-aii-confirm]').addEventListener('change',buttons);$('[data-aii-reviewed]').addEventListener('change',buttons);
 $('[data-aii-preview]').addEventListener('click',()=>void run(async()=>{const value=await call<ImagePreview>('preview',{productId:hooks.id(),data:hooks.data(),settings:settings()});quote=value;budget=value.budget;budgetText();$('[data-aii-cost]').hidden=false;$('[data-aii-estimate]').textContent=`Оценка: $${Number(value.estimatedUsd).toFixed(3)}. Резерв бюджета на запрос: $${Number(value.reservedUsd).toFixed(2)}. Фактический расход уточняется по ответу провайдера. Каждая новая генерация и правка оплачивается отдельно.`;$('[data-aii-prompt]').textContent=value.plan.prompt;$<HTMLInputElement>('[data-aii-confirm]').checked=false;}));
 $('[data-aii-generate]').addEventListener('click',()=>void run(async()=>{if(!quote||!$<HTMLInputElement>('[data-aii-confirm]').checked)return;const body={productId:hooks.id(),data:hooks.data(),settings:settings()},fingerprint=JSON.stringify({productId:body.productId,settings:body.settings,source:aiSource(body.data,body.settings.facts)});if(!pending||pending.fingerprint!==fingerprint)pending={fingerprint,key:crypto.randomUUID()};remember();const job=await call<ImageJob>('generate',{...body,quote:quote.token,confirmed:true,idempotencyKey:pending.key});quote=null;pageBefore=null;$('[data-aii-cost]').hidden=true;await refresh();selectJob(job);}));
 $('[data-aii-new]').addEventListener('click',()=>{pending=null;editOf=null;input('changes').value='';$('[data-aii-changes-field]').hidden=true;invalidate();input('type').focus();});
 $('[data-aii-revise]').addEventListener('click',()=>{const job=jobs.find(j=>j.id===selectedJob);if(!job?.result)return;pending=null;restore({...job.plan.settings,editOf:job.id,changes:''});input('changes').focus();});
 $('[data-aii-cover]').addEventListener('click',()=>void run(async()=>{if(!$<HTMLInputElement>('[data-aii-reviewed]').checked)return;await call('cover',{id:selectedJob,reviewed:true});await refresh();input('anchor').value=selectedJob!;invalidate();}));
 $('[data-aii-apply]').addEventListener('click',()=>void run(async()=>{if(!$<HTMLInputElement>('[data-aii-reviewed]').checked)return;const chosen=jobs.filter(j=>selectedResults.has(j.id)&&j.result);const existing=new Set(hooks.data().photos.map(p=>p.id));const additions=chosen.filter(j=>!j.applyFileId||!existing.has(j.applyFileId));if(hooks.data().photos.length+additions.length>12)throw Error('В галерее может быть до 12 фото. Уберите лишние или выберите меньше слайдов.');const photos:EditorPhoto[]=[];for(const job of chosen)photos.push(await call<EditorPhoto>('apply',{id:job.id,reviewed:true}));hooks.apply(photos);await refresh();$('[data-aii-apply-status]').textContent='Добавлено в форму товара. Сохраните черновик; публикация выполняется отдельно.';}));
 return{
  async open(){epoch++;pageBefore=null;const current=epoch;opener=document.activeElement instanceof HTMLElement?document.activeElement:null;hooks.busy(true);dialog.showModal();$('[data-aii-error]').hidden=true;$<HTMLInputElement>('[data-aii-reviewed]').checked=false;selectedResults.clear();selectedJob=null;quote=null;$('[data-aii-cost]').hidden=true;$('[data-aii-result]').hidden=true;$('[data-aii-placeholder]').hidden=false;$('[data-aii-placeholder]').textContent='Результат появится здесь';$('[data-aii-download]').hidden=true;$('[data-aii-apply-status]').textContent='После добавления сохраните черновик. Публикация — отдельное действие.';
   try{await refresh();if(current!==epoch||!dialog.open)return;let saved;try{saved=JSON.parse(sessionStorage.getItem(storeKey())??'null');}catch{}pending=saved?.pending??null;restore(saved?.settings??{type:'cover',headline:hooks.data().name,lines:'',footnote:'',facts:'',wishes:'Чистый студийный фон, крупный товар, читаемые надписи и аккуратные акценты.',changes:'',background:'#f6f4ef',accent:'#ff7a1a',sourceIds:[],styleId:null,coverId:null,editOf:null});void poll();}catch(e){error(e);}},
  lock(){epoch++;clearTimeout(timer);if(dialog.open)dialog.close();hooks.busy(false);assets=[];jobs=[];selectedSources=[];selectedResults.clear();styleId=null;editOf=null;selectedJob=null;quote=null;pending=null;actorId='';for(const selector of ['[data-aii-gallery]','[data-aii-history]','[data-aii-style]','[data-aii-prompt]'])$(selector).replaceChildren();for(const image of dialog.querySelectorAll('img'))image.removeAttribute('src');for(const a of dialog.querySelectorAll('[data-aii-original-link],[data-aii-result-link],[data-aii-download]'))a.removeAttribute('href');for(const field of dialog.querySelectorAll('input,textarea')){if(field instanceof HTMLInputElement&&(field.type==='checkbox'||field.type==='radio'))field.checked=false;else(field as HTMLInputElement).value='';}}
 };
}
