import {node} from './manager-page';
import {bundleTotals,type EditorData,type EditorOptions} from '../lib/product-editor';
import {formatRubles,multiplyRubles} from '../lib/money';

export function bundleEditor(container:HTMLElement,hooks:{data:()=>EditorData;options:()=>EditorOptions;changed:()=>void;photosChanged:()=>void}){
 let query='',limit=12;
 const button=(label:string,fn:()=>void)=>{const b=node('button',label,'dash-button');b.type='button';b.addEventListener('click',fn);return b;};
 function identity(imageId:string|null,title:string,detail:string){const row=node('div','','be-identity');if(imageId){const image=node('img');image.src='/api/manager/product-image?id='+encodeURIComponent(imageId)+'&thumbnail=1';image.alt='';image.width=64;image.height=64;image.loading='lazy';row.append(image);}const copy=node('div');copy.append(node('strong',title),node('p',detail,'dash-help'));row.append(copy);return row;}
 function render(){
  const data=hooks.data(),skus=hooks.options().bundleSkus??[];container.replaceChildren();if(data.kind!=='bundle')return;
  const components=data.components??=[];const searchLabel=node('label','','dash-field'),search=node('input');search.type='search';search.placeholder='Название, цвет или артикул';search.value=query;search.dataset.bundleSearch='';searchLabel.append(node('span','Найти товар для комплекта'),search);
  const results=node('div','','be-results'),count=node('p','','dash-help');count.setAttribute('role','status');
  function searchResults(){results.replaceChildren();const q=query.trim().toLocaleLowerCase('ru-RU');const found=skus.filter(s=>s.published&&`${s.productName} ${s.name} ${s.article}`.toLocaleLowerCase('ru-RU').includes(q));count.textContent=`Найдено исполнений: ${found.length}`;
   for(const sku of found.slice(0,limit)){const row=node('article','','be-result');row.append(identity(sku.imageId,sku.productName,`${sku.name} · ${sku.article}`),node('p',`${formatRubles(sku.price)} / шт. · свободно: ${sku.available}`,'dash-help'));const selected=components.some(c=>c.skuId===sku.id),add=button(selected?'Добавлено':'Добавить',()=>{if(components.some(c=>c.skuId===sku.id)||components.length>=50)return;components.push({skuId:sku.id,quantity:'1'});renderSelected();searchResults();hooks.changed();});add.disabled=selected||components.length>=50;add.setAttribute('aria-label',`${selected?'Добавлено':'Добавить'}: ${sku.productName}, ${sku.name}, ${sku.article}`);row.append(add);results.append(row);}
   if(found.length>limit)results.append(button('Показать ещё',()=>{limit+=12;searchResults();}));if(!found.length)results.append(node('p','Нет доступных исполнений. Измените поиск или опубликуйте нужный товар.','dash-help'));
  }
  search.addEventListener('input',()=>{query=search.value;limit=12;searchResults();});
  const picker=node('details','','be-picker');picker.open=true;picker.append(node('summary','Добавить товары в состав'),searchLabel,count,results);
  const selected=node('div','','be-selected');selected.id='pe-components';selected.tabIndex=-1;selected.dataset.fieldPath='components';const error=node('small','','pe-field-error');error.dataset.errorPath='components';
  function renderSelected(){selected.replaceChildren(node('h3',`Состав комплекта · ${components.length}`));if(!components.length)selected.append(node('p','Найдите товар выше и нажмите «Добавить». Выбирайте конкретный цвет или исполнение.','dash-help'));
   components.forEach((item,i)=>{const sku=skus.find(s=>s.id===item.skuId),row=node('article','','be-component');row.dataset.bundleComponent=item.skuId;row.append(identity(sku?.imageId??null,sku?.productName??'Недоступное исполнение',sku?`${sku.name} · ${sku.article}`:'Уберите его из состава и выберите доступное.'));if(sku&&!sku.published)row.append(node('p','Исполнение скрыто или удалено. Публикация комплекта с ним недоступна.','dash-error'));
    const label=node('label','','dash-field'),input=node('input');input.type='text';input.inputMode='numeric';input.maxLength=5;input.value=item.quantity;input.id=`pe-components-${i}-quantity`;input.dataset.fieldPath=`components.${i}.quantity`;const err=node('small','','pe-field-error');err.dataset.errorPath=`components.${i}.quantity`;err.id=input.id+'-error';input.setAttribute('aria-describedby',err.id);label.append(node('span','Количество в комплекте, шт.'),input,err);
    const price=node('p','','dash-help');price.dataset.bundleLine=item.skuId;input.addEventListener('input',()=>{item.quantity=input.value;hooks.changed();});input.addEventListener('blur',()=>{err.textContent=/^\d+$/.test(item.quantity)&&+item.quantity>=1&&+item.quantity<=10000?'':'Укажите целое количество от 1 до 10 000.';input.setAttribute('aria-invalid',String(!!err.textContent));});
    const actions=node('div','','pe-inline-actions'),up=button('Выше',()=>{[components[i-1],components[i]]=[components[i]!,components[i-1]!];renderSelected();hooks.changed();});up.disabled=i===0;actions.append(up,button('Убрать из комплекта',()=>{components.splice(i,1);renderSelected();searchResults();hooks.changed();}));row.append(label,price,actions);selected.append(row);
   });update();
  }
  const discountLabel=node('label','','dash-field'),discount=node('input');discount.type='text';discount.inputMode='decimal';discount.maxLength=6;discount.id='pe-discountPercent';discount.dataset.fieldPath='discountPercent';discount.value=data.discountPercent??'0';const discountError=node('small','','pe-field-error');discountError.dataset.errorPath='discountPercent';discountError.id='pe-discountPercent-error';discount.setAttribute('aria-describedby',discountError.id);discountLabel.append(node('span','Скидка на комплект, %'),discount,discountError);discount.addEventListener('input',()=>{data.discountPercent=discount.value;hooks.changed();});
  const totals=node('div','','be-totals');totals.dataset.bundleTotals='';totals.setAttribute('aria-live','polite');
  const photoNote=node('p','','dash-help');photoNote.setAttribute('role','status');const photoButton=button('Взять фото компонентов',()=>{let added=0;for(const item of components){const sku=skus.find(s=>s.id===item.skuId);if(sku?.imageId&&data.photos.length<12&&!data.photos.some(p=>p.id===sku.imageId)){data.photos.push({id:sku.imageId,alt:sku.productName+' · '+sku.name});added++;}}hooks.photosChanged();hooks.changed();photoNote.textContent=added?`Добавлено фото: ${added}. Порядок и подписи можно изменить в разделе «Фотографии».`:'Новых фото для добавления нет или в галерее уже 12 фотографий.';});
  container.append(picker,selected,error,discountLabel,totals,node('p','Цена пересчитывается из актуальных цен компонентов. Запас общий с отдельными товарами; если детали не хватает, весь комплект доступен по предзаказу.','dash-help'),photoButton,photoNote);renderSelected();searchResults();update();
 }
 function update(){const data=hooks.data(),skus=hooks.options().bundleSkus??[];for(const item of data.components??[]){const sku=skus.find(s=>s.id===item.skuId),line=container.querySelector<HTMLElement>(`[data-bundle-line="${item.skuId}"]`);if(line)try{line.textContent=sku?`${formatRubles(sku.price)} × ${item.quantity} = ${formatRubles(multiplyRubles(sku.price,Number(item.quantity)))}`:'Цена недоступна';}catch{line.textContent='Проверьте количество';}}
  const totals=container.querySelector<HTMLElement>('[data-bundle-totals]');if(!totals)return;try{const t=bundleTotals(data,skus);totals.replaceChildren(node('p','Стоимость по отдельности: '+formatRubles(t.subtotal)),node('strong','Цена комплекта: '+formatRubles(t.total)),node('p',t.published?`Можно собрать сейчас: ${t.available} шт.`:'Проверьте доступность компонентов.'));}catch{totals.replaceChildren(node('p','Добавьте состав и укажите корректные количество и скидку — здесь появятся цена и наличие.'));}
 }
 return{render,update};
}
