import Quill from 'quill';import 'quill/dist/quill.snow.css';
import {managerPage,managerDirty,node} from './manager-page';
import {commerceCommand,CommerceError,getSession} from './commerce';
import {productImageLibrary} from './product-image-library';
import {productSlug} from '../lib/product-editor';
import type {EditorPhoto} from '../lib/product-editor';
import {contentHref,type ContentData,type ContentState,type ContentOptions,type ContentKind} from '../lib/content-editor';
const root=document.querySelector<HTMLElement>('[data-workspace="content-editor"]');
if(root){
 const q=<T extends HTMLElement=HTMLElement>(selector:string)=>root.querySelector<T>(selector)!;
 const kind:ContentKind=new URLSearchParams(location.search).get('kind')==='page'?'page':'article',id=new URLSearchParams(location.search).get('id')??crypto.randomUUID();history.replaceState(null,'',`?kind=${kind}&id=${id}`);q<HTMLAnchorElement>('[data-content-back]').href='/manager/content?kind='+kind;
 let state:ContentState,options:ContentOptions,data:ContentData,busy=false,mediaBusy=false,rendering=false,slugManual=false,epoch=0,position=0,imageIndex:number|null=null,chosenPhoto:EditorPhoto|null=null,pending:{fingerprint:string;key:string}|null=null,uploadQueue:{file:File;key:string;target:string}[]=[];
 const bodyImageId=(url:string)=>url.match(/^\/(?:media\/|api\/manager\/product-image\?id=)([a-f0-9-]{36})$/i)?.[1]??null;
 const imageUrl=(file:string)=>'/api/manager/product-image?id='+encodeURIComponent(file);
 const BaseImage=Quill.import('formats/image') as typeof import('quill/formats/image').default;
 class ManagedImage extends BaseImage{static sanitize(value:string){const id=bodyImageId(value);return id?imageUrl(id):'about:blank';}}
 Quill.register(ManagedImage,true);
 const editor=new Quill(q('[data-ce-quill]'),{theme:'snow',placeholder:'Начните писать…',modules:{toolbar:[[{header:[false,2,3]}],['bold','italic','underline','strike'],[{list:'ordered'},{list:'bullet'}],['blockquote'],[{align:[]}],['link'],['clean']],history:{userOnly:false}},formats:['header','bold','italic','underline','strike','list','blockquote','align','link','image','alt','width']});
 editor.root.setAttribute('aria-label','Текст материала');editor.root.setAttribute('role','textbox');editor.root.setAttribute('aria-multiline','true');
 const names:Record<string,string>={bold:'Жирный',italic:'Курсив',underline:'Подчёркнутый',strike:'Зачёркнутый',blockquote:'Цитата',link:'Ссылка',clean:'Убрать форматирование'};
 root.querySelectorAll<HTMLButtonElement>('.ql-toolbar button').forEach(b=>{const key=Object.keys(names).find(k=>b.classList.contains('ql-'+k)),name=key?names[key]!:b.classList.contains('ql-list')?(b.value==='ordered'?'Нумерованный список':'Список с маркерами'):'Выравнивание';b.setAttribute('aria-label',name);b.title=name;b.type='button';});
 root.querySelectorAll('.ql-picker-label').forEach(p=>p.setAttribute('aria-label',p.parentElement?.classList.contains('ql-header')?'Стиль абзаца':'Выравнивание'));
 const undo=node('button','↶'),redo=node('button','↷');for(const [b,name] of [[undo,'Отменить'],[redo,'Повторить']] as const){b.type='button';b.title=name;b.setAttribute('aria-label',name);}undo.addEventListener('click',()=>editor.history.undo());redo.addEventListener('click',()=>editor.history.redo());q('.ql-toolbar').append(undo,redo);
 const fields=q<HTMLFieldSetElement>('[data-ce-fields]'),form=q<HTMLFormElement>('[data-ce-form]');
 function lockControls(){const locked=busy||mediaBusy;fields.disabled=locked||state?.status==='archived';editor.enable(!locked&&state?.status!=='archived');root!.querySelectorAll<HTMLButtonElement>('[data-ce-save],[data-ce-publish],[data-ce-discard],[data-ce-archive],[data-ce-restore],[data-workspace-refresh],[data-ce-show-preview]').forEach(b=>b.disabled=locked||state?.status==='archived'&&!b.hasAttribute('data-ce-restore')&&!b.hasAttribute('data-workspace-refresh')&&!b.hasAttribute('data-ce-show-preview'));form.setAttribute('aria-busy',String(locked));}
 function changed(){if(rendering||!data)return;data.body=editor.getSemanticHTML();managerDirty(true);q('[data-ce-save-hint]').textContent='Есть несохранённые изменения';q('[data-ce-count]').textContent=`Символов: ${editor.getText().trim().length}`;}
 editor.on('text-change',changed);editor.on('selection-change',range=>{if(range){position=range.index;const [leaf]=editor.getLeaf(range.index);imageIndex=leaf?.domNode instanceof HTMLImageElement?range.index:null;}});
 const button=(text:string,fn:()=>void)=>{const b=node('button',text,'dash-button');b.type='button';b.addEventListener('click',fn);return b;};
 function field(label:string,key:keyof ContentData,config:{type?:string;help?:string;choices?:{id:string;name:string}[]}={}){const wrap=node('label','','dash-field');wrap.append(node('span',label));let input:HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement;if(config.choices){input=node('select');input.append(new Option('Не выбрано',''));for(const row of config.choices)input.append(new Option(row.name,row.id));}else if(config.type==='textarea'){input=node('textarea');input.rows=3;}else{input=node('input');input.type=config.type??'text';}input.id='ce-'+key;const raw=String(data[key]);input.value=config.type==='datetime-local'?toLocal(raw):raw;input.addEventListener(input instanceof HTMLSelectElement?'change':'input',()=>{let value=input.value;if(config.type==='datetime-local')value=value?new Date(value+(value.length===16?':00':'')+'+03:00').toISOString():'';(data as unknown as Record<string,unknown>)[key]=value;if(key==='title'&&!slugManual){data.slug=productSlug(value);const slug=root!.querySelector<HTMLInputElement>('#ce-slug');if(slug)slug.value=data.slug;}if(key==='slug')slugManual=true;changed();});wrap.append(input);if(config.help)wrap.append(node('small',config.help,'dash-help'));return wrap;}
 function check(label:string,key:'isDemo'|'isLegal'|'isDraftText'){const wrap=node('label','','dash-checkbox'),input=node('input');input.type='checkbox';input.checked=data[key];input.id='ce-'+key;input.addEventListener('change',()=>{data[key]=input.checked;changed();});wrap.append(input,node('span',label));return wrap;}
 function toLocal(value:string){if(!value)return'';return new Date(Date.parse(value)+3*3600000).toISOString().slice(0,16);}
 function multi(label:string,key:'tagIds'|'productIds',choices:{id:string;name:string}[]){const wrap=node('label','','dash-field'),select=node('select');select.multiple=true;select.className='ce-select-multiple';select.id='ce-'+key;const all=[...choices,...data[key].filter(id=>!choices.some(c=>c.id===id)).map(id=>({id,name:'Недоступная запись — уберите из списка'}))];for(const row of all){const option=new Option(row.name,row.id);option.selected=data[key].includes(row.id);select.add(option);}select.addEventListener('change',()=>{data[key]=Array.from(select.selectedOptions).map(o=>o.value);changed();});wrap.append(node('span',label),select);return wrap;}
 function relations(){const c=q('[data-ce-relations]');c.replaceChildren(field('Категория','categoryId',{choices:options.categories.map(c=>({id:c.id,name:c.name+(c.status==='published'?'':' — скрыта')}))}),button('+ Новая категория',()=>taxonomy('category')),multi('Теги','tagIds',options.tags),button('+ Новый тег',()=>taxonomy('tag')),multi('Связанные товары','productIds',options.products));}
 function cover(target:'cover'|'thumbnail'='cover'){const key=target==='cover'?'coverId':'videoThumbnailId',container=target==='cover'?q('[data-ce-cover]'):q('[data-ce-video-cover]');container.replaceChildren();if(data[key]){const image=node('img');image.src=imageUrl(data[key]);image.className='ce-cover';image.alt=target==='cover'?'Обложка статьи':'Обложка видео';container.append(image,button('Убрать изображение',()=>{data[key]='';cover(target);changed();}));}const actions=node('div','','pe-inline-actions');actions.append(button('Загрузить фото',()=>chooseUpload(target)),button('Из библиотеки',()=>chooseLibrary(target)));container.append(actions);}
 function render(){epoch++;rendering=true;library.lock();data=structuredClone(state.data);slugManual=!!data.slug;pending=null;uploadQueue=[];q('[data-ce-upload-status]').replaceChildren();q('[data-ce-title]').textContent=state.live?(kind==='article'?'Редактировать статью':'Редактировать страницу'):(kind==='article'?'Новая статья':'Новая страница');q('[data-ce-status]').textContent=state.status==='archived'?'Материал удалён с сайта. Восстановите в черновик, чтобы редактировать.':state.hasDraft?'Открыт черновик. Опубликованная версия пока не меняется.':'Изменения появятся на сайте только после публикации.';
 root!.querySelectorAll<HTMLElement>('[data-ce-article]').forEach(e=>e.hidden=kind==='page');q('[data-ce-discard]').hidden=!state.hasDraft;q('[data-ce-archive]').hidden=state.status==='archived'||!state.live&&!state.hasDraft;q('[data-ce-restore]').hidden=state.status!=='archived';const publicLink=q<HTMLAnchorElement>('[data-ce-public]');publicLink.hidden=!state.live||state.status!=='published'||kind==='article'&&!!state.data.publishedAt&&Date.parse(state.data.publishedAt)>Date.now();publicLink.href=contentHref(kind,state.liveSlug??data.slug);
 q('[data-ce-main]').replaceChildren(field('Заголовок','title'),field(kind==='article'?'Краткое описание статьи':'Краткое описание страницы','summary',{type:'textarea'}));
 editor.clipboard.dangerouslyPasteHTML(data.body.replace(/(<img\b[^>]*\bsrc=")\/media\/([a-f0-9-]{36})"/gi,'$1/api/manager/product-image?id=$2"'),'silent');editor.history.clear();position=0;imageIndex=null;
 q('[data-ce-seo]').replaceChildren(field('Адрес страницы','slug',{help:'Предлагается из заголовка. Старый адрес сохранится как перенаправление.'}),field('SEO-заголовок','seoTitle'),field('Описание для поисковых систем','metaDescription',{type:'textarea'}));
 const settings=q('[data-ce-settings]');settings.replaceChildren();if(kind==='article'){settings.append(field('Дата публикации (время Москвы)','publishedAt',{type:'datetime-local',help:'Пустое поле — опубликовать сейчас. Будущая дата откладывает показ статьи.'}),check('Демонстрационная статья','isDemo'));relations();cover();const video=q('[data-ce-video]');video.replaceChildren(field('Ссылка на RUTUBE или VK Видео','videoUrl',{help:'Видео будет включаться по нажатию покупателя.'}),field('Название видео','videoTitle'),field('Описание видео','videoDescription',{type:'textarea'}),field('Дата размещения видео (Москва)','videoUploadedAt',{type:'datetime-local'}),field('Длительность, секунд','videoDuration'));const videoCover=node('div');videoCover.dataset.ceVideoCover='';video.append(node('h3','Обложка видео'),videoCover);cover('thumbnail');}else settings.append(check('Юридический документ','isLegal'),check('Показывать пометку «Проект документа»','isDraftText'),field('Порядок в меню страниц','sort'));
 q('[data-ce-count]').textContent=`Символов: ${editor.getText().trim().length}`;q('[data-ce-save-hint]').textContent=state.hasDraft?'Черновик сохранён':'Данные загружены';rendering=false;managerDirty(false);lockControls();}
 const library=productImageLibrary(q<HTMLDialogElement>('[data-image-library]'),{limit:1,used:()=>new Set([data?.coverId,data?.videoThumbnailId,...Array.from(editor.root.querySelectorAll('img')).flatMap(i=>bodyImageId(i.getAttribute('src')??'')??[])].filter(Boolean) as string[]),busy:v=>{mediaBusy=v;lockControls();},error:e=>page.showError(e)});
 function chooseLibrary(target:string){if(busy||mediaBusy)return;if(target==='inline')position=editor.getSelection(true)?.index??position;const current=epoch;library.open([],photos=>{if(current!==epoch)return;receive(photos,target);});}
 let fileTarget='inline';function chooseUpload(target:string){if(busy||mediaBusy)return;fileTarget=target;if(target==='inline')position=editor.getSelection(true)?.index??position;q<HTMLInputElement>('[data-ce-file]').click();}
 function receive(photos:EditorPhoto[],target:string){const first=photos[0];if(!first)return;if(target==='inline'){chosenPhoto=first;imageIndex=null;imageDialog(first,100);}else{data[target==='cover'?'coverId':'videoThumbnailId']=first.id;cover(target==='cover'?'cover':'thumbnail');changed();}}
 async function sendUploads(){if(busy||mediaBusy||!uploadQueue.length)return;const current=epoch;mediaBusy=true;lockControls();const status=q('[data-ce-upload-status]');try{const task=uploadQueue[0]!;status.textContent='Загружаем фотографию…';const session=await getSession(),body=new FormData();body.append('id',id);body.append('key',task.key);body.append('file',task.file);const response=await fetch('/api/manager/product-image',{method:'POST',body,headers:{'X-CSRF-Token':session.csrfToken},signal:AbortSignal.timeout(45000)}),payload=await response.json();if(!response.ok)throw new CommerceError(payload.error?.message??'Не удалось загрузить фото.',response.status);if(current!==epoch)return;uploadQueue=[];status.textContent='Фотография загружена. Сохраните изменения материала.';receive([payload],task.target);}catch(e){if(current!==epoch)return;status.replaceChildren(node('span',e instanceof Error?e.message:'Не удалось загрузить фото.'),button('Повторить загрузку',()=>void sendUploads()));if(e instanceof CommerceError&&(e.status===401||e.status===403))page.showError(e);}finally{if(current===epoch){mediaBusy=false;lockControls();}}}
 q<HTMLInputElement>('[data-ce-file]').addEventListener('change',()=>{const input=q<HTMLInputElement>('[data-ce-file]'),file=input.files?.[0];input.value='';if(file){if(fileTarget==='inline')position=editor.getSelection(true)?.index??position;uploadQueue=[{file,key:crypto.randomUUID(),target:fileTarget}];void sendUploads();}});
 q('[data-ce-upload]').addEventListener('click',()=>chooseUpload('inline'));q('[data-ce-library]').addEventListener('click',()=>chooseLibrary('inline'));
 const imageModal=q<HTMLDialogElement>('[data-ce-image-dialog]');function imageDialog(photo:EditorPhoto,width:number){q<HTMLImageElement>('[data-ce-image-preview]').src=imageUrl(photo.id);q<HTMLInputElement>('[data-ce-image-alt]').value=photo.alt;q<HTMLSelectElement>('[data-ce-image-width]').value=width+'%';q<HTMLInputElement>('[data-ce-image-caption]').value='';q('[data-ce-caption-label]').hidden=imageIndex!==null;q('[data-ce-image-apply]').textContent=imageIndex===null?'Вставить фото':'Применить';imageModal.showModal();}
 function selectImage(image:HTMLImageElement,index:number){const file=bodyImageId(image.getAttribute('src')??'');if(!file)return;imageIndex=index;position=index;chosenPhoto={id:file,alt:image.alt};imageDialog(chosenPhoto,parseInt(image.getAttribute('width')??'100')||100);}
 function editImage(){for(const image of editor.root.querySelectorAll('img')){const blot=Quill.find(image);if(blot&&!(blot instanceof Quill)){const index=editor.getIndex(blot);if(index===(imageIndex??position)||index+1===position){selectImage(image,index);return;}}}page.notify('Нажмите на фотографию в тексте, чтобы изменить её описание и размер.');}
 editor.root.addEventListener('click',event=>{if(event.target instanceof HTMLImageElement){const blot=Quill.find(event.target);if(blot&&!(blot instanceof Quill))selectImage(event.target,editor.getIndex(blot));}});q('[data-ce-image-settings]').addEventListener('click',editImage);q('[data-ce-image-close]').addEventListener('click',()=>imageModal.close());
 q('[data-ce-image-apply]').addEventListener('click',()=>{if(!chosenPhoto)return;let index=imageIndex??Math.min(position,editor.getLength()-1);const alt=q<HTMLInputElement>('[data-ce-image-alt]').value,width=q<HTMLSelectElement>('[data-ce-image-width]').value,caption=q<HTMLInputElement>('[data-ce-image-caption]').value;editor.history.cutoff();if(imageIndex===null){editor.insertText(index,'\n','api');index++;editor.insertEmbed(index,'image',imageUrl(chosenPhoto.id),'api');}editor.formatText(index,1,{alt,width},'api');if(imageIndex===null){editor.insertText(index+1,'\n'+(caption?caption+'\n':''),'api');editor.formatLine(index,caption?caption.length+2:1,{header:false,list:false,blockquote:false},'api');}imageModal.close();editor.setSelection(index+2,0,'silent');changed();});
 const preview=q<HTMLDialogElement>('[data-ce-preview]');q('[data-ce-preview-close]').addEventListener('click',()=>preview.close());q('[data-ce-show-preview]').addEventListener('click',()=>void previewMaterial());
 async function previewMaterial(){if(busy||mediaBusy)return;busy=true;lockControls();const current=epoch;try{data.body=editor.getSemanticHTML();const p=await commerceCommand<{html:string;title:string;summary:string;coverUrl:string|null;video:{provider:string}|null}>('/api/manager/content-editor',{action:'preview',kind,data});if(current!==epoch)return;q('[data-ce-preview-heading]').textContent=p.title;q('[data-ce-preview-summary]').textContent=p.summary;q('[data-ce-preview-body]').innerHTML=p.html;const image=q<HTMLImageElement>('[data-ce-preview-cover]');image.hidden=!p.coverUrl;if(p.coverUrl)image.src=p.coverUrl;else image.removeAttribute('src');q('[data-ce-preview-video]').textContent=p.video?'Видео '+p.video.provider+' появится под текстом и включится по нажатию.':'';preview.showModal();}catch(e){if(current===epoch)page.showError(e);}finally{if(current===epoch){busy=false;lockControls();}}}
 async function save(action:'draft'|'publish'|'discard'|'archive'|'restore'){if(busy||mediaBusy)return;if(['discard','archive','restore'].includes(action)&&!confirm(action==='archive'?'Убрать материал с сайта? Его можно восстановить в черновик.':action==='restore'?'Восстановить материал в черновик? Публикация выполняется отдельно.':'Сбросить черновик и несохранённые изменения?'))return;const current=epoch;data.body=editor.getSemanticHTML();const body={kind,id,version:state.version,baseHash:state.baseHash,action,data},fingerprint=JSON.stringify(body);if(pending?.fingerprint!==fingerprint)pending={fingerprint,key:crypto.randomUUID()};busy=true;lockControls();q('[data-ce-save-hint]').textContent='Сохраняем…';try{await commerceCommand('/api/manager/content-editor',{...body,idempotencyKey:pending.key});if(current!==epoch)return;pending=null;managerDirty(false);page.notify(action==='publish'?'Материал опубликован. Если указана будущая дата, статья появится в назначенное время.':action==='draft'?'Черновик сохранён. Опубликованный текст не изменён.':action==='archive'?'Материал перемещён в удалённые.':action==='restore'?'Материал восстановлен в черновик.':'Черновик сброшен.');await page.reload();}catch(e){if(current!==epoch)return;page.showError(e);q('[data-ce-save-hint]').textContent='Сохранение не подтверждено. Данные остаются в форме.';}finally{busy=false;lockControls();}}
 const taxonomyDialog=q<HTMLDialogElement>('[data-ce-taxonomy]'),taxForm=q<HTMLFormElement>('[data-ce-tax-form]');let taxKind='category',taxPending:{fingerprint:string;key:string}|null=null,taxBusy=false;
 function taxonomy(type:string){taxKind=type;taxForm.reset();q('[data-ce-tax-error]').textContent='';q('#ce-tax-title').textContent=type==='category'?'Новая категория':'Новый тег';taxonomyDialog.showModal();}
 (taxForm.elements.namedItem('name') as HTMLInputElement).addEventListener('input',()=>{(taxForm.elements.namedItem('slug') as HTMLInputElement).value=productSlug((taxForm.elements.namedItem('name') as HTMLInputElement).value);});q('[data-ce-tax-close]').addEventListener('click',()=>{if(!taxBusy)taxonomyDialog.close();});taxonomyDialog.addEventListener('cancel',e=>{if(taxBusy)e.preventDefault();});taxForm.addEventListener('submit',event=>{event.preventDefault();void(async()=>{if(taxBusy)return;const current=epoch;const values=new FormData(taxForm),body={action:'taxonomy',taxonomy:taxKind,name:String(values.get('name')),slug:String(values.get('slug'))},fingerprint=JSON.stringify(body);if(taxPending?.fingerprint!==fingerprint)taxPending={fingerprint,key:crypto.randomUUID()};taxBusy=true;taxForm.querySelector<HTMLButtonElement>('button')!.disabled=true;try{const result=await commerceCommand<{id:string;name:string;slug:string}>('/api/manager/content-editor',{...body,idempotencyKey:taxPending.key});if(current!==epoch)return;if(taxKind==='category'){options.categories.push({...result,status:'published'});data.categoryId=result.id;}else{options.tags.push(result);data.tagIds.push(result.id);}taxPending=null;taxonomyDialog.close();relations();changed();}catch(e){if(current!==epoch)return;q('[data-ce-tax-error]').textContent=e instanceof Error?e.message:'Не удалось создать запись.';if(e instanceof CommerceError&&(e.status===401||e.status===403))page.showError(e);}finally{taxBusy=false;taxForm.querySelector<HTMLButtonElement>('button')!.disabled=false;}})();});
 form.addEventListener('submit',e=>{e.preventDefault();void save('publish');});for(const action of ['draft','discard','archive','restore'] as const)q(action==='draft'?'[data-ce-save]':`[data-ce-${action}]`).addEventListener('click',()=>void save(action));
 const page=managerPage(root,async signal=>{const [loaded,refs]=await Promise.all([page.get<ContentState>(`/api/manager/content-editor?kind=${kind}&id=${id}`,signal),page.get<ContentOptions>('/api/manager/content-editor?options=1',signal)]);return()=>{state=loaded;options=refs;render();};});
 root.addEventListener('autoreelz:manager-locked',()=>{epoch++;rendering=true;library.lock();editor.setText('','silent');editor.enable(false);data=undefined as unknown as ContentData;pending=null;taxPending=null;taxBusy=false;uploadQueue=[];chosenPhoto=null;busy=mediaBusy=false;imageModal.querySelectorAll<HTMLInputElement>('input').forEach(i=>i.value='');taxForm.reset();root.querySelectorAll<HTMLInputElement>('.ql-tooltip input').forEach(i=>i.value='');q<HTMLAnchorElement>('[data-ce-public]').removeAttribute('href');root.querySelectorAll('dialog').forEach(d=>d.close());for(const selector of ['[data-ce-main]','[data-ce-cover]','[data-ce-relations]','[data-ce-video]','[data-ce-seo]','[data-ce-settings]','[data-ce-preview-body]','[data-ce-preview-heading]','[data-ce-preview-summary]','[data-ce-preview-video]'])q(selector).replaceChildren();q<HTMLImageElement>('[data-ce-image-preview]').removeAttribute('src');q<HTMLImageElement>('[data-ce-preview-cover]').removeAttribute('src');q('[data-ce-status]').textContent='';q('[data-ce-upload-status]').replaceChildren();});
 void page.reload();
}
