import {russianValidation} from './russian-validation';
import {commerceCommand,CommerceError} from './commerce';
import {formatRubles as money} from '../lib/money';
import {dashboardPeriod,dashboardFilter,dashboardLabels,type DashboardData,type DashboardPeriod,type DashboardFilter} from '../lib/dashboard';
const root=document.querySelector<HTMLElement>('[data-dashboard]');
if(root){
 const $=<T extends HTMLElement=HTMLElement>(s:string)=>root.querySelector<T>(s)!;
 const node=<K extends keyof HTMLElementTagNameMap>(tag:K,text='',className='')=>{const n=document.createElement(tag);n.textContent=text;n.className=className;return n;};
 const date=(s:string)=>new Intl.DateTimeFormat('ru-RU',{timeZone:'Europe/Moscow',dateStyle:'short',timeStyle:'short'}).format(new Date(s));
 const link=(text:string,href:string)=>{const a=node('a',text);a.href=href;return a;};
 const storageKey='autoreelz.owner.dashboard.v1';let saved:Record<string,unknown>={};try{saved=JSON.parse(localStorage.getItem(storageKey)??'{}')??{};}catch{}
 let period:DashboardPeriod='7',filter:DashboardFilter='all';const params=new URLSearchParams(location.search);
 try{period=dashboardPeriod(params.get('period')??String(saved.period??'7'));filter=dashboardFilter(params.get('filter')??String(saved.filter??'all'));}catch{}
 const thresholdOptions=[0,1,3,5,10,20,50,100];let threshold=thresholdOptions.includes(Number(saved.threshold))?Number(saved.threshold):3;
 let data:DashboardData|null=null,serial=0,controller:AbortController|null=null,busy=false,lastRefresh=0;
 const content=$('[data-dash-content]'),controls=$('[data-dash-controls]'),login=$('[data-dash-login]'),errorBox=$('[data-dash-error]');
 $<HTMLSelectElement>('[data-period]').value=period;$<HTMLSelectElement>('[data-threshold]').value=String(threshold);$<HTMLInputElement>('[data-stock-low]').checked=saved.low!==false;
 function save(){try{localStorage.setItem(storageKey,JSON.stringify({period,filter,threshold,low:$<HTMLInputElement>('[data-stock-low]').checked}));}catch{}const u=new URL(location.href);u.searchParams.set('period',period);u.searchParams.set('filter',filter);history.replaceState(null,'',u.pathname+u.search+u.hash);}
 function showError(e:unknown){errorBox.textContent=(e instanceof Error?e.message:'Не удалось обновить данные.')+(data?` Показаны данные последнего успешного обновления за период: ${data.period==='today'?'сегодня':data.period+' дней'}.`:'');errorBox.hidden=false;}
 const statusLabels:Record<string,string>={open:'Уточнить доставку',preorder_pending:'Подтвердить предзаказ',awaiting_payment:'Ожидает оплаты',paid:'Тестовая оплата получена',expired:'Срок истёк',cancelled:'Отменён',manual_review:'Проверить оплату'};
 const shippingLabels:Record<string,string>={pending_quote:'Доставка уточняется',quoted:'Доставка рассчитана',packing:'Сборка',shipped:'Отправлен',delivered:'Получен'};
 function renderOrders(){if(!data)return;const body=$('[data-orders]');body.replaceChildren();$('[data-list-title]').textContent=dashboardLabels[filter];$('[data-list-count]').textContent=`За всё время · показано ${data.orders.length} из ${data.orderCount}`;$('[data-orders-empty]').hidden=Boolean(data.orders.length);
  for(const order of data.orders){const tr=node('tr'),id=node('td'),kind=node('td',order.kind==='preorder'?'Предзаказ':'В наличии'),status=node('td'),price=node('td',money(order.productTotalRubles),'dash-number');id.append(link(order.number,'/manager/orders?order='+encodeURIComponent(order.id)),node('small',date(order.createdAt)));const tags=node('div','','dash-tags');tags.append(node('span',statusLabels[order.status]??order.status,'dash-tag '+(order.status==='paid'?'positive':order.status==='manual_review'?'danger':'warning')));if(order.status==='paid')tags.append(node('span',shippingLabels[order.deliveryStatus]??order.deliveryStatus,'dash-tag'));status.append(tags);tr.append(id,kind,status,price);body.append(tr);}
 }
 function renderStock(){if(!data)return;const low=data.stock.filter(s=>s.available<=threshold);$('[data-count="stock"]').textContent=String(low.length);const query=$<HTMLInputElement>('[data-stock-search]').value.trim().toLocaleLowerCase('ru-RU');const items=($<HTMLInputElement>('[data-stock-low]').checked?low:data.stock).filter(s=>`${s.article} ${s.name} ${s.productName}`.toLocaleLowerCase('ru-RU').includes(query));$('[data-stock-count]').textContent=`Показано ${items.length} из ${data.stock.length} исполнений · порог ≤ ${threshold} шт.`;$('[data-stock-empty]').hidden=Boolean(items.length);const body=$('[data-stock]');body.replaceChildren();for(const s of items){const tr=node('tr'),name=node('td'),action=node('td');name.append(node('strong',s.article),node('small',s.productName+' · '+s.name+(s.status==='draft'?' · черновик':'')));action.append(link('Изменить','/manager/orders?sku='+encodeURIComponent(s.skuId)+'#manager-stock-adjust'));tr.append(name,node('td',String(s.onHand),'dash-number'),node('td',String(s.reserved),'dash-number'),node('td',String(s.available),'dash-number'+(s.available<=threshold?' dash-low':'')),action);body.append(tr);}}
 function renderQuality(){if(!data)return;$('[data-quality-count]').textContent=`Товаров с незаполненными данными: ${data.quality.length}`;$('[data-quality-empty]').hidden=Boolean(data.quality.length);const box=$('[data-quality]');box.replaceChildren();for(const product of data.quality){const row=node('div','','dash-quality-row'),copy=node('div');copy.append(link(product.name,`${root!.dataset.cmsUrl}/content/ar_products/${product.id}`),node('p',product.issues.join(' · ')));row.append(copy,node('span',product.status==='draft'?'Черновик':'Опубликован','dash-tag'));box.append(row);}const bundles=$('[data-bundles]');bundles.replaceChildren();if(!data.bundles.length)bundles.append(node('p','Недемонстрационных комплектов пока нет.','dash-empty'));for(const b of data.bundles){const row=node('div','','dash-bundle-row');row.append(link(b.name,`${root!.dataset.cmsUrl}/content/ar_products/${b.id}`),node('strong',b.available===null?'Не задан состав':`Доступно: ${b.available}`));bundles.append(row);}}
 function renderChart(){if(!data||content.hidden)return;const box=$('[data-chart]'),w=Math.max(240,box.clientWidth),h=238,left=58,right=14,top=18,bottom=34,plotH=h-top-bottom;box.replaceChildren();const ns='http://www.w3.org/2000/svg';const svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox',`0 0 ${w} ${h}`);svg.setAttribute('role','img');svg.setAttribute('aria-label',`Оплата товаров за выбранный период: ${money(data.metrics.productRubles)}. ${data.metrics.paidOrders} подтверждённых тестовых заказов.`);const max=Math.max(...data.series.map(s=>Number(s.productRubles)),1),step=(w-left-right)/data.series.length;
  const mark=(tag:string,attrs:Record<string,string>,text='')=>{const n=document.createElementNS(ns,tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);n.textContent=text;svg.append(n);return n;};
  for(let i=0;i<=2;i++){const v=max*i/2,y=top+plotH-plotH*i/2;mark('line',{x1:String(left),x2:String(w-right),y1:String(y),y2:String(y),class:'chart-grid'});mark('text',{x:String(left-7),y:String(y+4),'text-anchor':'end',class:'chart-label'},new Intl.NumberFormat('ru-RU',{notation:'compact',maximumFractionDigits:1}).format(v));}
  const detail=node('p','Выберите столбец, чтобы увидеть сумму за день.','dash-chart-tooltip');detail.setAttribute('role','status');const labelEvery=Math.max(1,Math.ceil(data.series.length/(w<450?4:7)));
  for(const[s,i]of data.series.map((s,i)=>[s,i] as const)){const x=left+i*step+step*.15,height=Number(s.productRubles)/max*plotH;mark('rect',{x:String(x),y:String(top+plotH-height),width:String(Math.max(1,step*.7)),height:String(height),rx:'2',class:'chart-bar'});const hit=mark('rect',{x:String(left+i*step),y:String(top),width:String(step),height:String(plotH),class:'chart-hit'});const show=()=>{detail.textContent=`${new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'long',timeZone:'Europe/Moscow'}).format(new Date(s.day+'T12:00:00+03:00'))}: ${money(s.productRubles)} · заказов ${s.orders}`;};hit.addEventListener('pointerenter',show);hit.addEventListener('click',show);const title=document.createElementNS(ns,'title');title.textContent=`${s.day}: ${money(s.productRubles)}`;hit.append(title);if(i%labelEvery===0||i===data.series.length-1&&data.series.length-1-(Math.floor((i-1)/labelEvery)*labelEvery)>1)mark('text',{x:String(left+(i+.5)*step),y:String(h-10),'text-anchor':'middle',class:'chart-label'},s.day.slice(8)+'.'+s.day.slice(5,7));}
  const accessible=node('details','','dash-help');accessible.append(node('summary','Суммы по дням'));const list=node('ul');for(const s of data.series)list.append(node('li',`${s.day}: ${money(s.productRubles)}, заказов ${s.orders}`));accessible.append(list);box.append(svg,detail,accessible);$('[data-chart-empty]').hidden=data.metrics.paidOrders>0;
 }
 function render(){if(!data)return;content.hidden=false;controls.hidden=false;login.hidden=true;$('[data-kpi="products"]').textContent=money(data.metrics.productRubles);$('[data-kpi="orders"]').textContent=String(data.metrics.paidOrders);$('[data-kpi="average"]').textContent=money(data.metrics.averageRubles);$('[data-kpi="work"]').textContent=String(data.metrics.inWork);$('[data-order-split]').textContent=`Из наличия: ${data.metrics.ordinary} · предзаказы: ${data.metrics.preorder}`;$('[data-shipping]').textContent=money(data.metrics.shippingRubles);for(const[k,v]of Object.entries(data.tasks))$(`[data-count="${k}"]`).textContent=String(v);root!.querySelectorAll<HTMLButtonElement>('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.filter===filter)));root!.querySelectorAll<HTMLButtonElement>('[data-task]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.task===filter)));renderOrders();renderStock();renderQuality();renderChart();$('[data-updated]').textContent=`Обновлено ${date(data.generatedAt)} · МСК`;}
 async function load(){const id=++serial;controller?.abort();controller=new AbortController();const current=controller;busy=true;$<HTMLButtonElement>('[data-refresh]').disabled=true;try{const response=await fetch(`/api/manager/dashboard?period=${period}&filter=${filter}`,{credentials:'same-origin',cache:'no-store',signal:AbortSignal.any([current.signal,AbortSignal.timeout(20000)])});const payload=await response.json();if(id!==serial)return;if(!response.ok)throw new CommerceError(payload?.error?.message??'Не удалось обновить обзор.',response.status);if(!payload?.metrics||!Array.isArray(payload.orders)||payload.period!==period||payload.filter!==filter)throw new Error('Invalid dashboard response');data=payload;lastRefresh=Date.now();errorBox.hidden=true;render();}catch(e){if(id!==serial||current.signal.aborted)return;if(e instanceof CommerceError&&(e.status===401||e.status===403)){data=null;content.hidden=true;controls.hidden=true;login.hidden=false;$('[data-orders]').replaceChildren();$('[data-stock]').replaceChildren();$('[data-quality]').replaceChildren();if(e.status===403)showError(e);else errorBox.hidden=true;}else{controls.hidden=false;showError(e instanceof CommerceError?e:new Error('Не удалось связаться с магазином. Повторите обновление.'));}}finally{if(id===serial){busy=false;$('[data-loading]').hidden=true;$<HTMLButtonElement>('[data-refresh]').disabled=false;}}}
 const form=$<HTMLFormElement>('[data-dash-login-form]');russianValidation(form);form.addEventListener('submit',async e=>{e.preventDefault();const submit=form.querySelector<HTMLButtonElement>('button')!;submit.disabled=true;errorBox.hidden=true;try{const fields=new FormData(form);await commerceCommand('/api/manager/login',{email:fields.get('email'),password:fields.get('password')});(form.elements.namedItem('password') as HTMLInputElement).value='';await load();}catch(error){showError(error);}finally{submit.disabled=false;}});
 $<HTMLSelectElement>('[data-period]').addEventListener('change',e=>{period=dashboardPeriod((e.target as HTMLSelectElement).value);save();void load();});root.querySelectorAll<HTMLButtonElement>('[data-filter],[data-task]').forEach(b=>b.addEventListener('click',()=>{filter=dashboardFilter(b.dataset.filter??b.dataset.task??null);save();void load();if(b.dataset.task)$('[data-list-title]').scrollIntoView({block:'center',behavior:'auto'});}));$('[data-refresh]').addEventListener('click',()=>void load());$<HTMLSelectElement>('[data-threshold]').addEventListener('change',e=>{threshold=Number((e.target as HTMLSelectElement).value);save();renderStock();});$('[data-stock-low]').addEventListener('change',()=>{save();renderStock();});$('[data-stock-search]').addEventListener('input',renderStock);
 let resizeTimer:ReturnType<typeof setTimeout>,chartWidth=0;new ResizeObserver(entries=>{const width=entries[0]?.contentRect.width??0;if(Math.abs(width-chartWidth)<1)return;chartWidth=width;clearTimeout(resizeTimer);resizeTimer=setTimeout(renderChart,100);}).observe($('[data-chart]'));
 const auto=()=>{if(!document.hidden&&!busy&&data&&Date.now()-lastRefresh>=60000&&!document.activeElement?.closest('[data-orders],[data-stock],[data-quality]'))void load();};setInterval(auto,60000);document.addEventListener('visibilitychange',auto);
 if(/^#manager-/.test(location.hash))location.replace('/manager/orders'+location.search+location.hash);else void load();
}
