import {managerPage,node,link,managerDate} from './manager-page';
import {orderListQuery,paymentLabels,deliveryLabels,type OrderList} from '../lib/manager-workspace';
import {formatRubles as money} from '../lib/money';
const root=document.querySelector<HTMLElement>('[data-workspace="orders"]');
if(root){const $=<T extends HTMLElement=HTMLElement>(s:string)=>root.querySelector<T>(s)!;const form=$<HTMLFormElement>('[data-order-filters]');let timer:ReturnType<typeof setTimeout>;
 function fill(){const p=new URLSearchParams(location.search);for(const name of ['q','kind','payment','delivery','task','from','to']){const field=form.elements.namedItem(name) as HTMLInputElement|HTMLSelectElement;field.value=p.get(name)??(field instanceof HTMLSelectElement?'all':'');}}
 function setQuery(params:URLSearchParams,push=false){const url='/manager/orders'+(params.size?'?'+params:'');history[push?'pushState':'replaceState'](null,'',url);void page.reload();}
 function apply(){const p=new URLSearchParams();for(const [key,value]of new FormData(form))if(typeof value==='string'&&value.trim()&&value!=='all')p.set(key,value.trim());try{orderListQuery(p);setQuery(p);}catch(e){page.showError(e);}}
 function render(data:OrderList){const list=$('[data-order-list]');list.replaceChildren();$('[data-orders-total]').textContent=`Всего: ${data.total}`;$('[data-list-empty]').hidden=data.items.length>0;
  for(const o of data.items){const tr=node('tr');tr.dataset.orderRow=o.id;const cell=(label:string,text='',cls='')=>{const td=node('td',text,cls);td.dataset.label=label;return td;};const id=cell('Заказ');const back=new URL(location.href);back.searchParams.delete('restore');const href=`/manager/orders/${o.id}?returnTo=${encodeURIComponent(back.pathname+back.search)}`;const a=link(o.number,href);a.addEventListener('click',()=>{try{sessionStorage.setItem('autoreelz.manager.orders.scroll',String(scrollY));}catch{}});id.append(a,node('small',managerDate(o.createdAt)+' · '+(o.kind==='preorder'?'Предзаказ':'Из наличия')));const payment=cell('Оплата'),delivery=cell('Доставка');payment.append(node('span',['cancelled','expired'].includes(o.status)?(o.status==='cancelled'?'Отменён':'Срок истёк'):paymentLabels[o.paymentStatus]??o.paymentStatus,'dash-tag '+(o.paymentStatus==='paid'?'positive':o.paymentStatus==='review'?'danger':'warning')));delivery.append(node('span',deliveryLabels[o.deliveryStatus]??o.deliveryStatus,'dash-tag'));tr.append(id,cell('Покупатель',o.customerName),payment,delivery,cell('Сумма',o.totalRubles===null?`${money(o.productTotalRubles)} + доставка`:money(o.totalRubles),'dash-number'));list.append(tr);}
  const pagination=$('[data-order-pagination]');pagination.replaceChildren();const move=(step:number,label:string)=>{const b=node('button',label,'dash-button');b.type='button';b.disabled=step<0?data.page<=1:data.page>=data.pages;b.addEventListener('click',()=>{const p=new URLSearchParams(location.search);p.delete('restore');p.set('page',String(data.page+step));setQuery(p,true);$('[data-orders-total]').scrollIntoView({block:'center'});});return b;};pagination.append(move(-1,'← Назад'),node('span',`Страница ${data.page} из ${data.pages}`),move(1,'Далее →'));const current=new URLSearchParams(location.search);if(data.page!==Number(current.get('page')??1)){current.set('page',String(data.page));history.replaceState(null,'','/manager/orders?'+current);}
  if(current.has('restore')){let y=0;try{y=Number(sessionStorage.getItem('autoreelz.manager.orders.scroll')??0);}catch{}current.delete('restore');history.replaceState(null,'','/manager/orders'+(current.size?'?'+current:''));requestAnimationFrame(()=>scrollTo(0,Math.max(0,Number.isFinite(y)?y:0)));}
 }
 const page=managerPage(root,async signal=>{const data=await page.get<OrderList>('/api/manager/order-list?'+new URLSearchParams(location.search),signal);return()=>render(data);});fill();form.addEventListener('submit',e=>{e.preventDefault();clearTimeout(timer);apply();});form.querySelector<HTMLInputElement>('[name=q]')!.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(apply,350);});form.querySelectorAll('select,input[type=date]').forEach(e=>e.addEventListener('change',apply));form.addEventListener('reset',()=>setTimeout(apply,0));window.addEventListener('popstate',()=>{fill();void page.reload();});void page.reload();
}
