import {managerPage,node,link,managerDate,managerDirty} from './manager-page';
import {commerceCommand} from './commerce';
import {russianValidation} from './russian-validation';
import type {InventoryItem,StockHistory} from '../lib/manager-workspace';
const root=document.querySelector<HTMLElement>('[data-workspace="stock"]');
if(root){const $=<T extends HTMLElement=HTMLElement>(s:string)=>root.querySelector<T>(s)!;const dialog=$<HTMLDialogElement>('[data-stock-dialog]'),form=$<HTMLFormElement>('[data-stock-operation]'),amount=form.elements.namedItem('amount') as HTMLInputElement,reason=form.elements.namedItem('reason') as HTMLInputElement,error=$('[data-stock-error]');let items:InventoryItem[]=[],current:InventoryItem|undefined,operation='receive',pageIndex=1,historyPage=1,modalSerial=0,saving=false,dirty=false,linked=false,returnFocus:HTMLElement|null=null;
 const options=[0,1,3,5,10,20,50,100];try{const old=JSON.parse(localStorage.getItem('autoreelz.owner.dashboard.v1')??'{}');if(options.includes(Number(old.threshold)))$<HTMLSelectElement>('[data-inventory-threshold]').value=String(old.threshold);}catch{}
 const params=new URLSearchParams(location.search);$<HTMLInputElement>('[data-inventory-low]').checked=params.get('low')==='1';if(params.get('q'))$<HTMLInputElement>('[data-inventory-search]').value=params.get('q')!;
 function setDirty(value:boolean){dirty=value;managerDirty(value);}
 function close(){if(saving)return;if(dirty&&!confirm('Закрыть форму без сохранения изменений?'))return;dialog.close();}
 dialog.addEventListener('cancel',e=>{e.preventDefault();close();});$('[data-close-stock]').addEventListener('click',close);dialog.addEventListener('close',()=>{modalSerial++;setDirty(false);returnFocus?.focus({preventScroll:true});});
 const button=(text:string,action:()=>void)=>{const b=node('button',text,'dash-button');b.type='button';b.addEventListener('click',action);return b;};
 async function history(){if(!current)return;const serial=++modalSerial;$('[data-stock-history-status]').textContent='Загружаем движения…';try{const data=await page.get<StockHistory>(`/api/manager/stock-history?sku=${current.skuId}&page=${historyPage}`,AbortSignal.timeout(15000));if(serial!==modalSerial||!dialog.open)return;const list=$('[data-stock-history-list]');list.replaceChildren();$('[data-stock-history-status]').textContent=`Всего движений: ${data.total}`;if(!data.items.length)list.append(node('p','Движений пока нет.','dash-empty'));for(const event of data.items){const row=node('article','','mgr-movement');row.append(node('strong',event.reason),node('p',`${managerDate(event.at)} · ${event.byManager?'Сотрудник':'Система'}`,'dash-help'),node('p',`Остаток: ${event.stockDelta>0?'+':''}${event.stockDelta} · Резерв: ${event.reservedDelta>0?'+':''}${event.reservedDelta}`));if(event.orderId)row.append(link(event.orderNumber??'Открыть заказ','/manager/orders/'+event.orderId));list.append(row);}const nav=$('[data-stock-history-pagination]'),prev=button('← Назад',()=>{historyPage--;void history();}),next=button('Далее →',()=>{historyPage++;void history();});prev.disabled=data.page<=1;next.disabled=data.page>=data.pages;nav.replaceChildren(prev,node('span',`${data.page} / ${data.pages}`),next);}catch(e){if(serial!==modalSerial)return;error.textContent=e instanceof Error?e.message:'Не удалось загрузить историю.';error.hidden=false;page.showError(e);}}
 function open(item:InventoryItem,action:string,from?:HTMLElement){current=item;operation=action;returnFocus=from??$('[data-inventory-search]');historyPage=1;modalSerial++;setDirty(false);error.hidden=true;form.reset();$('[data-stock-dialog-title]').textContent=action==='history'?'История движений':action==='adjust'?'Корректировка остатка':'Приход товара';$('[data-stock-dialog-item]').textContent=`${item.article} · ${item.productName} · ${item.name}`;$('[data-stock-form-box]').hidden=action==='history';$('[data-stock-history-box]').hidden=action!=='history';$('[data-stock-history-list]').replaceChildren();$('[data-stock-history-pagination]').replaceChildren();$('[data-stock-current]').textContent=`На складе: ${item.onHand} · резерв: ${item.reserved} · свободно: ${item.available}.`;
  $<HTMLLabelElement>('[data-stock-amount-label]').firstChild!.textContent=action==='adjust'?'Фактический остаток, шт.':'Поступило, шт.';amount.min=String(action==='adjust'?item.reserved:1);amount.max=action==='adjust'?'1000000':'100000';amount.value=action==='adjust'?String(item.onHand):'';$('[data-save-stock]').textContent=action==='adjust'?'Сохранить остаток':'Принять на склад';dialog.showModal();if(action==='history')void history();else amount.focus();}
 function render(){const q=$<HTMLInputElement>('[data-inventory-search]').value.trim().toLocaleLowerCase('ru-RU'),threshold=Number($<HTMLSelectElement>('[data-inventory-threshold]').value),low=$<HTMLInputElement>('[data-inventory-low]').checked,demo=$<HTMLInputElement>('[data-inventory-demo]').checked,archive=$<HTMLInputElement>('[data-inventory-archived]').checked;const filtered=items.filter(s=>(demo||!s.isDemo)&&(archive||s.status!=='archived'&&s.productStatus!=='archived')&&(!low||s.available<=threshold)&&`${s.article} ${s.name} ${s.productName}`.toLocaleLowerCase('ru-RU').includes(q));const pages=Math.max(1,Math.ceil(filtered.length/20));pageIndex=Math.min(pageIndex,pages);const body=$('[data-inventory-list]');body.replaceChildren();$('[data-inventory-count]').textContent=`Найдено: ${filtered.length} · порог ≤ ${threshold}`;$('[data-inventory-empty]').hidden=filtered.length>0;
  for(const item of filtered.slice((pageIndex-1)*20,pageIndex*20)){const row=node('tr');row.dataset.inventoryRow=item.skuId;const cell=(label:string,text='',cls='')=>{const td=node('td',text,cls);td.dataset.label=label;return td;};const name=cell('Исполнение');name.append(node('strong',item.article),node('small',item.productName+' · '+item.name));if(item.isDemo||item.status!=='published'||item.productStatus!=='published')name.append(node('small',item.isDemo?'Демонстрационное':item.status==='archived'||item.productStatus==='archived'?'Архивное':'Черновик'));const actions=cell('Действия');const group=node('div','','mgr-row-actions');for(const[action,label]of [['receive','Приход'],['adjust','Остаток'],['history','История']]){const b=button(label!,()=>open(item,action!,b));b.dataset.stockAction=action;b.dataset.sku=item.skuId;group.append(b);}actions.append(group);row.append(name,cell('На складе',String(item.onHand),'dash-number'),cell('Резерв',String(item.reserved),'dash-number'),cell('Свободно',String(item.available),'dash-number'+(item.available<=threshold?' dash-low':'')),actions);body.append(row);}
  const nav=$('[data-inventory-pagination]'),prev=button('← Назад',()=>{pageIndex--;render();}),next=button('Далее →',()=>{pageIndex++;render();});prev.disabled=pageIndex<=1;next.disabled=pageIndex>=pages;nav.replaceChildren(prev,node('span',`Страница ${pageIndex} из ${pages}`),next);
 }
 const page=managerPage(root,async signal=>{const result=await page.get<{items:InventoryItem[]}>('/api/manager/inventory',signal);return()=>{items=result.items;render();if(!linked&&params.has('sku')){linked=true;const item=items.find(s=>s.skuId===params.get('sku'));if(item)open(item,params.get('action')==='receive'?'receive':'adjust');else page.showError(new Error('Исполнение не найдено.'));}};});
 russianValidation(form);form.addEventListener('input',()=>setDirty(true));form.addEventListener('submit',async e=>{e.preventDefault();if(saving||!current)return;const value=Number(amount.value);if(!Number.isSafeInteger(value)||value<(operation==='adjust'?current.reserved:1)){error.textContent='Укажите целое количество с учётом текущего резерва.';error.hidden=false;return;}saving=true;error.hidden=true;const fields=[...form.querySelectorAll<HTMLInputElement|HTMLButtonElement>('input,button')];fields.forEach(f=>f.disabled=true);try{await commerceCommand(operation==='adjust'?'/api/manager/stock-adjust':'/api/manager/stock',operation==='adjust'?{skuId:current.skuId,onHand:value,reason:reason.value.trim()}:{skuId:current.skuId,quantity:value,reason:reason.value.trim()});setDirty(false);dialog.close();page.notify(operation==='adjust'?'Фактический остаток сохранён.':'Приход товара проведён.');await page.reload();$('[data-inventory-search]').focus({preventScroll:true});}catch(e){error.textContent=e instanceof Error?e.message:'Не удалось сохранить изменения.';error.hidden=false;page.showError(e);}finally{saving=false;fields.forEach(f=>f.disabled=false);}});
 root.querySelectorAll<HTMLInputElement|HTMLSelectElement>('[data-inventory-search],[data-inventory-threshold],[data-inventory-low],[data-inventory-demo],[data-inventory-archived]').forEach(input=>input.addEventListener(input instanceof HTMLInputElement&&input.type==='search'?'input':'change',()=>{pageIndex=1;render();if(input.matches('[data-inventory-threshold]'))try{const saved=JSON.parse(localStorage.getItem('autoreelz.owner.dashboard.v1')??'{}');localStorage.setItem('autoreelz.owner.dashboard.v1',JSON.stringify({...saved,threshold:Number(input.value)}));}catch{}}));void page.reload();
}
