import {commerceCommand,commerceGet,CommerceError} from './commerce';
import type {ManagerOrderView,OwnerNotification,GenerationProduct,DescriptionDraft} from '../lib/management-types';
import type {ReviewView} from '../lib/social-types';

type OwnerHooks={refresh:()=>Promise<void>;error:(error:unknown)=>void;notify:(message:string)=>void};
type StockItem={skuId:string;article:string;name:string;onHand:number;reserved:number;available:number};
const $=<T extends Element=HTMLElement>(selector:string,root:ParentNode=document)=>root.querySelector<T>(selector);
const date=(value:string)=>new Intl.DateTimeFormat('ru-RU',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value));
const deliveryLabels:Record<string,string>={pending_quote:'Стоимость уточняется',quoted:'Доставка рассчитана',packing:'Сборка',shipped:'Отправлен',delivered:'Получен'};
const sourceLabels:Record<string,string>={checkout:'Оформление заказа',manager:'Сотрудник',carrier:'Перевозчик'};
function node<K extends keyof HTMLElementTagNameMap>(tag:K,text='',className=''):HTMLElementTagNameMap[K]{const element=document.createElement(tag);element.textContent=text;element.className=className;return element;}
function button(label:string,kind='button-secondary',submit=false){const element=node('button',label,kind);element.type=submit?'submit':'button';return element;}
function textField(label:string,name:string,value='',multiline=false){const wrapper=node('label',label,'field'),input=multiline?node('textarea'):node('input');input.name=name;input.value=value;if(input instanceof HTMLTextAreaElement)input.rows=3;wrapper.append(input);return{wrapper,input};}
function selectField(label:string,name:string,options:[string,string][],value?:string){const wrapper=node('label',label,'field'),input=node('select');input.name=name;for(const [key,text]of options)input.append(new Option(text,key));if(value!==undefined)input.value=value;wrapper.append(input);return{wrapper,input};}
function reasonField(label='Причина',name='reason'){const field=textField(label,name);field.input.required=true;field.input.minLength=3;field.input.maxLength=500;return field;}
function note(text:string,warning=false){return node('p',text,warning?'notice warning':'notice');}
function blank(title:string,text:string){const panel=node('div','','owner-empty');panel.append(node('h2',title),node('p',text));return panel;}
function localDateTime(){const now=new Date();return new Date(now.getTime()-now.getTimezoneOffset()*60000).toISOString().slice(0,19);}
function clearError(){const error=$<HTMLElement>('[data-owner-error]');if(error){error.hidden=true;error.textContent='';}}
function pageError(error:unknown){const panel=$<HTMLElement>('[data-owner-error]');if(!panel)return;panel.textContent=error instanceof Error?error.message:'Не удалось выполнить действие.';panel.hidden=false;panel.focus({preventScroll:true});panel.scrollIntoView({block:'nearest'});}
function success(message:string){const panel=$<HTMLElement>('[data-owner-success]');if(panel){panel.textContent=message;panel.hidden=false;}}
async function run(control:HTMLElement,work:()=>Promise<void>,onError:(error:unknown)=>void=pageError){if(control.getAttribute('aria-busy')==='true')return;clearError();control.setAttribute('aria-busy','true');const controls=control instanceof HTMLButtonElement?[control]:[...control.querySelectorAll<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement|HTMLButtonElement>('input,select,textarea,button')];const disabled=controls.map(input=>input.disabled);controls.forEach(input=>input.disabled=true);try{await work();}catch(error){onError(error);}finally{control.removeAttribute('aria-busy');controls.forEach((input,index)=>input.disabled=disabled[index]!);}}
const openOrders=new Set<string>();

export function appendOwnerOrderTools(card:HTMLElement,order:ManagerOrderView,hooks:OwnerHooks){
 const details=node('details','','owner-tools');details.dataset.ownerOrderTools=order.id;details.open=openOrders.has(order.id);details.addEventListener('toggle',()=>{if(details.open)openOrders.add(order.id);else openOrders.delete(order.id);});details.append(node('summary','Заметки и управление заказом'));
 const content=node('div','','owner-tools-content');
 const notes=node('section','','owner-tool-block');notes.append(node('h4','Внутренние заметки'),node('p','Эти заметки видит только владелец. Покупателю они не передаются.','field-help'));
 const notesList=node('div','','owner-notes');for(const item of order.notes??[]){const row=node('article','','owner-note');const time=node('time',date(item.createdAt));time.dateTime=item.createdAt;row.append(node('p',item.body),time);notesList.append(row);}if(!(order.notes??[]).length)notesList.append(node('p','Заметок пока нет.','field-help'));notes.append(notesList);
 const noteForm=node('form','','commerce-form');noteForm.dataset.orderNoteForm='';const body=textField('Новая заметка','note','',true);body.input.required=true;body.input.minLength=2;body.input.maxLength=2000;noteForm.append(body.wrapper,button('Добавить заметку','button',true));noteForm.addEventListener('submit',event=>{event.preventDefault();void run(card,async()=>{await commerceCommand<ManagerOrderView>('/api/manager/note',{orderId:order.id,note:body.input.value.trim()});body.input.value='';hooks.notify('Внутренняя заметка добавлена.');await hooks.refresh();},hooks.error);});notes.append(noteForm);content.append(notes);
 const delivery=node('section','','owner-tool-block');delivery.append(node('h4','Отправление'));const state=node('div','','owner-delivery-state');state.append(node('span',deliveryLabels[order.deliveryStatus]??order.deliveryStatus,'status-pill'),node('span',`Источник: ${sourceLabels[order.deliverySource]??order.deliverySource}`,'owner-source'));delivery.append(state);if(order.trackingNumber)delivery.append(node('p',`Трек-номер: ${order.trackingNumber}`,'owner-tracking'));if(order.deliveredAt)delivery.append(node('p',`Получен: ${date(order.deliveredAt)}`,'field-help'));
 if(order.deliveryOverride)delivery.append(note('Включено ручное управление. События перевозчика сохраняются в истории, но не меняют выбранный статус. Чтобы снова применять их, снимите ручное управление.',true));
 if(order.status==='paid'){
  const next:Record<string,string>={quoted:'packing',packing:'shipped',shipped:'delivered'};const nextStatus=next[order.deliveryStatus];
  if(nextStatus){const form=node('form','','commerce-form');form.dataset.fulfillmentForm='';const status=selectField('Следующий этап','status',[[nextStatus,deliveryLabels[nextStatus]!]]);const tracking=textField('Трек-номер','trackingNumber',order.trackingNumber??'');tracking.input.maxLength=120;tracking.input.minLength=3;tracking.input.required=['shipped','delivered'].includes(nextStatus);const reason=reasonField('Комментарий к переходу');form.append(status.wrapper,tracking.wrapper,reason.wrapper,node('p','Действие сотрудника включает ручное управление доставкой.','field-help'),button('Подтвердить этап отправления','button',true));form.addEventListener('submit',event=>{event.preventDefault();void run(card,async()=>{await commerceCommand<ManagerOrderView>('/api/manager/fulfillment',{orderId:order.id,status:status.input.value,trackingNumber:tracking.input.value.trim(),reason:reason.input.value.trim()});hooks.notify('Этап отправления обновлён.');await hooks.refresh();},hooks.error);});delivery.append(form);}
  const controls=node('details','','owner-test-tools');controls.dataset.deliveryOverrideTools='';controls.append(node('summary','Ручная корректировка и возврат к перевозчику'));const override=node('form','','commerce-form');override.dataset.deliveryOverrideForm='';const status=selectField('Ручной статус доставки','status',['quoted','packing','shipped','delivered'].map(value=>[value,deliveryLabels[value]!]),order.deliveryStatus);const tracking=textField('Трек-номер при корректировке','trackingNumber',order.trackingNumber??'');tracking.input.maxLength=120;tracking.input.minLength=3;tracking.input.required=['shipped','delivered'].includes(status.input.value);status.input.addEventListener('change',()=>{tracking.input.required=['shipped','delivered'].includes(status.input.value);});const reason=reasonField('Причина ручной корректировки');const set=button('Установить ручной статус','button',true);override.append(status.wrapper,tracking.wrapper,reason.wrapper,set);
  override.addEventListener('submit',event=>{event.preventDefault();void run(card,async()=>{await commerceCommand<ManagerOrderView>('/api/manager/delivery-override',{orderId:order.id,status:status.input.value,trackingNumber:tracking.input.value.trim(),reason:reason.input.value.trim()});hooks.notify('Ручной статус сохранён.');await hooks.refresh();},hooks.error);});
  if(order.deliveryOverride){const last=[...(order.deliveryEvents??[])].filter(item=>item.source==='carrier').sort((a,b)=>new Date(b.occurredAt).getTime()-new Date(a.occurredAt).getTime())[0];override.append(node('p',last?`Последнее событие перевозчика: ${deliveryLabels[last.status]??last.status}, ${date(last.occurredAt)}. После снятия ручного управления сервер применит допустимый статус.`:'Событий перевозчика пока нет. После снятия ручного управления новые события смогут менять статус.','field-help'));const clear=button('Снять ручное управление');clear.dataset.clearDeliveryOverride='';clear.addEventListener('click',()=>{if(!override.reportValidity())return;void run(card,async()=>{await commerceCommand<ManagerOrderView>('/api/manager/delivery-override',{orderId:order.id,status:null,reason:reason.input.value.trim()});hooks.notify('Автоматическое обновление доставки включено.');await hooks.refresh();},hooks.error);});override.append(clear);}controls.append(override);delivery.append(controls);
  const adapter=node('details','','owner-test-tools');adapter.dataset.carrierTestTools='';adapter.append(node('summary','Тестовый перевозчик'),node('p','Локальная имитация события доставки. Реального запроса перевозчику не будет.','field-help'));const carrier=node('form','','commerce-form');carrier.dataset.carrierTestForm='';const carrierStatus=selectField('Статус от перевозчика','status',['packing','shipped','delivered'].map(value=>[value,deliveryLabels[value]!]));const occurred=textField('Время события','occurredAt',localDateTime());(occurred.input as HTMLInputElement).type='datetime-local';(occurred.input as HTMLInputElement).step='1';occurred.input.required=true;const eventId=textField('Идентификатор тестового события','providerEventId',`test-${crypto.randomUUID()}`);eventId.input.required=true;eventId.input.maxLength=100;const carrierTracking=textField('Трек-номер от перевозчика','trackingNumber',order.trackingNumber??'');carrierTracking.input.maxLength=120;carrierTracking.input.minLength=3;carrierStatus.input.addEventListener('change',()=>{carrierTracking.input.required=['shipped','delivered'].includes(carrierStatus.input.value);});carrier.append(carrierStatus.wrapper,carrierTracking.wrapper,occurred.wrapper,eventId.wrapper,button('Получить тестовое событие','button-secondary',true));carrier.addEventListener('submit',event=>{event.preventDefault();const at=new Date(occurred.input.value);if(!Number.isFinite(at.getTime())){hooks.error(new Error('Укажите корректные дату и время события.'));return;}void run(card,async()=>{await commerceCommand<ManagerOrderView>('/api/manager/carrier-test',{orderId:order.id,status:carrierStatus.input.value,occurredAt:at.toISOString(),providerEventId:eventId.input.value.trim(),...(carrierTracking.input.value.trim()?{trackingNumber:carrierTracking.input.value.trim()}:{})});hooks.notify('Тестовое событие записано. Проверьте его применение в истории.');await hooks.refresh();},hooks.error);});adapter.append(carrier);delivery.append(adapter);
 }else delivery.append(node('p','Сборка и отправка доступны после успешной оплаты заказа.','field-help'));
 const events=node('details','','order-history');events.dataset.deliveryHistory='';events.append(node('summary','История доставки'));const history=node('ol','','owner-events');for(const item of order.deliveryEvents??[]){const row=node('li');row.append(node('strong',`${deliveryLabels[item.status]??item.status} · ${sourceLabels[item.source]??item.source}`),node('time',date(item.occurredAt)),node('p',item.reason,'field-help'),node('div',item.applied?'Применено к заказу':'Записано без изменения статуса',`owner-event-result${item.applied?' applied':''}`));history.append(row);}if(!history.children.length)events.append(node('p','Изменений доставки пока нет.','field-help'));else events.append(history);delivery.append(events);content.append(delivery);
 if(order.canCancel){const block=node('details','','owner-test-tools');block.dataset.ownerCancelTools='';block.append(node('summary','Отмена неоплаченного заказа'));const form=node('form','','commerce-form');form.dataset.ownerCancelForm='';const reason=reasonField('Причина отмены');form.append(node('p','Заказ будет отменён. Резерв или предварительное списание вернутся на склад один раз.','field-help'),reason.wrapper,button('Отменить заказ от имени владельца','button-secondary',true));form.addEventListener('submit',event=>{event.preventDefault();void run(card,async()=>{await commerceCommand<ManagerOrderView>('/api/manager/order-cancel',{orderId:order.id,reason:reason.input.value.trim()});hooks.notify('Заказ отменён.');await hooks.refresh();},hooks.error);});block.append(form);content.append(block);}else if(order.status==='paid')content.append(node('p','Оплаченный заказ нельзя отменить этой командой. Возврат оплаты требует отдельного процесса.','field-help'));
 details.append(content);card.append(details);
}

export function bindOwnerExtras(hooks:OwnerHooks){
 let items:StockItem[]=[];const adjust=$<HTMLFormElement>('#manager-stock-adjust-form')!,select=$<HTMLSelectElement>('[data-adjust-stock-select]')!,amount=adjust.elements.namedItem('onHand') as HTMLInputElement;
 function showStock(){const item=items.find(value=>value.skuId===select.value);amount.value=item?String(item.onHand):'';amount.min=String(item?.reserved??0);$<HTMLElement>('[data-adjust-stock-summary]')!.textContent=item?`Физический остаток: ${item.onHand}. Резерв: ${item.reserved}. Свободно: ${item.available}. Новый остаток не может быть ниже ${item.reserved}.`:'Выберите исполнение, чтобы увидеть остаток и резерв.';}
 select.addEventListener('change',showStock);
 adjust.addEventListener('submit',event=>{event.preventDefault();const onHand=Number(amount.value),item=items.find(value=>value.skuId===select.value),reason=(adjust.elements.namedItem('reason') as HTMLInputElement).value.trim();if(!item||!Number.isSafeInteger(onHand)||onHand<item.reserved){hooks.error(new Error('Остаток должен быть целым числом и не меньше текущего резерва.'));amount.focus();return;}void run(adjust,async()=>{await commerceCommand('/api/manager/stock-adjust',{skuId:select.value,onHand,reason});const result=$<HTMLElement>('[data-adjust-stock-result]')!;result.hidden=false;result.textContent=`Фактический остаток сохранён: ${onHand} шт.`;(adjust.elements.namedItem('reason') as HTMLInputElement).value='';hooks.notify('Корректировка склада проведена.');await hooks.refresh();},hooks.error);});
 const notificationButton=$<HTMLButtonElement>('[data-load-notifications]')!;
 async function notifications(){const result=await commerceGet<{notifications:OwnerNotification[]}>('/api/manager/notifications');const list=$<HTMLElement>('[data-owner-notifications]')!;list.replaceChildren();if(!result.notifications.length){list.append(node('p','Уведомлений пока нет.','field-help'));return;}for(const item of result.notifications){const card=node('article','','owner-notification');card.dataset.notificationId=item.id;const labels={pending:'Ожидает локальной доставки',delivered:'Доставлено локальным имитатором',failed:'Ошибка локальной доставки'};card.append(node('h3',item.subject),node('p',`${item.channel==='max'?'MAX':'Email'} · ${labels[item.status]}`,'owner-source'),node('p',item.body),node('time',date(item.createdAt)),node('p',`Попыток: ${item.attempts}`,'field-help'));if(item.lastError)card.append(note(item.lastError,true));if(item.status==='failed'){const retry=button('Повторить доставку');retry.dataset.retryNotification=item.id;retry.addEventListener('click',()=>void run(retry,async()=>{await commerceCommand('/api/manager/notification-retry',{notificationId:item.id});hooks.notify('Повторная попытка поставлена в локальную очередь.');await notifications();},hooks.error));card.append(retry);}list.append(card);}notificationButton.textContent='Обновить уведомления';}
 notificationButton.addEventListener('click',()=>void run(notificationButton,notifications,hooks.error));
 return{stock(next:StockItem[]){items=next;const selected=select.value;select.replaceChildren(new Option('Выберите исполнение',''));for(const item of items)select.append(new Option(`${item.article} · ${item.name}`,item.skuId));select.value=selected;showStock();}};
}

async function withOwnerLogin(load:()=>Promise<void>){
 const form=$<HTMLFormElement>('#owner-login-form')!,login=$<HTMLElement>('[data-owner-login]')!,content=$<HTMLElement>('[data-owner-content]')!;
 async function guarded(){try{await load();login.hidden=true;content.hidden=false;}catch(error){if(error instanceof CommerceError&&(error.status===401||error.status===403)){content.hidden=true;login.hidden=false;if(error.status===403)pageError(new Error('Эти инструменты доступны только администратору новой CMS.'));return;}throw error;}}
 form.addEventListener('submit',event=>{event.preventDefault();const email=(form.elements.namedItem('email') as HTMLInputElement).value.trim(),password=(form.elements.namedItem('password') as HTMLInputElement).value;void run(form,async()=>{await commerceCommand('/api/manager/login',{email,password});(form.elements.namedItem('password') as HTMLInputElement).value='';await guarded();});});
 try{await guarded();}catch(error){pageError(error);}finally{$<HTMLElement>('[data-owner-loading]')!.hidden=true;}
 return guarded;
}

async function initGeneration(){
 const select=$<HTMLSelectElement>('[data-generation-product]')!,generateForm=$<HTMLFormElement>('#generation-form')!,applyForm=$<HTMLFormElement>('#apply-description-form')!,preview=$<HTMLElement>('[data-generation-preview]')!,generate=$<HTMLButtonElement>('[data-generate]')!;
 const description=applyForm.elements.namedItem('description') as HTMLTextAreaElement,meta=applyForm.elements.namedItem('metaDescription') as HTMLTextAreaElement;
 let products:GenerationProduct[]=[],currentId='',draft:DescriptionDraft|null=null,stale=false;
 const drafts=new Map<string,{draft:DescriptionDraft;description:string;meta:string;stale:boolean}>();
 function saveEdits(){if(currentId&&draft)drafts.set(currentId,{draft,description:description.value,meta:meta.value,stale});}
 function showProduct(){const product=products.find(item=>item.id===select.value);currentId=product?.id??'';$<HTMLElement>('[data-generation-current]')!.hidden=!product;generate.disabled=!product;if(product){$<HTMLElement>('[data-generation-name]')!.textContent=product.name;$<HTMLElement>('[data-generation-demo]')!.hidden=!product.isDemo;$<HTMLInputElement>('[data-generation-title]')!.value=product.seoTitle;$<HTMLTextAreaElement>('[data-current-description]')!.value=product.description;$<HTMLTextAreaElement>('[data-current-meta]')!.value=product.metaDescription;}const cached=drafts.get(currentId);draft=cached?.draft??null;stale=cached?.stale??false;preview.hidden=!cached;if(cached){description.value=cached.description;meta.value=cached.meta;}$<HTMLElement>('[data-generation-conflict]')!.hidden=!stale;$<HTMLButtonElement>('button[type=submit]',applyForm)!.disabled=stale;}
 async function load(){saveEdits();const selected=select.value||new URLSearchParams(location.search).get('product')||'';products=(await commerceGet<{products:GenerationProduct[]}>('/api/manager/products')).products;select.replaceChildren(new Option('Выберите товар',''));for(const product of products)select.append(new Option(product.name,product.id));select.value=products.some(product=>product.id===selected)?selected:'';showProduct();}
 select.addEventListener('change',()=>{saveEdits();clearError();showProduct();const url=new URL(location.href);if(currentId)url.searchParams.set('product',currentId);else url.searchParams.delete('product');history.replaceState(null,'',url);});
 const reload=$<HTMLButtonElement>('[data-generation-refresh]')!;reload.addEventListener('click',()=>void run(reload,load));
 generateForm.addEventListener('submit',event=>{event.preventDefault();if(!currentId)return;saveEdits();const productId=currentId,simulateFailure=(generateForm.elements.namedItem('simulateFailure') as HTMLInputElement).checked;void run(generateForm,async()=>{const result=await commerceCommand<DescriptionDraft>('/api/manager/generate',{productId,simulateFailure});drafts.set(productId,{draft:result,description:result.description,meta:result.metaDescription,stale:false});showProduct();$<HTMLElement>('#generation-preview-title')!.focus();});});
 applyForm.addEventListener('submit',event=>{event.preventDefault();if(!draft||stale)return;const body={draftId:draft.id,description:description.value.trim(),metaDescription:meta.value.trim()};void run(applyForm,async()=>{try{const result=await commerceCommand<{ok:true;product:GenerationProduct}>('/api/manager/apply-description',body);const index=products.findIndex(product=>product.id===result.product.id);if(index>=0)products[index]=result.product;drafts.delete(currentId);draft=null;showProduct();success('Описание и meta description сохранены. SEO-заголовок остался прежним.');}catch(error){if(error instanceof CommerceError&&error.status===409){stale=true;saveEdits();$<HTMLElement>('[data-generation-conflict]')!.hidden=false;setTimeout(()=>$<HTMLButtonElement>('button[type=submit]',applyForm)!.disabled=true,0);}throw error;}});});
 $<HTMLButtonElement>('[data-discard-draft]')!.addEventListener('click',()=>{drafts.delete(currentId);draft=null;preview.hidden=true;generate.focus();});
 await withOwnerLogin(load);
}

async function initModeration(){
 let reviews:ReviewView[]=[];const filter=$<HTMLSelectElement>('[data-review-filter]')!,list=$<HTMLElement>('[data-moderation-list]')!,labels={pending:'Ожидает проверки',approved:'Опубликован',rejected:'Отклонён'};
 function render(){const shown=reviews.filter(review=>filter.value==='all'||review.status===filter.value);$<HTMLElement>('[data-review-count]')!.textContent=`Показано: ${shown.length}. Ожидают проверки: ${reviews.filter(review=>review.status==='pending').length}.`;list.replaceChildren();if(!shown.length){list.append(blank('Отзывов в этом списке нет','Выберите другой статус или обновите список.'));return;}for(const review of shown){const card=node('article','',`owner-review ${review.status}`);card.dataset.reviewId=review.id;const heading=node('div','','owner-review-head');heading.append(node('h2',review.productName),node('span',labels[review.status],'status-pill'));card.append(heading,node('p',`${review.authorName} · ${date(review.createdAt)}`,'owner-review-meta'),node('p',review.body,'owner-review-body'));if(review.media.length){const images=node('div','','owner-review-media');review.media.forEach((media,index)=>{if(!media.url.startsWith('/review-media/'))return;const link=node('a');link.href=media.url;link.target='_blank';link.rel='noopener';link.setAttribute('aria-label',`Открыть фото ${index+1} к отзыву`);const image=node('img');image.src=media.url;image.alt=`Фото ${index+1} к отзыву покупателя`;image.width=media.width;image.height=media.height;image.loading='lazy';link.append(image);images.append(link);});card.append(images);}if(review.moderationNote)card.append(note(`Комментарий модерации: ${review.moderationNote}`));const form=node('form','','commerce-form');const reason=textField('Комментарий к решению','note','',true);reason.input.maxLength=1000;const actions=node('div','','owner-actions');const approve=button('Опубликовать отзыв','button',true),reject=button('Отклонить отзыв','button-secondary',true);approve.dataset.reviewDecision='approved';reject.dataset.reviewDecision='rejected';approve.disabled=review.status==='approved';reject.disabled=review.status==='rejected';actions.append(approve,reject);form.append(reason.wrapper,node('p','Для отклонения укажите понятную причину. Текст отзыва не изменяется.','field-help'),actions);form.addEventListener('submit',event=>{event.preventDefault();const decision=(event as SubmitEvent).submitter instanceof HTMLElement?((event as SubmitEvent).submitter as HTMLElement).dataset.reviewDecision:undefined;if(decision!=='approved'&&decision!=='rejected')return;const message=reason.input.value.trim();if(decision==='rejected'&&message.length<2){pageError(new Error('Укажите причину отклонения отзыва.'));reason.input.focus();return;}void run(card,async()=>{const result=await commerceCommand<ReviewView>('/api/social/moderation',{reviewId:review.id,status:decision,note:message});reviews=reviews.map(item=>item.id===result.id?result:item);render();success(decision==='approved'?'Отзыв и его фотографии опубликованы.':'Отзыв отклонён и скрыт из магазина.');});});card.append(form);list.append(card);}}
 async function load(){reviews=(await commerceGet<{reviews:ReviewView[]}>('/api/social/moderation')).reviews;render();}
 filter.addEventListener('change',render);const reload=$<HTMLButtonElement>('[data-reload-reviews]')!;reload.addEventListener('click',()=>void run(reload,load));await withOwnerLogin(load);
}
const page=document.querySelector<HTMLElement>('[data-owner-page]');if(page){const initialize=page.dataset.ownerPage==='content'?initGeneration:initModeration;void initialize().catch(error=>{pageError(error);const loading=$<HTMLElement>('[data-owner-loading]');if(loading)loading.hidden=true;});}
