import {commerceGet,commerceCommand} from './commerce';
import {node} from './manager-page';
export function productTrash(root:HTMLElement,hooks:{done:(count:number)=>Promise<void>;error:(e:unknown)=>void}){
 const dialog=node('dialog','','product-lifecycle-dialog'),title=node('h2','Очистить раздел «Удалённые»?'),copy=node('p'),error=node('p','','dash-message dash-error'),actions=node('div','','mgr-row-actions'),cancel=node('button','Отмена','dash-button'),submit=node('button','Удалить все окончательно','dash-button dash-danger');
 title.id='product-trash-title';dialog.setAttribute('aria-labelledby',title.id);cancel.type=submit.type='button';cancel.autofocus=true;error.setAttribute('role','alert');actions.append(cancel,submit);dialog.append(title,copy,error,actions);root.append(dialog);
 let serial=0,busy=false,token='',key='';
 const close=()=>{if(busy)return;serial++;dialog.close();token='';};cancel.addEventListener('click',close);dialog.addEventListener('cancel',e=>{e.preventDefault();close();});
 root.addEventListener('autoreelz:manager-locked',()=>{serial++;token='';copy.textContent='';dialog.close();});
 submit.addEventListener('click',async()=>{if(busy||!token)return;busy=true;submit.disabled=cancel.disabled=true;error.hidden=true;try{const result=await commerceCommand<{count:number}>('/api/manager/product-lifecycle',{action:'purge-all',token,idempotencyKey:key});dialog.close();await hooks.done(result.count);}catch(e){error.textContent=e instanceof Error?e.message:'Не удалось удалить товары.';error.hidden=false;hooks.error(e);}finally{busy=false;submit.disabled=cancel.disabled=false;}});
 return{async open(){if(busy)return;const turn=++serial;token='';key=crypto.randomUUID();submit.disabled=true;cancel.disabled=false;error.hidden=true;copy.textContent='Проверяем полный список…';dialog.showModal();try{const snapshot=await commerceGet<{count:number;token:string}>('/api/manager/product-lifecycle?trash=1');if(turn!==serial||!dialog.open)return;token=snapshot.token;copy.textContent=`Будут окончательно удалены все товары из раздела «Удалённые»: ${snapshot.count}. Поиск, категории и другие фильтры не ограничивают очистку. Восстановление через менеджер будет недоступно. Заказы, SKU, складской учёт и общие фотографии сохранятся.`;submit.disabled=snapshot.count===0;}catch(e){if(turn!==serial)return;error.textContent=e instanceof Error?e.message:'Не удалось проверить список.';error.hidden=false;hooks.error(e);}}};
}
