import {managerPage,managerDirty,node,link} from './manager-page';
import {CommerceError,getSession} from './commerce';
import {emptyVariant,productSlug,publicationIssues,hasPackage,packageValues,type EditorData,type EditorState,type EditorOptions,type EditorPhoto,type EditorAttribute,type EditorFitment,type EditorIssue} from '../lib/product-editor';
import {parseRublesInput,formatRubles,compareRubles} from '../lib/money';

const root=document.querySelector<HTMLElement>('[data-workspace="product-editor"]');
if(root){
 const $=<T extends HTMLElement=HTMLElement>(s:string)=>root.querySelector<T>(s)!;
 const form=$<HTMLFormElement>('[data-editor-form]'),fields=$<HTMLFieldSetElement>('[data-editor-fields]');
 const id=new URLSearchParams(location.search).get('id')??crypto.randomUUID();history.replaceState(null,'','?id='+encodeURIComponent(id));
 let state:EditorState,options:EditorOptions,data:EditorData,slugManual=false,busy=false,uploading=0,generation=0,pending:{fingerprint:string;key:string}|null=null,showValidation=false;
 const imageUrl=(id:string)=>'/api/manager/product-image?id='+encodeURIComponent(id);
 const pathId=(path:string)=>'pe-'+path.replaceAll('.','-');
 function button(label:string,fn:()=>void,css='dash-button'){const b=node('button',label,css);b.type='button';b.addEventListener('click',fn);return b;}
 function changed(){managerDirty(true);$('[data-editor-save-hint]').textContent='Есть несохранённые изменения';updatePreview();if(showValidation)markIssues(publicationIssues(data,state.existingSkuIds),false);}
 function field(label:string,path:string,value:string,set:(value:string)=>void,config:{type?:string;help?:string;choices?:[string,string][];wide?:boolean;max?:number}={}){
  const wrap=node('label','','dash-field pe-field'+(config.wide?' pe-wide':''));wrap.append(node('span',label));let input:HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement;
  if(config.choices){const select=node('select');for(const[value,text]of config.choices){const option=node('option',text);option.value=value;select.append(option);}input=select;}
  else if(config.type==='textarea'){input=node('textarea');input.rows=5;input.maxLength=config.max??12000;}
  else{input=node('input');input.type='text';input.maxLength=config.max??250;if(config.type==='decimal')input.inputMode='decimal';if(config.type==='integer')input.inputMode='numeric';}
  input.id=pathId(path);input.dataset.fieldPath=path;input.value=value;
  input.addEventListener(input instanceof HTMLSelectElement?'change':'input',()=>{set(input.value);changed();});
  input.addEventListener('blur',()=>{const issues=publicationIssues(data,state.existingSkuIds).filter(i=>i.path===path);markField(path,issues[0]?.message??'');});wrap.append(input);
  const err=node('small','','pe-field-error');err.id=pathId(path)+'-error';err.dataset.errorPath=path;wrap.append(err);input.setAttribute('aria-describedby',err.id);
  if(config.help){const help=node('small',config.help,'dash-help');help.id=pathId(path)+'-help';input.setAttribute('aria-describedby',help.id+' '+err.id);wrap.append(help);}return wrap;
 }
 function markField(path:string,message:string){const target=root!.querySelector<HTMLElement>(`[data-field-path="${path}"]`);target?.setAttribute('aria-invalid',String(!!message));const error=root!.querySelector<HTMLElement>(`[data-error-path="${path}"]`);if(error)error.textContent=message;}
 function markIssues(issues:EditorIssue[],focus:boolean){root!.querySelectorAll('[data-error-path]').forEach(n=>n.textContent='');root!.querySelectorAll('[aria-invalid]').forEach(n=>n.removeAttribute('aria-invalid'));issues.forEach(i=>markField(i.path,i.message));if(!focus)return;const box=$('[data-editor-errors]');box.replaceChildren(node('strong','Проверьте данные перед публикацией'));const list=node('ul','','pe-errors-list');for(const issue of issues){const li=node('li'),a=link(issue.message,'#'+pathId(issue.path));a.addEventListener('click',e=>{e.preventDefault();const target=document.getElementById(pathId(issue.path));if(target){let p=target.parentElement;while(p){if(p instanceof HTMLDetailsElement)p.open=true;p=p.parentElement;}target.scrollIntoView({block:'center'});target.focus();}});li.append(a);list.append(li);}box.append(list);box.hidden=false;box.focus();}
 function categoryLabel(id:string){const row=options.categories.find(c=>c.id===id);if(!row)return'';const names=[row.name];let parent=row.parentId;const seen=new Set([row.id]);while(parent&&!seen.has(parent)){seen.add(parent);const p=options.categories.find(c=>c.id===parent);if(!p)break;names.unshift(p.name);parent=p.parentId;}return names.join(' / ');}
 function categoryIds(){const ids=new Set<string>();let id=data.categoryId;while(id&&!ids.has(id)){ids.add(id);id=options.categories.find(c=>c.id===id)?.parentId??'';}return ids;}
 function updatePreview(){
  if(!data)return;const first=data.photos[0],img=$<HTMLImageElement>('[data-preview-image]');img.hidden=!first;$('[data-preview-placeholder]').hidden=!!first;if(first){if(img.getAttribute('src')!==imageUrl(first.id))img.src=imageUrl(first.id);img.alt=first.alt;}
  $('[data-preview-name]').textContent=data.name||'Название товара';$('[data-preview-category]').textContent=categoryLabel(data.categoryId);
  const prices=data.variants.filter(v=>v.status==='published').flatMap(v=>{try{return[parseRublesInput(v.price)];}catch{return[];}}).sort(compareRubles);
  $('[data-preview-price]').textContent=prices.length?(prices.length>1?'от ':'')+formatRubles(prices[0]!):'Укажите цену';
  $('[data-preview-count]').textContent=`Исполнений: ${data.variants.length}`;
  const checklist=$('[data-preview-checklist]');checklist.replaceChildren();
  const issues=publicationIssues(data,state.existingSkuIds);
  const checks:[string,boolean][]=[['Название и категория',!!data.name&&!!data.categoryId],['Общие фотографии',!!data.photos.length],['Артикулы и цены',data.variants.length>0&&!issues.some(i=>/article|price|variants$/.test(i.path))],['Упаковка для доставки',data.variants.length>0&&data.variants.every(v=>{try{return hasPackage(v.package)&&!!packageValues(v.package);}catch{return false;}})],['Описание товара',!!data.description],['Данные для публикации',issues.length===0]];
  for(const[label,complete]of checks){const li=node('li',label);li.dataset.complete=String(complete);checklist.append(li);}
 }
 function gallery(container:HTMLElement,items:EditorPhoto[],path:string){
  container.replaceChildren();container.id=pathId(path);container.tabIndex=-1;
  const label=node('label','','pe-upload');label.append(node('strong','Добавить фотографии'),node('p','JPG, PNG или WebP, до 10 МБ и 24 мегапикселей. Не более 12 фото в галерее.','dash-help'));
  const upload=node('input');upload.type='file';upload.multiple=true;upload.accept='image/jpeg,image/png,image/webp';upload.setAttribute('aria-label','Выбрать фотографии');upload.hidden=true;label.append(upload,button('Выбрать фотографии',()=>upload.click()));
  const status=node('p','','dash-help pe-upload-status');status.setAttribute('role','status');const grid=node('div','','pe-gallery');const err=node('small','','pe-field-error');err.dataset.errorPath=path;
  container.append(label,status,err,grid);
  let drag=-1;
  function reorder(from:number,to:number){if(to<0||to>=items.length)return;const [photo]=items.splice(from,1);items.splice(to,0,photo!);changed();draw();(grid.children[to]?.querySelector('button:not([disabled])') as HTMLButtonElement|null)?.focus();}
  function draw(){grid.replaceChildren();items.forEach((photo,i)=>{const card=node('article','','pe-photo');card.draggable=true;card.addEventListener('dragstart',e=>{if(busy||uploading){e.preventDefault();return;}drag=i;});card.addEventListener('dragover',e=>e.preventDefault());card.addEventListener('drop',e=>{e.preventDefault();if(!busy&&!uploading&&drag>=0)reorder(drag,i);drag=-1;});const badge=node('span',i===0?'Главное фото':`Фото ${i+1}`,'pe-photo-badge'),img=node('img');img.src=imageUrl(photo.id);img.alt=photo.alt;img.loading='lazy';card.append(badge,img,field('Подпись',`${path}.${i}.alt`,photo.alt,v=>photo.alt=v,{max:500}));const controls=node('div','','pe-photo-tools'),left=button('←',()=>reorder(i,i-1)),right=button('→',()=>reorder(i,i+1)),remove=button('Убрать',()=>{items.splice(i,1);changed();draw();});left.disabled=i===0;right.disabled=i===items.length-1;left.setAttribute('aria-label',`Фото ${i+1}: переместить раньше`);right.setAttribute('aria-label',`Фото ${i+1}: переместить позже`);controls.append(left,right,remove);card.append(controls);grid.append(card);});}
  upload.addEventListener('change',()=>{const selected=Array.from(upload.files??[]);upload.value='';if(items.length+selected.length>12){status.textContent='В галерее может быть не больше 12 фотографий.';return;}const tasks=selected.map(file=>({file,key:crypto.randomUUID()}));void send(tasks);});
  async function send(tasks:{file:File;key:string}[]){const serial=generation;uploading++;setBusy();managerDirty(true);let completed=0;
   try{for(const task of tasks){status.textContent=`Загружаем фото ${completed+1} из ${tasks.length}…`;const session=await getSession(),body=new FormData();body.append('id',id);body.append('key',task.key);body.append('file',task.file);const response=await fetch('/api/manager/product-image',{method:'POST',body,headers:{'X-CSRF-Token':session.csrfToken},signal:AbortSignal.timeout(45000)}),payload=await response.json();if(!response.ok)throw new CommerceError(payload.error?.message??'Не удалось загрузить фотографию.',response.status,payload.error?.code);if(serial!==generation)return;items.push(payload);completed++;draw();changed();}status.textContent='Фотографии загружены. Сохраните черновик или опубликуйте товар.';}
   catch(e){if(serial!==generation)return;status.replaceChildren(node('span',e instanceof Error?e.message:'Не удалось загрузить фото.'));status.append(button('Повторить загрузку',()=>void send(tasks.slice(completed))));if(e instanceof CommerceError&&(e.status===401||e.status===403))page.showError(e);}
   finally{uploading--;setBusy();}
  }
  draw();
 }
 function attributeFields(container:HTMLElement,rows:EditorAttribute[],prefix:string){
  container.replaceChildren(node('h3','Характеристики'));const list=node('div','','pe-stack');container.append(list);
  rows.forEach((row,i)=>{const def=options.attributes.find(a=>a.id===row.attributeId),block=node('div','','pe-row'),grid=node('div','','pe-grid');
   grid.append(field('Характеристика',`${prefix}.${i}.attributeId`,row.attributeId,v=>{row.attributeId=v;row.value='';attributeFields(container,rows,prefix);},{choices:[['','Выберите характеристику'],...options.attributes.map(a=>[a.id,a.name] as[string,string])]}));
   grid.append(field(def?.unit?`Значение, ${def.unit}`:'Значение',`${prefix}.${i}.value`,row.value,v=>row.value=v,def?.type==='select'?{choices:[['','Выберите значение'],...def.values.map(v=>[v.id,v.label] as[string,string])]}:def?.type==='boolean'?{choices:[['','Не указано'],['true','Да'],['false','Нет']]}:{type:def?.type==='number'?'decimal':'text',max:2000}));block.append(grid,button('Убрать характеристику',()=>{rows.splice(i,1);attributeFields(container,rows,prefix);changed();}));list.append(block);
  });
  const ids=categoryIds(),suggested=options.attributes.filter(a=>a.categoryIds.some(id=>ids.has(id))&&!rows.some(r=>r.attributeId===a.id));
  const actions=node('div','','pe-inline-actions');for(const def of suggested)actions.append(button('+ '+def.name,()=>{rows.push({attributeId:def.id,value:''});attributeFields(container,rows,prefix);changed();}));
  actions.append(button('+ Другая характеристика',()=>{rows.push({attributeId:'',value:''});attributeFields(container,rows,prefix);changed();}));container.append(actions);
 }
 function fitmentFields(container:HTMLElement,rows:EditorFitment[],prefix:string){
  container.replaceChildren(node('h3','Совместимость с автомобилями'));container.append(node('p','Нет подтверждения — оставьте статус «Не подтверждено». Неизвестные годы можно не заполнять.','dash-help'));
  rows.forEach((row,i)=>{const block=node('div','','pe-row'),grid=node('div','','pe-grid'),path=`${prefix}.${i}`;
   grid.append(field('Автомобиль',path+'.vehicleId',row.vehicleId,v=>{row.vehicleId=v;row.versionId='';fitmentFields(container,rows,prefix);},{choices:[['','Выберите автомобиль'],...options.vehicles.map(v=>[v.id,v.name] as[string,string])]}),field('Модификация',path+'.versionId',row.versionId,v=>row.versionId=v,{choices:[['','Не уточнена'],...(options.vehicles.find(v=>v.id===row.vehicleId)?.versions??[]).map(v=>[v.id,v.name] as[string,string])]}),field('Статус совместимости',path+'.state',row.state,v=>row.state=v,{choices:[['unknown','Не подтверждено'],['compatible','Подходит'],['incompatible','Не подходит']]}),field('Кондиционер',path+'.ac',row.ac,v=>row.ac=v,{choices:[['unknown','Неизвестно'],['yes','Есть'],['no','Нет'],['any','Не влияет']]}),field('Год от',path+'.yearFrom',row.yearFrom,v=>row.yearFrom=v,{type:'integer',max:4}),field('Год до',path+'.yearTo',row.yearTo,v=>row.yearTo=v,{type:'integer',max:4}),field('Примечание',path+'.note',row.note,v=>row.note=v,{wide:true,max:2000}));block.append(grid,button('Убрать правило',()=>{rows.splice(i,1);fitmentFields(container,rows,prefix);changed();}));container.append(block);
  });container.append(button('+ Добавить автомобиль',()=>{rows.push({vehicleId:'',versionId:'',yearFrom:'',yearTo:'',ac:'unknown',state:'unknown',note:''});fitmentFields(container,rows,prefix);changed();},'dash-button pe-add'));
 }
 function renderVariants(){const container=$('[data-editor-variants]');container.id=pathId('variants');container.tabIndex=-1;container.replaceChildren();
  data.variants.forEach((v,i)=>{const path=`variants.${i}`,card=node('section','','pe-variant'),heading=node('div','','pe-variant-head');heading.append(node('h3',`Вариант ${i+1}`));const exists=state.existingSkuIds.includes(v.id);if(!exists&&data.variants.length>1)heading.append(button('Удалить',()=>{data.variants.splice(i,1);renderVariants();changed();}));card.append(heading);
   const grid=node('div','','pe-grid');grid.append(field('Название варианта',path+'.name',v.name,value=>v.name=value,{help:'Например, «Зелёная подсветка» или «Стандартное исполнение».'}),field('Артикул',path+'.article',v.article,value=>v.article=value,{help:'Ваш существующий артикул. Автоматически не перенумеровывается.',max:160}),field('Цена, ₽',path+'.price',v.price,value=>v.price=value,{type:'decimal',help:'1800 или 1800,50 — в рублях.',max:40}),field('Показывать на сайте',path+'.status',v.status,value=>v.status=value as typeof v.status,{choices:[['published','Да, после публикации товара'],['draft','Пока черновик'],['archived','Архив']]}));
   if(exists){const s=state.stock[v.id],info=node('div','','pe-field');info.append(node('strong','Остаток на складе'),node('p',s?`На складе: ${s.onHand} · резерв: ${s.reserved} · свободно: ${s.onHand-s.reserved}`:'Поступлений пока нет','dash-help'),link('Изменить остаток','/manager/stock?sku='+v.id,'dash-button'));grid.append(info);}else grid.append(field('Начальный остаток, шт.',path+'.initialStock',v.initialStock,value=>v.initialStock=value,{type:'integer',help:'Приход будет проведён один раз при публикации. 0 означает предзаказ.',max:10}),field('Причина прихода',path+'.stockReason',v.stockReason,value=>v.stockReason=value,{help:'Нужна, если начальный остаток больше нуля.',max:500}));card.append(grid);
   const pack=node('details');pack.open=data.variants.length===1;pack.append(node('summary','Упаковка для доставки'));const pg=node('div','','pe-package');pg.id=pathId(path+'.package');pg.tabIndex=-1;pg.append(node('p','Укажите вес вместе с упаковкой и внешние размеры готовой посылки.','dash-help'));for(const[key,label]of [['weightG','Вес, г'],['lengthCm','Длина, см'],['widthCm','Ширина, см'],['heightCm','Высота, см']] as const)pg.append(field(label,path+'.package.'+key,v.package[key],value=>v.package[key]=value,{type:key==='weightG'?'integer':'decimal',max:15}));const err=node('small','','pe-field-error');err.dataset.errorPath=path+'.package';pg.append(err);pack.append(pg);if(data.variants.length>1)pack.append(button('Применить эту упаковку ко всем вариантам',()=>{for(const other of data.variants)other.package={...v.package};renderVariants();changed();}));card.append(pack);
   const extra=node('details');extra.append(node('summary','Фотографии и характеристики этого варианта'));const extraBody=node('div','','pe-stack'),photos=node('div'),attrs=node('div'),fits=node('div');
   extraBody.append(field('Фотографии варианта',path+'.mediaMode',v.mediaMode,value=>{v.mediaMode=value as typeof v.mediaMode;photos.hidden=value==='inherit';},{choices:[['inherit','Общие фотографии товара'],['replace','Свои фотографии варианта']]}),photos);gallery(photos,v.photos,path+'.photos');photos.hidden=v.mediaMode==='inherit';attributeFields(attrs,v.attributes,path+'.attributes');extraBody.append(attrs,field('Совместимость варианта',path+'.fitmentMode',v.fitmentMode,value=>{v.fitmentMode=value as typeof v.fitmentMode;fits.hidden=value==='inherit';},{choices:[['inherit','Общие правила товара'],['replace','Свои правила варианта']]}),fits);fitmentFields(fits,v.fitment,path+'.fitment');fits.hidden=v.fitmentMode==='inherit';extra.append(extraBody);card.append(extra);container.append(card);
  });
 }
 function render(){generation++;data=structuredClone(state.data);slugManual=!!data.slug;showValidation=false;$('[data-editor-errors]').hidden=true;$('[data-discard-draft]').hidden=!state.hasDraft;
  $('[data-editor-title]').textContent=state.live?'Редактировать товар':'Добавить товар';
  $('[data-editor-status]').textContent=state.hasDraft?(state.live?'Открыт сохранённый черновик. На сайте пока остаётся прежняя версия товара.':'Открыт сохранённый черновик. Товар ещё не опубликован.'):(state.live?'Изменения появятся на сайте только после публикации. Склад существующих вариантов здесь не пересчитывается.':'Заполните данные в одной форме. Черновик можно сохранить даже до заполнения всех полей.');
  const main=$('[data-editor-main]');main.replaceChildren(field('Название товара','name',data.name,value=>{data.name=value;if(!slugManual){data.slug=productSlug(value);const input=document.getElementById(pathId('slug')) as HTMLInputElement|null;if(input)input.value=data.slug;}},{wide:true}),field('Категория','categoryId',data.categoryId,value=>{data.categoryId=value;attributeFields($('[data-editor-attributes]'),data.attributes,'attributes');},{wide:true,choices:[['','Выберите категорию'],...options.categories.map(c=>[c.id,categoryLabel(c.id)+(c.status==='published'?'':' — '+(c.status==='draft'?'черновик':'архив'))] as[string,string])]}),field('Описание','description',data.description,value=>data.description=value,{wide:true,type:'textarea',help:'Что это за товар, что входит в поставку и что важно для установки.'}));
  gallery($('[data-editor-photos]'),data.photos,'photos');renderVariants();attributeFields($('[data-editor-attributes]'),data.attributes,'attributes');fitmentFields($('[data-editor-fitment]'),data.fitment,'fitment');
  const seo=$('[data-editor-seo]');seo.replaceChildren(field('Адрес страницы','slug',data.slug,value=>{slugManual=true;data.slug=value;},{help:'Предлагается из названия. Латиница, цифры, дефисы; уникальность проверим при публикации.',max:160}),field('SEO-заголовок','seoTitle',data.seoTitle,value=>data.seoTitle=value),field('Краткое описание для поиска','metaDescription',data.metaDescription,value=>data.metaDescription=value,{type:'textarea',max:2000}));const demo=node('label','','dash-checkbox'),toggle=node('input');toggle.type='checkbox';toggle.checked=data.isDemo;toggle.addEventListener('change',()=>{data.isDemo=toggle.checked;changed();});demo.append(toggle,node('span','Демонстрационный товар'));seo.append(demo);
  const preview=$<HTMLAnchorElement>('[data-preview-link]');preview.hidden=!state.live;preview.href='/product/'+(state.liveSlug??data.slug);
  $('[data-editor-save-hint]').textContent=state.hasDraft?'Черновик сохранён':state.live?'Данные загружены':'Изменения ещё не сохранены';managerDirty(false);updatePreview();setBusy();
 }
 function setBusy(){const locked=busy||uploading>0;fields.disabled=locked;form.setAttribute('aria-busy',String(locked));$<HTMLButtonElement>('[data-save-draft]').disabled=locked;$<HTMLButtonElement>('[data-publish-product]').disabled=locked;$<HTMLButtonElement>('[data-workspace-refresh]').disabled=locked;$<HTMLButtonElement>('[data-discard-draft]').disabled=locked;}
 async function save(action:'draft'|'publish'|'discard'){
  if(busy||uploading)return;$('[data-editor-errors]').hidden=true;if(action==='publish'){showValidation=true;const issues=publicationIssues(data,state.existingSkuIds);if(issues.length){markIssues(issues,true);return;}}
  const body={id,version:state.version,baseHash:state.baseHash,data,action},fingerprint=JSON.stringify(body);if(pending?.fingerprint!==fingerprint)pending={fingerprint,key:crypto.randomUUID()};busy=true;setBusy();$('[data-editor-save-hint]').textContent=action==='discard'?'Сбрасываем черновик…':action==='draft'?'Сохраняем черновик…':'Публикуем товар…';
  try{const session=await getSession(),response=await fetch('/api/manager/product-editor',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':session.csrfToken},body:JSON.stringify({...body,idempotencyKey:pending.key}),signal:AbortSignal.timeout(25000)}),payload=await response.json();if(!response.ok){if(payload.error?.issues)markIssues(payload.error.issues,true);throw new CommerceError(payload.error?.message??'Не удалось сохранить товар.',response.status,payload.error?.code);}pending=null;managerDirty(false);page.notify(action==='discard'?'Черновик сброшен. Загружена актуальная карточка.':action==='draft'?'Черновик сохранён. Можно вернуться к нему из списка товаров.':'Товар опубликован. Новые остатки учтены один раз.');await page.reload();}
  catch(e){page.showError(e instanceof CommerceError?e:new Error('Не удалось связаться с магазином. Проверьте соединение и повторите сохранение.'));$('[data-editor-save-hint]').textContent='Сохранение не подтверждено. Данные остаются в форме; повторите действие.';}
  finally{busy=false;setBusy();}
 }
 const page=managerPage(root,async signal=>{const [loaded,settings]=await Promise.all([page.get<EditorState>('/api/manager/product-editor?id='+encodeURIComponent(id),signal),page.get<EditorOptions>('/api/manager/product-editor?options=1',signal)]);return()=>{state=loaded;options=settings;render();};});
 $<HTMLButtonElement>('[data-add-variant]').addEventListener('click',()=>{if(data.variants.length>=20){page.showError(new Error('В одной форме можно добавить до 20 вариантов.'));return;}data.variants.push(emptyVariant(crypto.randomUUID()));renderVariants();changed();document.getElementById(pathId(`variants.${data.variants.length-1}.name`))?.focus();});
 $<HTMLButtonElement>('[data-save-draft]').addEventListener('click',()=>void save('draft'));form.addEventListener('submit',e=>{e.preventDefault();void save('publish');});
 $<HTMLButtonElement>('[data-discard-draft]').addEventListener('click',()=>{if(confirm('Удалить сохранённый черновик и несохранённые изменения? Опубликованный товар и склад останутся без изменений.'))void save('discard');});
 root.addEventListener('autoreelz:manager-locked',()=>{generation++;for(const selector of ['[data-editor-main]','[data-editor-photos]','[data-editor-variants]','[data-editor-attributes]','[data-editor-fitment]','[data-editor-seo]'])$(selector).replaceChildren();$('[data-editor-status]').textContent='';$<HTMLImageElement>('[data-preview-image]').removeAttribute('src');$('[data-preview-name]').textContent='';$('[data-preview-price]').textContent='';$('[data-editor-errors]').hidden=true;});
 void page.reload();
}
