import {test} from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {emptyProduct,emptyVariant} from '../src/lib/product-editor.ts';import {aiSource,aiSourceSignature} from '../src/lib/ai-text.ts';
import {TEXT_MAX_OUTPUT,TEXT_PRICES,checkTextFacts,parseAIText,reservationCost,usageCost,requestAIText} from '../src/server/adapters/ai-text.ts';
import {aiConfig,factsForAI,generateProductText} from '../src/server/product-ai.ts';
const category=randomUUID(),car=randomUUID(),attr=randomUUID(),value=randomUUID();
const options={categories:[{id:category,name:'Блоки отопителя',parentId:null,status:'published'}],attributes:[{id:attr,name:'Подсветка',type:'select',unit:null,categoryIds:[category],values:[{id:value,label:'Зелёная'}]}],vehicles:[{id:car,name:'Лада Гранта',versions:[]}]};
const data={...emptyProduct(),name:'Блок отопителя',categoryId:category,description:'PRIVATE CURRENT COPY',seoTitle:'MANUAL SEO TITLE',metaDescription:'PRIVATE META',variants:[{...emptyVariant(randomUUID()),name:'Зелёная',article:'QA-GREEN',price:'1800',initialStock:'10',stockReason:'PRIVATE STOCK NOTE'}]};
const result={description:'Блок отопителя с зелёной подсветкой.',metaDescription:'Блок отопителя с зелёной подсветкой. Информация об исполнении в карточке товара.'};
test('private gateway is opt-in, fixed destination, and never retries an uncertain request',async()=>{
 const before=process.env.AI_TEXT_OPENAI_GATEWAY;process.env.AI_TEXT_OPENAI_GATEWAY='true';let calls=0;
 try{await assert.rejects(()=>requestAIText('openai','qa-secret',{},async(input)=>{calls++;assert.equal(input,'https://89.124.96.238:14446/v1/responses');throw Error('sensitive upstream error');}),e=>(e as any).code==='AI_UNCERTAIN'&&!(e as Error).message.includes('sensitive'));assert.equal(calls,1);
 await assert.rejects(()=>requestAIText('deepseek','qa-secret',{},async(input)=>{assert.equal(input,'https://api.deepseek.com/chat/completions');return Response.json({},{status:403});}),e=>(e as any).code==='AI_ACCESS');
 }finally{if(before===undefined)delete process.env.AI_TEXT_OPENAI_GATEWAY;else process.env.AI_TEXT_OPENAI_GATEWAY=before;}
});
test('configured AI budget accepts ten dollars and preserves the approved ceiling',()=>{
 const previous=process.env.AI_TEXT_MONTHLY_BUDGET_USD;
 try{for(const [input,expected] of [['10','10.00000000'],['7.5','7.50000000'],['100','10.00000000'],['-1','0.00000000'],['invalid','0.00000000'],['Infinity','0.00000000']]){process.env.AI_TEXT_MONTHLY_BUDGET_USD=input;assert.equal(aiConfig().limitUsd,expected);}}
 finally{if(previous===undefined)delete process.env.AI_TEXT_MONTHLY_BUDGET_USD;else process.env.AI_TEXT_MONTHLY_BUDGET_USD=previous;}
});
test('OpenAI unexpected paid tier trips the usage circuit breaker',async()=>{
 await assert.rejects(()=>requestAIText('openai','qa-only',{},async()=>Response.json({service_tier:'priority',usage:{input_tokens:100,output_tokens:50}})),error=>(error as any).code==='AI_USAGE');
});
test('source allowlist excludes prices, stock, SEO title, existing prose and file IDs',()=>{const source=JSON.stringify(aiSource(data,'Проверенный факт'));for(const text of ['1800','PRIVATE','MANUAL','initialStock','price','photos'])assert.ok(!source.includes(text),text);assert.equal(aiSourceSignature(data,''),aiSourceSignature({...data,description:'changed',seoTitle:'changed'},''));assert.notEqual(aiSourceSignature(data,''),aiSourceSignature({...data,name:'Другой товар'},''));});
test('facts translate dictionaries and preserve SKU override and unknown fitment',()=>{const d=structuredClone(data);d.attributes=[{attributeId:attr,value}];d.fitment=[{vehicleId:car,versionId:'',yearFrom:'',yearTo:'',ac:'unknown',state:'unknown',note:''}];d.variants[0]!.fitmentMode='replace';const facts=factsForAI(d,options,'Проверенный факт');assert.equal(facts.attributes[0]!.value,'Зелёная');assert.equal(facts.fitment[0]!.state,'unknown');assert.deepEqual(facts.variants[0]!.fitment,[]);assert.ok(!JSON.stringify(facts).includes('PRIVATE'));assert.throws(()=>factsForAI({...d,categoryId:randomUUID()},options,''));});
test('output requires exactly two bounded text fields and rejects HTML and malformed JSON',()=>{assert.deepEqual(parseAIText(JSON.stringify(result)),result);for(const bad of ['text',JSON.stringify({...result,seoTitle:'overwrite'}),JSON.stringify({...result,description:'<script>alert(1)</script>'}),JSON.stringify({...result,metaDescription:'x'.repeat(321)}),JSON.stringify({...result,description:'https://bad.invalid/payload'})])assert.throws(()=>parseAIText(bad));});
test('peak uncached costs use exact decimal USD and reserve a conservative token ceiling',()=>{assert.equal(usageCost('deepseek',{inputTokens:1000,outputTokens:1000}),'0.00150000');assert.equal(usageCost('openai',{inputTokens:1000,outputTokens:1000}),'0.00062500');assert.ok(Number(reservationCost('deepseek',{name:'товар'}))>Number(usageCost('deepseek',{inputTokens:1000,outputTokens:100})));});
test('DeepSeek request is fixed-host, no tools, thinking disabled and bounded; output tokens billed',async()=>{const fetcher:typeof fetch=async(input,init)=>{assert.equal(input,'https://api.deepseek.com/chat/completions');assert.equal(init?.redirect,'error');const body=JSON.parse(String(init?.body));assert.equal(body.model,TEXT_PRICES.deepseek.model);assert.deepEqual(body.thinking,{type:'disabled'});assert.equal(body.max_tokens,TEXT_MAX_OUTPUT);assert.equal(body.tools,undefined);assert.equal(body.response_format.type,'json_object');return Response.json({choices:[{finish_reason:'stop',message:{content:JSON.stringify(result)}}],usage:{prompt_tokens:100,completion_tokens:50}});};assert.deepEqual((await requestAIText('deepseek','qa-secret',{name:'Блок отопителя с зелёной подсветкой'},fetcher)).result,checkTextFacts(result,{name:'Блок отопителя с зелёной подсветкой'}));});
test('OpenAI uses Responses, no storage or tools, parses output beyond non-message entries',async()=>{const fetcher:typeof fetch=async(input,init)=>{assert.equal(input,'https://api.openai.com/v1/responses');const body=JSON.parse(String(init?.body));assert.equal(body.store,false);assert.equal(body.service_tier,'default');assert.ok(body.input.startsWith('Product facts (JSON):\n'));assert.equal(body.max_output_tokens,TEXT_MAX_OUTPUT);assert.equal(body.tools,undefined);return Response.json({status:'completed',output:[{type:'reasoning'},{type:'message',content:[{type:'output_text',text:JSON.stringify(result)}]}],usage:{input_tokens:100,output_tokens:50}});};assert.deepEqual((await requestAIText('openai','qa-secret',{name:'Блок отопителя с зелёной подсветкой'},fetcher)).result,checkTextFacts(result,{name:'Блок отопителя с зелёной подсветкой'}));});
test('billing uncertainty is distinct from explicit rejection, error bodies do not leak',async()=>{await assert.rejects(()=>requestAIText('deepseek','qa-secret',{},async()=>{throw Error('secret network detail');}),e=>(e as any).code==='AI_UNCERTAIN'&&!(e as Error).message.includes('secret'));await assert.rejects(()=>requestAIText('deepseek','qa-secret',{},async()=>Response.json({error:'qa-secret'},{status:401})),e=>(e as any).definitelyNotCharged===true&&!(e as Error).message.includes('qa-secret'));await assert.rejects(()=>requestAIText('deepseek','qa-secret',{},async()=>Response.json({error:'qa-secret'},{status:500})),e=>(e as any).definitelyNotCharged===false);});
test('invalid or incomplete output retains metering instead of pretending no charge',async()=>{for(const finish_reason of ['stop','length']){const response=await requestAIText('deepseek','qa-secret',{},async()=>Response.json({choices:[{finish_reason,message:{content:'not JSON'}}],usage:{prompt_tokens:100,completion_tokens:50}}));assert.equal(response.result,null);assert.equal(response.usage.outputTokens,50);assert.ok(response.errorCode);}});
test('billing quota errors are distinct from temporary rate limits without leaking provider text',async()=>{await assert.rejects(()=>requestAIText('openai','qa-secret',{},async()=>Response.json({error:{code:'insufficient_quota',message:'private vendor text'}},{status:429})),e=>(e as any).code==='AI_BALANCE'&&(e as any).definitelyNotCharged===true&&!(e as Error).message.includes('private'));});
test('oversized inherited facts fail clearly before database reservation or network use',async()=>{const d=structuredClone(data);d.attributes=[{attributeId:attr,value:'а'.repeat(1900)}];d.variants=Array.from({length:20},()=>({...emptyVariant(randomUUID()),name:'Вариант'}));const opts={...options,attributes:[{...options.attributes[0]!,type:'text',values:[]}]};await assert.rejects(()=>generateProductText({id:randomUUID()},{productId:randomUUID(),idempotencyKey:randomUUID(),data:d,provider:'deepseek',notes:''},{options:opts,config:{provider:'deepseek',keys:{},enabled:false,limitUsd:'0'},adapter:async()=>{throw Error('Must not call');}}),e=>(e as any).code==='AI_INPUT'&&(e as any).status===400);});
test('fact check rejects unsupported finish, manufacturer, fitment, marketplace IDs and numbers',()=>{const facts={name:'Консоль панель на ВАЗ 2114 под 9 дюймов',attributes:[{name:'Цвет',value:'черный'},{name:'Бренд',value:'Spacecraft'}]};for(const text of ['Консоль глянцевая, цвет черный.','Производитель Spacecraft.','Панель подходит для ВАЗ 2114.','Артикул Wildberries 123456.','Черная панель с экраном 12 дюймов.'])assert.throws(()=>checkTextFacts({description:text,metaDescription:'Панель для салона автомобиля.'},facts));const good=checkTextFacts({description:facts.name+'. Черное исполнение, бренд Spacecraft.',metaDescription:facts.name+'. Черное исполнение.'},facts);assert.match(good.description,/Совместимость уточняйте/);});
test('marketplace identifiers are excluded from the provider fact set',()=>{const def=randomUUID();const source={...data,attributes:[{attributeId:def,value:'12345678'}]};const opts={...options,attributes:[...options.attributes,{id:def,name:'Артикул Wildberries',type:'text',unit:null,categoryIds:[],values:[]}]};const facts=factsForAI(source,opts,'');assert.ok(!JSON.stringify(facts).includes('12345678'));assert.ok(!JSON.stringify(facts).includes('QA-GREEN'));});
test('explicit gloss supports inflected wording; internal input commentary is removed',()=>{const facts={name:'Дефлекторы AMG черный глянец'};const result=checkTextFacts({description:'Дефлекторы AMG черный глянец. Чёрное глянцевое исполнение. Другие характеристики в переданных данных не подтверждены.',metaDescription:'Дефлекторы AMG черный глянец.'},facts);assert.match(result.description,/глянцевое/);assert.doesNotMatch(result.description,/переданных/);});
test('useful paragraphs survive cleanup and the fitment notice remains separate',()=>{
 const facts={name:'Дефлекторы AMG',attributes:[{name:'Цвет',value:'чёрный'},{name:'Поверхность',value:'глянец'}]};
 const paragraphs=['Дефлекторы AMG — чёрное глянцевое исполнение.','При выборе оформления сравните цвет и поверхность с остальными деталями салона.'];
 const answer=checkTextFacts({description:paragraphs[0]+'\r\n\r\nДругие характеристики в переданных данных не подтверждены.\r\n\r\n'+paragraphs[1],metaDescription:'Дефлекторы AMG: чёрное глянцевое исполнение.'},facts);
 assert.deepEqual(answer.description.split('\n\n'),[...paragraphs,'Совместимость уточняйте для выбранного исполнения в карточке товара.']);
});
test('sparse inputs do not become claims that no other product properties exist',()=>{
 const facts={name:'Панель',attributes:[{name:'Цвет',value:'зелёный'}]};
 const answer=checkTextFacts({description:'Панель в зелёном исполнении.\n\nЗелёный цвет — единственное подтверждённое отличие этой версии. Других подтверждённых характеристик для этой позиции нет. Перед заказом сравните цвет с остальными деталями салона.',metaDescription:'Панель в зелёном исполнении.'},facts);
 assert.equal(answer.description,'Панель в зелёном исполнении.\n\nПеред заказом сравните цвет с остальными деталями салона.\n\nСовместимость уточняйте для выбранного исполнения в карточке товара.');
});
