import {test} from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {emptyProduct,emptyVariant,bundleTotals,bundleDiscount,publicationIssues,type BundleSku} from '../src/lib/product-editor.ts';
import {normalizeProduct} from '../src/server/product-editor.ts';
const sku:BundleSku={id:randomUUID(),productId:randomUUID(),productName:'Блок',name:'Красный',article:'R',price:'10.05',available:11,published:true,imageId:null,hasPackage:true};
test('bundle price and capacity use exact rubles, discount and component quantities',()=>{const second={...sku,id:randomUUID(),price:'20.10',available:7};assert.deepEqual(bundleTotals({components:[{skuId:sku.id,quantity:'3'},{skuId:second.id,quantity:'2'}],discountPercent:'12,50'},[sku,second]),{subtotal:'70.35',total:'61.56',available:3,published:true,packaged:true});assert.equal(bundleTotals({components:[{skuId:sku.id,quantity:'12'}]},[sku]).available,0);assert.equal(bundleTotals({components:[{skuId:sku.id,quantity:'1'}]},[{...sku,published:false}]).published,false);});
test('bundle drafts preserve incomplete composition, published bundles require a valid unique composition',()=>{const draft={...emptyProduct(),kind:'bundle' as const,components:[],discountPercent:''};assert.deepEqual(normalizeProduct(draft),draft);assert.ok(publicationIssues(draft).some(e=>e.path==='components'));const data={...draft,name:'Комплект',slug:'komplekt',categoryId:randomUUID(),photos:[{id:randomUUID(),alt:''}],components:[{skuId:sku.id,quantity:'2'}],discountPercent:'0'};assert.deepEqual(publicationIssues(data),[]);for(const quantity of ['0','-1','1.5','10001',''])assert.ok(publicationIssues({...data,components:[{skuId:sku.id,quantity}]}).some(e=>e.path==='components.0.quantity'));assert.ok(publicationIssues({...data,components:[...data.components,...data.components]}).some(e=>e.path==='components'));});
test('bundles cannot own SKUs, stock or nested products; discount and money ranges are checked',()=>{assert.throws(()=>normalizeProduct({...emptyProduct(),kind:'bundle',variants:[emptyVariant(randomUUID())]}));assert.throws(()=>normalizeProduct({...emptyProduct(),components:[{skuId:sku.id,quantity:'1'}]}));assert.throws(()=>normalizeProduct({...emptyProduct(),kind:'bundle',components:[{skuId:'not-a-sku',quantity:'1'}]}));for(const discount of ['101','-1','NaN','5.123','1e2',''])assert.throws(()=>bundleDiscount(discount));assert.throws(()=>bundleTotals({components:[{skuId:sku.id,quantity:'10000'}]},[{...sku,price:'90071992547409.91'}]));assert.equal(bundleDiscount('100'),10000);});

test('bundle editor accepts twenty distinct positions and rejects twenty-one on the server',()=>{const components=Array.from({length:20},()=>({skuId:randomUUID(),quantity:'1'}));const data={...emptyProduct(),kind:'bundle' as const,components,discountPercent:'0'};assert.equal(normalizeProduct(data).components!.length,20);const large={...data,components:[...components,{skuId:randomUUID(),quantity:'1'}]};assert.throws(()=>normalizeProduct(large));assert.ok(publicationIssues(large).some(i=>i.path==='components'));});
