// Real CDEK directories/calculator, ephemeral database, no shipments or external messages.
import assert from'node:assert/strict';import{spawn}from'node:child_process';import{createRequire}from'node:module';import{randomUUID}from'node:crypto';import{readFileSync,writeFileSync,mkdirSync}from'node:fs';import{qaDatabase}from'./helpers/qa-db.mjs';
const require=createRequire(import.meta.url),{chromium}=require(process.env.HOME+'/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
assert.equal(process.env.AR_CDEK_BROWSER,'1','Explicit real calculator test invocation required');
const readEnv=p=>Object.fromEntries(readFileSync(p,'utf8').split(/\r?\n/).filter(l=>l&&!l.startsWith('#')&&l.includes('=')).map(l=>{const i=l.indexOf('=');return[l.slice(0,i),l.slice(i+1)];}));
const env=readEnv('.env'),carrier=readEnv('private/cdek.env'),base='http://127.0.0.1:14330';let qa,server,browser;const errors=[],report={passed:false,cleanup:false,checks:[],realCarrierApi:true,shipmentsCreated:0};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));const check=async(name,fn)=>{await fn();report.checks.push({name,passed:true});console.log('PASS '+name);};
mkdirSync('artifacts/cdek-checkout',{recursive:true});
try{
 assert.equal(await fetch(base+'/health').then(()=>true).catch(()=>false),false);qa=await qaDatabase('cdek_browser');
 const product=randomUUID(),sku=randomUUID(),pack=randomUUID();await qa.query("INSERT INTO ar_packages(id,name,weight_g,length_mm,width_mm,height_mm) VALUES($1,'QA 1шт',200,220,100,40)",[pack]);await qa.query("INSERT INTO ar_products(id,name,slug,category_id,status,is_demo) VALUES($1,'QA — Блок отопителя',$2,'00000000-0000-4000-8000-000000000001','published',true)",[product,'qa-'+product]);await qa.query("INSERT INTO ar_skus(id,product_id,article,name,price_rubles,package_id,status) VALUES($1,$2,$3,'QA зелёный','1800.00',$4,'published')",[sku,product,'QA-'+sku,pack]);await qa.query('INSERT INTO ar_stock(sku_id,on_hand,reserved) VALUES($1,10,0)',[sku]);
 server=spawn(process.execPath,['dist/server/entry.mjs'],{env:{...process.env,...carrier,AR_DATABASE_NAME:qa.database,AR_DB_HOST:'127.0.0.1',AR_DB_PORT:env.DB_PORT,APP_DB_PASSWORD:env.APP_DB_PASSWORD,APP_SECRET:env.APP_SECRET,APP_ORIGIN:base,STORE_MODE:'local-test',SHIPPING_PROVIDER:'cdek',PAYMENT_PROVIDER:'simulation',HOST:'127.0.0.1',PORT:'14330'},stdio:['ignore','ignore','pipe']});let log='';server.stderr.on('data',d=>log=(log+d).slice(-2000));
 for(let i=0;i<100;i++){if(await fetch(base+'/health').then(r=>r.ok).catch(()=>false))break;await sleep(100);if(i===99)throw Error('QA server unavailable');}
 browser=await chromium.launch({channel:'chrome',headless:true});const ctx=await browser.newContext({viewport:{width:1440,height:1050},locale:'ru-RU',reducedMotion:'reduce'}),page=await ctx.newPage();page.setDefaultTimeout(20000);page.on('pageerror',e=>errors.push(e.message));
 const api=async(path,body)=>{const session=await(await ctx.request.get(base+'/api/commerce/session')).json();const r=body?await ctx.request.post(base+path,{headers:{Origin:base,'X-CSRF-Token':session.csrfToken},data:{...body,idempotencyKey:randomUUID()}}):await ctx.request.get(base+path);const data=await r.json();assert.equal(r.status(),200,path+': '+data.error?.code);return data;};
 const add=async()=>{const cart=await api('/api/commerce/cart');return api('/api/commerce/cart',{productId:product,skuId:sku,mode:'add',quantity:1,cartVersion:cart.version});};await add();let quote;
 await check('pickup selection shows the shipping price before contact details, with map and synchronized fields',async()=>{
  await page.goto(base+'/checkout',{waitUntil:'domcontentloaded'});await page.locator('#checkout-form').waitFor();
  await page.locator('[name=city]').fill('Москва');
  await page.getByRole('button',{name:'Найти город'}).click();await page.locator('[name=cityCode] option[value="44"]').waitFor({state:'attached'});await page.locator('[name=cityCode]').selectOption('44');await page.locator('[name=pointCode] option[value="MSK2"]').waitFor({state:'attached',timeout:30000});await page.locator('[name=pointCode]').selectOption('MSK2');await page.locator('.pickup-marker.selected').first().waitFor();
  await page.locator('.pickup-marker.selected').first().focus();await page.keyboard.press('Enter');await page.getByRole('button',{name:'Выбрать этот ПВЗ'}).waitFor();await page.waitForTimeout(450);assert.equal(await page.getByRole('button',{name:'Выбрать этот ПВЗ'}).isVisible(),true,'Popup must survive its automatic pan');await page.getByRole('button',{name:'Выбрать этот ПВЗ'}).click();assert.equal(await page.locator('[name=selectedPointCode]').inputValue(),'MSK2');assert.match(await page.locator('[name=selectedPointAddress]').inputValue(),/Международная/);
  await page.waitForFunction(()=>Boolean(document.querySelector('[data-delivery-total]')?.getAttribute('data-delivery-total')));assert.equal(await page.locator('[name=email]').inputValue(),'');assert.match(await page.locator('[data-point-controls] [data-delivery-cost-preview]').innerText(),/Доставка.*₽.*Итого/);
  for(const[name,value]of Object.entries({name:'QA покупатель',phone:'+79990000000',email:'cdek-browser@example.invalid'}))await page.locator(`[name=${name}]`).fill(value);
  await page.waitForFunction(()=>[...document.querySelectorAll('.leaflet-tile')].some(i=>i.complete&&i.naturalWidth>0),null,{timeout:15000});
  for(const width of [1440,375]){await page.setViewportSize({width,height:1050});await page.locator('[data-pickup-map]').scrollIntoViewIfNeeded();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await page.screenshot({path:`artifacts/cdek-checkout/map-${width}.png`,fullPage:true});}
 });
 await check('CDEK quote, per-order tariff snapshot and existing test payment work together',async()=>{
  const response=page.waitForResponse(r=>r.url().endsWith('/api/commerce/quote')&&r.request().method()==='POST');await page.getByRole('button',{name:'Проверить заказ и доставку'}).click();const r=await response;quote=await r.json();assert.equal(r.status(),200,quote.error?.code);assert.equal(quote.groups[0].shipping.carrier.provider,'cdek');assert.equal(quote.groups[0].shipping.costRubles,quote.groups[0].shipping.carrier.costRubles);await page.locator('[data-quote-review]').waitFor();await page.screenshot({path:'artifacts/cdek-checkout/quote-375.png',fullPage:true});
  await page.locator('[data-confirm-checkout]').click();await page.waitForURL('**/orders/**');await page.locator('.status-pill.awaiting_payment').waitFor();const id=new URL(page.url()).pathname.split('/').at(-1),order=await api('/api/commerce/order?id='+id);assert.equal(order.shippingCostRubles,quote.groups[0].shipping.costRubles);assert.equal(order.delivery.carrier.tariffCode,136);assert.equal(order.delivery.pointCode,'MSK2');await page.getByRole('button',{name:'Оплатить тестово',exact:true}).click();await page.locator('.status-pill.paid').waitFor();
 });
 await check('courier uses selected city and a street address, without a stale pickup code',async()=>{
  await add();await page.goto(base+'/checkout',{waitUntil:'domcontentloaded'});await page.locator('#checkout-form').waitFor();for(const[name,value]of Object.entries({name:'QA покупатель',phone:'+79990000000',email:'cdek-browser@example.invalid',city:'Москва'}))await page.locator(`[name=${name}]`).fill(value);await page.getByRole('radio',{name:'СДЭК — доставка до двери',exact:true}).check();await page.getByRole('button',{name:'Найти город'}).click();await page.locator('[name=cityCode] option[value="44"]').waitFor({state:'attached'});await page.locator('[name=cityCode]').selectOption('44');await page.locator('[name=address]').fill('ул. Международная, 15');const response=page.waitForResponse(r=>r.url().endsWith('/api/commerce/quote')&&r.request().method()==='POST');await page.getByRole('button',{name:'Проверить заказ и доставку'}).click();const r=await response,value=await r.json();assert.equal(r.status(),200);assert.equal(value.groups[0].shipping.carrier.tariffCode,137);assert.equal(value.delivery.pointCode,undefined);
 });
 await check('directory failure permits manual entry with unknown cost and no premature payment',async()=>{
  await page.goto(base+'/checkout',{waitUntil:'domcontentloaded'});await page.locator('#checkout-form').waitFor();await page.route('**/api/shipping/cities?*',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{message:'QA Справочник недоступен'}})}));await page.locator('[name=city]').fill('Москва');await page.getByRole('button',{name:'Найти город'}).click();await page.locator('[data-shipping-error]').waitFor();await page.locator('[name=manualDelivery]').check();for(const[name,value]of Object.entries({name:'QA ручная доставка',phone:'+79990000000',email:'manual-qa@example.invalid',address:'ПВЗ требует уточнения'}))await page.locator(`[name=${name}]`).fill(value);const response=page.waitForResponse(r=>r.url().endsWith('/api/commerce/quote')&&r.request().method()==='POST');await page.getByRole('button',{name:'Проверить заказ и доставку'}).click();const r=await response,value=await r.json();assert.equal(r.status(),200);assert.equal(value.groups[0].shipping.costRubles,null);await page.screenshot({path:'artifacts/cdek-checkout/manual-375.png',fullPage:true});
 });
 assert.deepEqual(errors,[]);report.passed=true;
}catch(e){report.error=e.message;throw e;}finally{await browser?.close();if(server){server.kill('SIGTERM');await Promise.race([new Promise(r=>server.once('exit',r)),sleep(5000)]);if(server.exitCode===null&&server.signalCode===null)server.kill('SIGKILL');}if(qa)await qa.close();report.cleanup=true;writeFileSync('artifacts/cdek-checkout/browser.json',JSON.stringify(report,null,2)+'\n');}
