import test from'node:test';import assert from'node:assert/strict';import{randomUUID}from'node:crypto';import{mkdirSync,writeFileSync}from'node:fs';
import{qaDatabase}from'./helpers/qa-db.mjs';import type{ShopSession,QuoteGroup}from'../src/lib/commerce-types.ts';
import{createCdekShipping}from'../src/server/cdek-shipping.ts';import{CdekError,type createCdekClient}from'../src/server/adapters/cdek.ts';
test('CDEK checkout on an isolated PostgreSQL clone',{skip:process.env.AR_CDEK_TESTS!=='1'},async t=>{
 const qa=await qaDatabase('cdek');process.env.SHIPPING_PROVIDER='cdek';process.env.CDEK_CLIENT_ID='fixture';process.env.CDEK_CLIENT_SECRET='fixture-secret';process.env.CDEK_FROM_PVZ='MKHCH13';process.env.CDEK_FROM_CITY_CODE='442';
 const cart=await import('../src/server/cart.ts'),orders=await import('../src/server/orders.ts'),db=await import('../src/server/db.ts');
 const report:{checks:{name:string;passed:boolean}[];passed:boolean;cleanup:boolean}={checks:[],passed:false,cleanup:false};
 const check=async(name:string,fn:()=>Promise<void>)=>t.test(name,async()=>{await fn();report.checks.push({name,passed:true});});
 const delivery={method:'pickup_point',city:'Forged name',cityCode:44,pointCode:'MSK1',address:'Forged address'};
 const customer={name:'QA CDEK',phone:'+79990000000',email:'cdek-qa@example.invalid'};
 let calls=0,hook:(()=>Promise<void>)|undefined,bad=false;
 const client={cities:async()=>[],offices:async()=>({items:[],hasMore:false}),getCity:async(code:number)=>code===44?{code,name:'Москва',region:'Москва',subRegion:''}:null,getPoint:async(code:string)=>['MSK1','MKHCH13'].includes(code)?{code,name:code,cityCode:code==='MSK1'?44:442,city:'Москва',address:'Улица, 1',workTime:'10–20',reception:true,handout:true,latitude:55,longitude:37}:null,quote:async()=>{calls++;if(hook)await hook();if(bad)throw new CdekError('UNAVAILABLE');return{provider:'cdek',tariffCode:136,tariffName:'Посылка',costRubles:'390.00',currency:'RUB',periodMin:3,periodMax:4,quotedAt:new Date().toISOString(),originPointCode:'MKHCH13',originCityCode:442};}} as unknown as ReturnType<typeof createCdekClient>;
 const shipping=createCdekShipping(()=>client);
 async function session():Promise<ShopSession>{const id=randomUUID(),csrf=randomUUID();await qa.query("INSERT INTO ar_web_sessions(id,token_hash,csrf_token,expires_at) VALUES($1,$2,$3,now()+interval '1 day')",[id,randomUUID(),csrf]);return{id,csrfToken:csrf,email:null,expiresAt:new Date(Date.now()+86400000).toISOString()};}
 async function fixture(stock=5,pack=true){const productId=randomUUID(),skuId=randomUUID(),packageId=randomUUID();if(pack)await qa.query('INSERT INTO ar_packages(id,name,weight_g,length_mm,width_mm,height_mm) VALUES($1,\'QA\',200,220,100,40)',[packageId]);await qa.query("INSERT INTO ar_products(id,name,slug,kind,category_id,status) VALUES($1,'QA CDEK',$2,'single','00000000-0000-4000-8000-000000000001','published')",[productId,'qa-'+productId]);await qa.query("INSERT INTO ar_skus(id,product_id,article,name,price_rubles,status,package_id) VALUES($1,$2,$3,'QA','1800.00','published',$4)",[skuId,productId,'QA-'+skuId,pack?packageId:null]);await qa.query('INSERT INTO ar_stock(sku_id,on_hand,reserved) VALUES($1,$2,0)',[skuId,stock]);return{productId,skuId,packageId};}
 async function add(s:ShopSession,item:{productId:string;skuId:string},quantity=1){const c=await cart.getCart(s);return cart.changeCart(s,{...item,quantity,mode:'add',cartVersion:c.version,idempotencyKey:randomUUID()});}
 async function preview(s:ShopSession,d=delivery){return cart.createQuote(s,{customer,delivery:d,cartVersion:(await cart.getCart(s)).version,costRubles:'0.01'},shipping);}
 const buy=(s:ShopSession,q:any)=>orders.checkout(s,{quoteId:q.id,cartVersion:q.cartVersion,idempotencyKey:randomUUID(),shippingCostRubles:'0.01'});
 const reject=(fn:()=>Promise<unknown>,code:string)=>assert.rejects(fn,e=>(e as any).code===code);
 try{
 await check('server resolves point identity and snapshots actual rate; checkout and repeats never call CDEK under SQL locks',async()=>{const s=await session(),item=await fixture();await add(s,item);const q=await preview(s);assert.equal(q.delivery.city,'Москва');assert.equal(q.delivery.address,'Улица, 1');assert.equal(q.groups[0]!.totalRubles,'2190.00');const count=calls;const[first,second]=await Promise.all([buy(s,q),buy(s,q)]);assert.deepEqual(first.orderIds,second.orderIds);assert.equal(calls,count);const o=first.orders[0]!;assert.equal(o.shippingCostRubles,'390.00');assert.equal(o.delivery.carrier?.tariffCode,136);assert.equal(o.delivery.pointCode,'MSK1');assert.deepEqual((await qa.query('SELECT on_hand,reserved FROM ar_stock WHERE sku_id=$1',[item.skuId])).rows[0],{on_hand:5,reserved:1});});
 await check('unknown package and multiple units need a packing rule; no guessed dimension or tariff',async()=>{const s=await session(),item=await fixture();await add(s,item,2);const count=calls,q=await preview(s);assert.equal(calls,count);assert.equal(q.groups[0]!.shipping.costRubles,null);const o=(await buy(s,q)).orders[0]!;assert.equal(o.canPay,false);assert.equal(o.status,'open');});
 await check('ordinary and preorder get independent quotes, and preorder has no early reserve',async()=>{const s=await session(),a=await fixture(),b=await fixture(0);await add(s,a);await add(s,b);const before=calls,q=await preview(s);assert.equal(calls-before,2);assert.equal(q.groups.length,2);const result=await buy(s,q);assert.equal(result.orders[1]!.shippingCostRubles,'390.00');assert.equal((await qa.query('SELECT reserved FROM ar_stock WHERE sku_id=$1',[b.skuId])).rows[0].reserved,0);});
 await check('provider failure keeps total unknown and manager can complete shipping safely',async()=>{const s=await session(),item=await fixture();await add(s,item);bad=true;const q=await preview(s);bad=false;assert.equal(q.groups[0]!.totalRubles,null);const o=(await buy(s,q)).orders[0]!;assert.equal(o.canPay,false);const actor=(await qa.query('SELECT id FROM directus_users LIMIT 1')).rows[0];const changed=await orders.quoteShipping(actor,{orderId:o.id,costRubles:'450.00',note:'QA ручной расчёт',idempotencyKey:randomUUID()});assert.equal(changed.canPay,true);assert.equal(changed.totalRubles,'2250.00');});
 await check('manual address stays manual even when the API works',async()=>{const s=await session(),item=await fixture();await add(s,item);const before=calls,q=await preview(s,{...delivery,manual:true} as any);assert.equal(calls,before);assert.equal(q.groups[0]!.shipping.costRubles,null);});
 await check('invalid city or wrong-city point cannot become a paid delivery quote',async()=>{const s=await session(),item=await fixture();await add(s,item);await reject(()=>preview(s,{...delivery,cityCode:442}),'CDEK_CITY');await reject(()=>preview(s,{...delivery,pointCode:'MKHCH13'}),'CDEK_POINT');});
 await check('no cart/stock locks during carrier request; price changes during network invalidate the quote',async()=>{const s=await session(),item=await fixture();await add(s,item);hook=async()=>{const c=await qa.owner.connect();try{await c.query('BEGIN');await c.query('SELECT * FROM ar_carts WHERE session_id=$1 FOR UPDATE NOWAIT',[s.id]);await c.query('SELECT * FROM ar_stock WHERE sku_id=$1 FOR UPDATE NOWAIT',[item.skuId]);await c.query('UPDATE ar_skus SET price_rubles=1801 WHERE id=$1',[item.skuId]);await c.query('COMMIT');}finally{c.release();}};await reject(()=>preview(s),'QUOTE_CHANGED');hook=undefined;});
 await check('package changes after a quote force review without reserving anything',async()=>{const s=await session(),item=await fixture();await add(s,item);const q=await preview(s);await qa.query('UPDATE ar_packages SET weight_g=201 WHERE id=$1',[item.packageId]);await reject(()=>buy(s,q),'QUOTE_CHANGED');assert.equal((await qa.query('SELECT reserved FROM ar_stock WHERE sku_id=$1',[item.skuId])).rows[0].reserved,0);});
 await check('stock repartition or origin changes invalidate confirmed rates',async()=>{const s=await session(),item=await fixture();await add(s,item);const q=await preview(s);await qa.query('UPDATE ar_stock SET on_hand=0 WHERE sku_id=$1',[item.skuId]);await reject(()=>buy(s,q),'QUOTE_CHANGED');await qa.query('UPDATE ar_stock SET on_hand=5 WHERE sku_id=$1',[item.skuId]);process.env.CDEK_FROM_PVZ='MKHCH14';await reject(()=>buy(s,q),'QUOTE_CHANGED');process.env.CDEK_FROM_PVZ='MKHCH13';});
 await check('expired and foreign-session quotes are rejected',async()=>{const s=await session(),item=await fixture();await add(s,item);const q=await preview(s);await reject(async()=>buy(await session(),q),'QUOTE_NOT_FOUND');await qa.query("UPDATE ar_cart_quotes SET expires_at=now()-interval '1 second' WHERE id=$1",[q.id]);await reject(()=>buy(s,q),'QUOTE_EXPIRED');});
 report.passed=report.checks.length===10;
 }finally{await db.getPool().end();await qa.close();report.cleanup=true;mkdirSync('artifacts/cdek-checkout',{recursive:true});writeFileSync('artifacts/cdek-checkout/integration.json',JSON.stringify(report,null,2)+'\n');}
});
