/** Integration acceptance: only an ephemeral clone of this new store database. */
import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID,randomBytes} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {readFileSync,mkdirSync,writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import type {ShopSession,OrderView} from '../src/lib/commerce-types.ts';

const enabled=process.env.AR_COMMERCE_TESTS==='1';
test('commerce integration in isolated PostgreSQL', {skip:!enabled,timeout:180000},async t=>{
 const root=fileURLToPath(new URL('..',import.meta.url));
 const env=Object.fromEntries(readFileSync(`${root}/.env`,'utf8').split(/\r?\n/).filter(line=>line&&!line.startsWith('#')&&line.includes('=')).map(line=>{const pos=line.indexOf('=');return[line.slice(0,pos),line.slice(pos+1)];}));
 const source='autoreelz2026_new',project='autoreelz2026-new';
 assert.equal(env.POSTGRES_DB,source);assert.equal(env.COMPOSE_PROJECT_NAME,project);
 const database=`ar_qa_commerce_${process.pid}_${Date.now()}`;assert.match(database,/^ar_qa_commerce_\d+_\d+$/);
 const report:{database:string;source:string;startedAt:string;finishedAt?:string;checks:{name:string;passed:boolean;error?:string}[];cleanup:boolean;passed?:boolean;setupError?:string;cleanupError?:string}={database,source,startedAt:new Date().toISOString(),checks:[],cleanup:false};
 const compose=['compose','-p',project,'exec','-T','db'];let created=false;
 const execute=(args:string[],input?:string)=>{const result=spawnSync('docker',args,{cwd:root,input,encoding:'utf8',timeout:30000,maxBuffer:128*1024*1024});if(result.error)throw result.error;if(result.status!==0)throw new Error(result.stderr.trim()||'QA database command failed');return result.stdout;};
 const adminSql=(sql:string,db=source)=>{assert.ok(db===source||db===database);return execute([...compose,'psql','-X','-q','-v','ON_ERROR_STOP=1','-U','ar_migrator','-d',db],sql);};
 let owner:import('pg').Pool|undefined,appPool:import('pg').Pool|undefined;
 try{
  const dump=execute([...compose,'pg_dump','-U','ar_migrator','-d',source,'--no-password']);
  adminSql(`CREATE DATABASE ${database};`);created=true;adminSql(dump,database);
  process.env.AR_DATABASE_NAME=database;process.env.AR_DB_HOST='127.0.0.1';process.env.AR_DB_PORT=env.DB_PORT||'65432';process.env.APP_DB_PASSWORD=env.APP_DB_PASSWORD;process.env.APP_SECRET=randomBytes(48).toString('hex');process.env.APP_ORIGIN='http://127.0.0.1:14325';process.env.STORE_MODE='local-test';
  const {default:pg}=await import('pg');owner=new pg.Pool({host:'127.0.0.1',port:Number(process.env.AR_DB_PORT),database,user:'ar_migrator',password:env.POSTGRES_PASSWORD,max:6,connectionTimeoutMillis:5000});
  const db=await import('../src/server/db.ts');appPool=db.getPool();
  const security=await import('../src/server/security.ts'),cart=await import('../src/server/cart.ts'),orders=await import('../src/server/orders.ts'),payments=await import('../src/server/payments.ts'),pricing=await import('../src/server/pricing.ts'),{testPaymentAdapter}=await import('../src/server/adapters/payment.ts'),{workerTick}=await import('../src/server/worker.ts');
  const sql=async(statement:string,values:unknown[]=[])=>owner!.query(statement,values);
  const one=async(statement:string,values:unknown[]=[])=>{const result=await sql(statement,values);assert.equal(result.rows.length,1);return result.rows[0];};
  const actor={id:randomUUID()},category='00000000-0000-4000-8000-000000000001';
  const delivery={method:'pickup_point' as const,city:'QA Москва',address:'QA пункт выдачи, 1'};
  const customer={name:'QA Покупатель',phone:'+79990000000',email:'qa-commerce@example.invalid'};
  async function check(name:string,fn:()=>Promise<void>){await t.test(name,async()=>{try{await fn();report.checks.push({name,passed:true});}catch(error){report.checks.push({name,passed:false,error:error instanceof Error?error.message:String(error)});throw error;}});}
  async function rejected(fn:()=>Promise<unknown>,code:string){await assert.rejects(fn,(error:unknown)=>{assert.equal((error as {code:string}).code,code);return true;});}
  async function session(){const cookies=new Map<string,string>();const ctx={cookies:{get:(name:string)=>cookies.has(name)?{value:cookies.get(name)}:undefined,set:(name:string,value:string)=>cookies.set(name,value),delete:(name:string)=>cookies.delete(name)}};const value=await security.getSession(ctx as never);assert.equal((await security.getSession(ctx as never)).id,value.id);assert.ok(cookies.get(security.COOKIE));return value;}
  async function fixture(onHand=5,price='100.01',packaged=false){const productId=randomUUID(),skuId=randomUUID(),packageId=packaged?randomUUID():null;const article=`QA-${skuId}`;
   if(packageId)await sql('INSERT INTO ar_packages(id,name,weight_g,length_mm,width_mm,height_mm,note) VALUES($1,$2,500,200,100,50,$3)',[packageId,'QA упаковка','Synthetic fixture, not a product fact']);
   await sql("INSERT INTO ar_products(id,name,slug,category_id,status,is_demo) VALUES($1,'QA товар',$2,$3,'published',true)",[productId,`qa-${productId}`,category]);
   await sql("INSERT INTO ar_skus(id,product_id,article,name,price_rubles,status,package_id) VALUES($1,$2,$3,'QA исполнение',$4,'published',$5)",[skuId,productId,article,price,packageId]);
   await sql('INSERT INTO ar_stock(sku_id,on_hand,reserved) VALUES($1,$2,0)',[skuId,onHand]);return{productId,skuId,article,price,packageId};
  }
  type Fixture=Awaited<ReturnType<typeof fixture>>;
  async function bundle(parts:{item:Fixture;quantity:number}[],discount=10){const productId=randomUUID();await sql("INSERT INTO ar_products(id,name,slug,category_id,kind,status,is_demo,discount_percent) VALUES($1,'QA комплект',$2,$3,'bundle','published',true,$4)",[productId,`qa-${productId}`,category,discount]);for(const part of parts)await sql('INSERT INTO ar_bundle_components(bundle_id,sku_id,quantity) VALUES($1,$2,$3)',[productId,part.item.skuId,part.quantity]);return{productId,skuId:null};}
  async function add(s:ShopSession,item:{productId:string;skuId:string|null},quantity=1){const current=await cart.getCart(s);return cart.changeCart(s,{...item,quantity,mode:'add',cartVersion:current.version,idempotencyKey:randomUUID()});}
  async function quote(s:ShopSession){const current=await cart.getCart(s);return cart.createQuote(s,{customer,delivery,cartVersion:current.version});}
  async function buy(item:{productId:string;skuId:string|null},quantity=1){const s=await session();await add(s,item,quantity);const preview=await quote(s);const result=await orders.checkout(s,{quoteId:preview.id,cartVersion:preview.cartVersion,idempotencyKey:randomUUID()});assert.equal(result.orders.length,1);return{s,order:result.orders[0]!,preview};}
  async function state(skuId:string){return one('SELECT on_hand,reserved FROM ar_stock WHERE sku_id=$1',[skuId]);}
  async function moves(orderId:string){return(await sql('SELECT operation_key,stock_delta,reserved_delta FROM ar_stock_movements WHERE order_id=$1 ORDER BY created_at,id',[orderId])).rows;}
  async function makeDue(orderId:string){await sql("UPDATE ar_orders SET expires_at=now()-interval '1 second' WHERE id=$1",[orderId]);}
  async function pay(s:ShopSession,order:OrderView,key=randomUUID()){return payments.payOrder(s,{orderId:order.id,shippingVersion:order.shippingVersion,method:'card',idempotencyKey:key});}
  async function startPay(s:ShopSession,order:OrderView,key=randomUUID()){const result=await payments.initiatePayment(s,{orderId:order.id,shippingVersion:order.shippingVersion,method:'sbp',idempotencyKey:key});assert.ok('paymentId'in result&&result.paymentId);return {id:result.paymentId!,amountRubles:result.amountRubles!};}
  async function shipping(order:OrderView,costRubles='123.45'){return orders.quoteShipping(actor,{orderId:order.id,costRubles,note:'QA подтверждённый расчёт',idempotencyKey:randomUUID()});}
  const cancel=(s:ShopSession,id:string,key=randomUUID())=>orders.cancelOrder(s,{orderId:id,idempotencyKey:key});
  const receipt=(skuId:string,quantity:number,key=randomUUID())=>orders.receiveStock(actor,{skuId,quantity,reason:'QA приход для проверки',idempotencyKey:key});
  const confirm=(id:string,key=randomUUID())=>orders.confirmPreorder(actor,{orderId:id,terms:'QA срок и условия согласованы',idempotencyKey:key});
  // Hold the shared order row until both real application transactions wait on it.
  async function orderRace(orderId:string,first:()=>Promise<unknown>,second:()=>Promise<unknown>){const lock=await owner!.connect();let results:Promise<PromiseSettledResult<unknown>[]>|undefined;try{await lock.query('BEGIN');await lock.query('SELECT id FROM ar_orders WHERE id=$1 FOR UPDATE',[orderId]);results=Promise.allSettled([first(),second()]);const deadline=Date.now()+3000;let waiting=0;while(Date.now()<deadline){waiting=Number((await one("SELECT count(*) n FROM pg_stat_activity WHERE datname=$1 AND usename='ar_app' AND wait_event_type='Lock'",[database])).n);if(waiting>=2)break;await new Promise(resolve=>setTimeout(resolve,20));}assert.ok(waiting>=2,'Both competing commands must be observed waiting on the locked order');}finally{await lock.query('COMMIT');lock.release();}const completed=await results!;for(const result of completed)assert.equal(result.status,'fulfilled',result.status==='rejected'?String(result.reason):undefined);}

  await check('isolation: application uses ar_app in the uniquely named QA clone',async()=>{const r=await db.query('SELECT current_user,current_database() db');assert.equal(r.rows[0].current_user,'ar_app');assert.equal(r.rows[0].db,database);assert.ok((await one('SELECT status FROM ar_categories WHERE id=$1',[category])).status==='published');});
  await check('cart: same key replays once; changed payload and stale version rejected',async()=>{const item=await fixture(),s=await session(),key=randomUUID();const input={productId:item.productId,skuId:item.skuId,quantity:2,mode:'add',cartVersion:0,idempotencyKey:key};const first=await cart.changeCart(s,input),again=await cart.changeCart(s,input);assert.deepEqual(again,first);assert.equal(first.lines[0]!.quantity,2);assert.equal(first.version,1);await rejected(()=>cart.changeCart(s,{...input,quantity:3}),'KEY_REUSED');await rejected(()=>cart.changeCart(s,{...input,idempotencyKey:randomUUID()}),'CART_CHANGED');const next=await add(s,item);assert.equal(next.lines[0]!.quantity,3);assert.deepEqual(await state(item.skuId),{on_hand:5,reserved:0});});
  await check('cart: concurrent distinct commands on one version have one winner',async()=>{const item=await fixture(),s=await session();const result=await Promise.allSettled([1,2].map(quantity=>cart.changeCart(s,{productId:item.productId,skuId:item.skuId,quantity,mode:'add',cartVersion:0,idempotencyKey:randomUUID()})));assert.equal(result.filter(r=>r.status==='fulfilled').length,1);const failed=result.find(r=>r.status==='rejected') as PromiseRejectedResult;assert.equal(failed.reason.code,'CART_CHANGED');assert.equal((await cart.getCart(s)).version,1);});
  await check('checkout: concurrent same key and later different key return the same order',async()=>{const item=await fixture(4,'100.01',true),s=await session();await add(s,item);const preview=await quote(s),input={quoteId:preview.id,cartVersion:preview.cartVersion,idempotencyKey:randomUUID()};const [first,second]=await Promise.all([orders.checkout(s,input),orders.checkout(s,input)]);assert.deepEqual(second.orderIds,first.orderIds);const different=await orders.checkout(s,{...input,idempotencyKey:randomUUID()});assert.deepEqual(different.orderIds,first.orderIds);await rejected(()=>orders.checkout(s,{...input,quoteId:randomUUID()}),'KEY_REUSED');assert.equal((await orders.listOrders(s)).length,1);assert.equal((await cart.getCart(s)).lines.length,0);assert.deepEqual(await state(item.skuId),{on_hand:4,reserved:1});});
  await check('split: partial shortage moves the whole line to preorder without a reserve',async()=>{const item=await fixture(1,'120.00',true);const result=await buy(item,2);assert.equal(result.preview.groups.length,1);assert.equal(result.order.kind,'preorder');assert.equal(result.order.lines[0]!.quantity,2);assert.equal(result.order.expiresAt,null);assert.equal(result.order.canPay,false);assert.deepEqual(await state(item.skuId),{on_hand:1,reserved:0});assert.equal((await moves(result.order.id)).length,0);});
  await check('split: insertion priority, fixed bundle shortage, and separate shipping',async()=>{const a=await fixture(2,'100.01'),b=await fixture(1,'230.00'),kit=await bundle([{item:a,quantity:2},{item:b,quantity:1}]),s=await session();await add(s,a);await add(s,kit);await add(s,b);const preview=await quote(s);assert.deepEqual(preview.groups.map(g=>g.kind),['ordinary','preorder']);assert.deepEqual(preview.groups[0]!.lines.map(l=>l.productId),[a.productId,b.productId]);assert.equal(preview.groups[1]!.lines[0]!.productId,kit.productId);assert.equal(preview.groups[1]!.productTotalRubles,'387.02');assert.equal(preview.groups[0]!.shipping.costRubles,null);assert.equal(preview.groups[1]!.shipping.costRubles,null);const result=await orders.checkout(s,{quoteId:preview.id,cartVersion:preview.cartVersion,idempotencyKey:randomUUID()});assert.equal(result.orders.length,2);assert.deepEqual(await state(a.skuId),{on_hand:2,reserved:1});assert.deepEqual(await state(b.skuId),{on_hand:1,reserved:1});assert.equal(result.orders.find(o=>o.kind==='preorder')!.expiresAt,null);});
  await check('bundle plus standalone component: one shared stock requirement and exact discounted price',async()=>{const a=await fixture(3,'100.01'),b=await fixture(1,'230.00'),kit=await bundle([{item:a,quantity:2},{item:b,quantity:1}]),s=await session();await add(s,kit);await add(s,a);const preview=await quote(s);assert.equal(preview.groups.length,1);assert.equal(preview.groups[0]!.productTotalRubles,'487.03');const result=await orders.checkout(s,{quoteId:preview.id,cartVersion:preview.cartVersion,idempotencyKey:randomUUID()});const order=await shipping(result.orders[0]!);assert.deepEqual(await state(a.skuId),{on_hand:3,reserved:3});assert.deepEqual(await state(b.skuId),{on_hand:1,reserved:1});const needs=(await sql('SELECT sku_id,quantity FROM ar_order_components WHERE order_id=$1',[order.id])).rows;assert.equal(needs.find(n=>n.sku_id===a.skuId).quantity,3);await pay(s,order);assert.deepEqual(await state(a.skuId),{on_hand:0,reserved:0});assert.deepEqual(await state(b.skuId),{on_hand:0,reserved:0});});
  await check('two bundles share the same physical stock and the later one becomes preorder',async()=>{const item=await fixture(1),first=await bundle([{item,quantity:1}]),second=await bundle([{item,quantity:1}]),s=await session();await add(s,first);await add(s,second);const preview=await quote(s);assert.equal(preview.groups[0]!.lines[0]!.productId,first.productId);assert.equal(preview.groups[1]!.lines[0]!.productId,second.productId);await orders.checkout(s,{quoteId:preview.id,cartVersion:preview.cartVersion,idempotencyKey:randomUUID()});assert.deepEqual(await state(item.skuId),{on_hand:1,reserved:1});});
  await check('bundle cannot be sold when a component category is unpublished',async()=>{const item=await fixture(2,'100.01'),kit=await bundle([{item,quantity:1}]),hiddenCategory=randomUUID();await sql("INSERT INTO ar_categories(id,name,slug,status) VALUES($1,'QA скрытая категория',$2,'published')",[hiddenCategory,`qa-${hiddenCategory}`]);await sql('UPDATE ar_products SET category_id=$2 WHERE id=$1',[item.productId,hiddenCategory]);const s=await session();await add(s,kit);const preview=await quote(s);await sql("UPDATE ar_categories SET status='draft' WHERE id=$1",[hiddenCategory]);await rejected(()=>orders.checkout(s,{quoteId:preview.id,cartVersion:preview.cartVersion,idempotencyKey:randomUUID()}),'UNAVAILABLE');assert.equal((await orders.listOrders(s)).length,0);assert.deepEqual(await state(item.skuId),{on_hand:2,reserved:0});});
  await check('two buyers compete for the last SKU: one order and one QUOTE_CHANGED',async()=>{const item=await fixture(1,'100.01',true),a=await session(),b=await session();await add(a,item);await add(b,item);const qa=await quote(a),qb=await quote(b);const results=await Promise.allSettled([[a,qa],[b,qb]].map(([s,p])=>orders.checkout(s as ShopSession,{quoteId:(p as typeof qa).id,cartVersion:(p as typeof qa).cartVersion,idempotencyKey:randomUUID()})));assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal((results.find(r=>r.status==='rejected') as PromiseRejectedResult).reason.code,'QUOTE_CHANGED');assert.deepEqual(await state(item.skuId),{on_hand:1,reserved:1});assert.equal((await orders.listOrders(a)).length+(await orders.listOrders(b)).length,1);});
  await check('unknown delivery stays null and blocks payment; revised delivery rejects stale total',async()=>{const item=await fixture(2),{s,order}=await buy(item);assert.equal(order.shippingCostRubles,null);assert.equal(order.totalRubles,null);assert.equal(order.canPay,false);await rejected(()=>startPay(s,order),'DELIVERY_PENDING');const revised=await shipping(order);assert.equal(revised.shippingCostRubles,'123.45');assert.equal(revised.shippingVersion,order.shippingVersion+1);assert.equal(revised.totalRubles,'223.46');assert.equal(revised.canPay,true);await rejected(()=>startPay(s,order),'TOTAL_CHANGED');await pay(s,revised);});
  await check('snapshot: catalog edits cannot change purchased name, article, price or components',async()=>{const item=await fixture(2,'432.10',true),{s,order}=await buy(item);await sql("UPDATE ar_products SET name='QA изменённый товар' WHERE id=$1",[item.productId]);await sql("UPDATE ar_skus SET name='QA новое исполнение',article=$2,price_rubles=999.99 WHERE id=$1",[item.skuId,`QA-NEW-${item.skuId}`]);const after=await orders.getOrder(s,order.id);assert.deepEqual(after.lines,order.lines);assert.equal(after.productTotalRubles,'432.10');await assert.rejects(()=>sql("UPDATE ar_orders SET items_snapshot='[]'::jsonb WHERE id=$1",[order.id]),/Снимок заказа неизменяем/);await assert.rejects(()=>sql('UPDATE ar_order_components SET quantity=9 WHERE order_id=$1',[order.id]),/Историческая запись неизменяема/);});
  await check('bundle snapshot and physical requirements remain fixed after a CMS composition edit',async()=>{const original=await fixture(2,'200.01'),replacement=await fixture(4,'888.88'),kit=await bundle([{item:original,quantity:2}],5),{s,order}=await buy(kit);const before=await orders.getOrder(s,order.id);await sql('UPDATE ar_bundle_components SET sku_id=$2,quantity=1 WHERE bundle_id=$1',[kit.productId,replacement.skuId]);await sql('UPDATE ar_products SET discount_percent=50 WHERE id=$1',[kit.productId]);assert.deepEqual((await orders.getOrder(s,order.id)).lines,before.lines);assert.equal(before.productTotalRubles,'380.02');await pay(s,await shipping(order));assert.deepEqual(await state(original.skuId),{on_hand:0,reserved:0});assert.deepEqual(await state(replacement.skuId),{on_hand:4,reserved:0});});
  await check('money safety: an overflowing line is rejected atomically',async()=>{const item=await fixture(5,'90071992547409.91'),s=await session();await rejected(()=>add(s,item,2),'PRICE_RANGE');assert.equal((await cart.getCart(s)).lines.length,0);assert.deepEqual(await state(item.skuId),{on_hand:5,reserved:0});});
  await check('rubles: database, order snapshot and payment preserve 0.01 and 7200.50 exactly',async()=>{
   for(const price of ['0.01','7200.50']){
    const item=await fixture(2,price),{s,order}=await buy(item);
    assert.equal((await one('SELECT price_rubles FROM ar_skus WHERE id=$1',[item.skuId])).price_rubles,price);
    assert.equal(order.lines[0]!.unitPriceRubles,price);
    assert.equal(order.lines[0]!.lineTotalRubles,price);
    assert.equal(order.lines[0]!.components[0]!.unitPriceRubles,price);
    assert.equal(order.productTotalRubles,price);
    const revised=await shipping(order,'123.45');
    const expected=price==='0.01'?'123.46':'7323.95';
    assert.equal(revised.shippingCostRubles,'123.45');
    assert.equal(revised.totalRubles,expected);
    const started=await startPay(s,revised);
    assert.equal(started.amountRubles,expected);
    assert.equal((await one('SELECT amount_rubles FROM ar_payments WHERE id=$1',[started.id])).amount_rubles,expected);
    const event=testPaymentAdapter.event(started);
    await payments.applyPaymentEvent(event.event,event.signature);
    assert.equal((await orders.getOrder(s,order.id)).totalRubles,expected);
    assert.deepEqual(await state(item.skuId),{on_hand:1,reserved:0});
   }
  });
  await check('rubles: 0.10 plus 0.20 remains 0.30 through cart, checkout and payment',async()=>{
   const a=await fixture(2,'0.10'),b=await fixture(2,'0.20'),s=await session();
   await add(s,a);const basket=await add(s,b);
   assert.equal(basket.productTotalRubles,'0.30');
   const preview=await quote(s);
   assert.equal(preview.groups[0]!.productTotalRubles,'0.30');
   const result=await orders.checkout(s,{quoteId:preview.id,cartVersion:preview.cartVersion,idempotencyKey:randomUUID()});
   const order=await shipping(result.orders[0]!,'0.01');
   assert.equal(order.totalRubles,'0.31');
   const paid=await pay(s,order);
   assert.equal(paid.status,'paid');assert.equal(paid.totalRubles,'0.31');
   assert.equal((await one("SELECT amount_rubles FROM ar_payments WHERE order_id=$1 AND status='succeeded'",[order.id])).amount_rubles,'0.31');
  });
  await check('rubles: bundle discount rounds half a kopeck up after the component sum',async()=>{
   const a=await fixture(2,'0.01'),b=await fixture(2,'0.02');
   const kit=await bundle([{item:a,quantity:1},{item:b,quantity:1}],50);
   const {order}=await buy(kit);
   assert.equal(order.lines[0]!.unitPriceRubles,'0.02');
   assert.equal(order.productTotalRubles,'0.02');
   assert.deepEqual(order.lines[0]!.components.map(c=>c.unitPriceRubles).sort(),['0.01','0.02']);
   assert.equal((await one('SELECT price_rubles FROM ar_bundle_offer($1)',[kit.productId])).price_rubles,'0.02');
   const summedFirst=await bundle([{item:a,quantity:2}],50);
   const second=await buy(summedFirst);
   assert.equal(second.order.productTotalRubles,'0.01');
  });
  await check('packaging: known unit package, exact multi-unit rule, and provider fallback',async()=>{const item=await fixture(10,'100.01',true);await db.transaction(async c=>{const single=await pricing.snapshotLine(c,item.productId,item.skuId,1),pair=await pricing.snapshotLine(c,item.productId,item.skuId,2);assert.equal((await pricing.shippingQuote(c,[single],delivery)).costRubles,'500.00');assert.equal((await pricing.shippingQuote(c,[single],{...delivery,method:'courier'})).costRubles,'800.00');assert.equal((await pricing.shippingQuote(c,[pair],delivery)).costRubles,null);const failed=await pricing.shippingQuote(c,[single],delivery,true);assert.equal(failed.status,'pending_quote');assert.equal(failed.costRubles,null);assert.match(failed.reason!,/временно недоступен/);});const rule=randomUUID();await sql('INSERT INTO ar_packing_rules(id,name,package_id,components,is_demo) VALUES($1,$2,$3,$4,true)',[rule,'QA ровно два SKU',item.packageId,JSON.stringify({[item.skuId]:2})]);await db.transaction(async c=>{const pair=await pricing.snapshotLine(c,item.productId,item.skuId,2),three=await pricing.snapshotLine(c,item.productId,item.skuId,3);assert.equal((await pricing.shippingQuote(c,[pair],delivery)).costRubles,'500.00');assert.equal((await pricing.shippingQuote(c,[three],delivery)).costRubles,null);});await sql('UPDATE ar_packing_rules SET active=false WHERE id=$1',[rule]);await db.transaction(async c=>assert.equal((await pricing.shippingQuote(c,[await pricing.snapshotLine(c,item.productId,item.skuId,2)],delivery)).costRubles,null));});
  await check('ordinary payment: pending idempotency, duplicate events and repeated pay do not redebit',async()=>{const item=await fixture(3,'170.00',true),{s,order}=await buy(item);const key=randomUUID(),first=await startPay(s,order,key),same=await startPay(s,order,key),other=await startPay(s,order);assert.deepEqual(first,same);assert.deepEqual(first,other);const event=testPaymentAdapter.event(first);assert.equal((await payments.applyPaymentEvent(event.event,event.signature)).outcome,'paid');assert.equal((await payments.applyPaymentEvent(event.event,event.signature)).outcome,'paid');const duplicate={...event.event,eventId:`QA-${randomUUID()}`};assert.equal((await payments.applyPaymentEvent(duplicate,security.sign(security.canonical(duplicate)))).outcome,'duplicate');const paid=await pay(s,order);assert.equal(paid.status,'paid');assert.deepEqual(await state(item.skuId),{on_hand:2,reserved:0});assert.equal((await moves(order.id)).filter(m=>m.stock_delta===-1).length,1);await rejected(()=>payments.applyPaymentEvent({...event.event,amountRubles:'670.01'},security.sign(security.canonical({...event.event,amountRubles:'670.01'}))),'PAYMENT_EVENT_REUSED');});
  await check('payment signature and wrong amount: invalid event denied; signed mismatch goes to review',async()=>{const item=await fixture(2,'170.00',true),{s,order}=await buy(item),started=await startPay(s,order),valid=testPaymentAdapter.event(started);await rejected(()=>payments.applyPaymentEvent(valid.event,'invalid-signature'),'PAYMENT_SIGNATURE');assert.equal((await orders.getOrder(s,order.id)).status,'awaiting_payment');const wrong={...valid.event,amountRubles:'670.01'};assert.equal((await payments.applyPaymentEvent(wrong,security.sign(security.canonical(wrong)))).outcome,'review');assert.equal((await orders.getOrder(s,order.id)).status,'manual_review');assert.deepEqual(await state(item.skuId),{on_hand:2,reserved:1});await makeDue(order.id);await workerTick();await workerTick();assert.deepEqual(await state(item.skuId),{on_hand:2,reserved:0});assert.equal((await orders.getOrder(s,order.id)).status,'manual_review');});
  await check('failed payment can be retried and does not downgrade a completed payment',async()=>{const item=await fixture(2,'170.00',true),{s,order}=await buy(item),started=await startPay(s,order),failed=testPaymentAdapter.event(started,'failed');await payments.applyPaymentEvent(failed.event,failed.signature);assert.equal((await orders.getOrder(s,order.id)).paymentStatus,'failed');assert.deepEqual(await state(item.skuId),{on_hand:2,reserved:1});await pay(s,order);assert.deepEqual(await state(item.skuId),{on_hand:1,reserved:0});const payment=await one("SELECT id,amount_rubles FROM ar_payments WHERE order_id=$1 AND status='succeeded'",[order.id]),lateFailure=testPaymentAdapter.event({id:payment.id,amountRubles:payment.amount_rubles},'failed');await payments.applyPaymentEvent(lateFailure.event,lateFailure.signature);assert.equal((await orders.getOrder(s,order.id)).status,'paid');});
  await check('a repeated failure of payment A cannot clear pending payment B or unlock delivery',async()=>{
   const item=await fixture(2,'170.00',true),{s,order}=await buy(item);
   const paymentA=await startPay(s,order),failureA=testPaymentAdapter.event(paymentA,'failed');
   await payments.applyPaymentEvent(failureA.event,failureA.signature);
   assert.equal((await orders.getOrder(s,order.id)).paymentStatus,'failed');
   const paymentB=await startPay(s,order);
   assert.notEqual(paymentB.id,paymentA.id);
   assert.equal((await orders.getOrder(s,order.id)).paymentStatus,'pending');
   const repeatedFailureA={...failureA.event,eventId:`QA-repeat-failure-${randomUUID()}`};
   await payments.applyPaymentEvent(repeatedFailureA,security.sign(security.canonical(repeatedFailureA)));
   const pending=await orders.getOrder(s,order.id);
   assert.equal(pending.paymentStatus,'pending');
   assert.equal(pending.status,'awaiting_payment');
   await rejected(()=>shipping(pending,'890.00'),'ORDER_STATE');
   const unchanged=await orders.getOrder(s,order.id);
   assert.equal(unchanged.shippingVersion,order.shippingVersion);
   assert.equal(unchanged.shippingCostRubles,order.shippingCostRubles);
   assert.deepEqual(await state(item.skuId),{on_hand:2,reserved:1});
   const successB=testPaymentAdapter.event(paymentB);
   assert.equal((await payments.applyPaymentEvent(successB.event,successB.signature)).outcome,'paid');
   await payments.applyPaymentEvent(successB.event,successB.signature);
   const paid=await orders.getOrder(s,order.id);
   assert.equal(paid.status,'paid');assert.equal(paid.paymentStatus,'paid');
   assert.deepEqual(await state(item.skuId),{on_hand:1,reserved:0});
   assert.equal((await moves(order.id)).filter(m=>m.stock_delta===-1).length,1);
  });
  await check('ordinary cancellation and duplicate worker return a reserve exactly once',async()=>{const item=await fixture(2,'170.00',true),{s,order}=await buy(item);await cancel(s,order.id);await cancel(s,order.id);await workerTick();assert.equal((await orders.getOrder(s,order.id)).status,'cancelled');assert.deepEqual(await state(item.skuId),{on_hand:2,reserved:0});assert.equal((await moves(order.id)).filter(m=>m.reserved_delta===-1).length,1);});
  await check('ordinary expiration under concurrent workers releases once and cannot be paid',async()=>{const item=await fixture(2,'170.00',true),{s,order}=await buy(item);await makeDue(order.id);await orderRace(order.id,workerTick,workerTick);await workerTick();assert.equal((await orders.getOrder(s,order.id)).status,'expired');assert.deepEqual(await state(item.skuId),{on_hand:2,reserved:0});assert.equal((await moves(order.id)).filter(m=>m.reserved_delta===-1).length,1);await rejected(()=>startPay(s,order),'PAYMENT_CLOSED');await cancel(s,order.id);assert.equal((await orders.getOrder(s,order.id)).status,'expired');});
  await check('stock receipt is idempotent; insufficient preorder cannot confirm; confirmation debits once',async()=>{const item=await fixture(0,'170.00',true),{s,order}=await buy(item);assert.equal(order.status,'preorder_pending');assert.equal(order.expiresAt,null);assert.deepEqual(await state(item.skuId),{on_hand:0,reserved:0});await rejected(()=>confirm(order.id),'INSUFFICIENT_STOCK');const receiptKey=randomUUID();await Promise.all([receipt(item.skuId,2,receiptKey),receipt(item.skuId,2,receiptKey)]);assert.deepEqual(await state(item.skuId),{on_hand:2,reserved:0});await rejected(()=>receipt(item.skuId,3,receiptKey),'KEY_REUSED');const confirmKey=randomUUID(),confirmed=await confirm(order.id,confirmKey);await confirm(order.id,confirmKey);assert.deepEqual(await state(item.skuId),{on_hand:1,reserved:0});assert.equal(confirmed.status,'awaiting_payment');assert.ok(Math.abs(new Date(confirmed.expiresAt!).getTime()-Date.now()-1800000)<5000);await rejected(()=>confirm(order.id),'ORDER_STATE');await pay(s,confirmed);assert.deepEqual(await state(item.skuId),{on_hand:1,reserved:0});assert.equal((await moves(order.id)).filter(m=>m.stock_delta===-1).length,1);});
  await check('confirmed preorder expiration restores physical stock exactly once',async()=>{const item=await fixture(0,'170.00',true),{s,order}=await buy(item);await receipt(item.skuId,1);await confirm(order.id);assert.deepEqual(await state(item.skuId),{on_hand:0,reserved:0});await makeDue(order.id);await Promise.all([orders.expireDueOrders(),orders.expireDueOrders()]);await workerTick();assert.equal((await orders.getOrder(s,order.id)).status,'expired');assert.deepEqual(await state(item.skuId),{on_hand:1,reserved:0});assert.equal((await moves(order.id)).filter(m=>m.stock_delta===1).length,1);});
  await check('confirmed preorder cancellation restores stock once; unconfirmed cancel never moves it',async()=>{const first=await fixture(0,'170.00',true),a=await buy(first);await receipt(first.skuId,1);await confirm(a.order.id);await cancel(a.s,a.order.id);await cancel(a.s,a.order.id);assert.deepEqual(await state(first.skuId),{on_hand:1,reserved:0});assert.equal((await moves(a.order.id)).filter(m=>m.stock_delta===1).length,1);const second=await fixture(0,'170.00',true),b=await buy(second);await cancel(b.s,b.order.id);assert.equal((await moves(b.order.id)).length,0);assert.equal((await orders.getOrder(b.s,b.order.id)).status,'cancelled');});
  await check('preorder confirmation competes with a new ordinary buyer for the same last SKU',async()=>{const item=await fixture(0,'170.00',true),pre=await buy(item);await receipt(item.skuId,1);const buyer=await session();await add(buyer,item);const preview=await quote(buyer);const result=await Promise.allSettled([confirm(pre.order.id),orders.checkout(buyer,{quoteId:preview.id,cartVersion:preview.cartVersion,idempotencyKey:randomUUID()})]);assert.equal(result.filter(r=>r.status==='fulfilled').length,1);const failure=result.find(r=>r.status==='rejected') as PromiseRejectedResult;assert.ok(['INSUFFICIENT_STOCK','QUOTE_CHANGED'].includes(failure.reason.code));const balance=await state(item.skuId);assert.ok((balance.on_hand===0&&balance.reserved===0)||(balance.on_hand===1&&balance.reserved===1));const pending=await orders.getOrder(pre.s,pre.order.id);if(pending.status==='awaiting_payment')assert.equal((await orders.listOrders(buyer)).length,0);else{assert.equal(pending.status,'preorder_pending');assert.equal((await orders.listOrders(buyer)).length,1);}});
  await check('delivery cannot change while a payment is pending; stale amounts never silently update',async()=>{const item=await fixture(2,'170.00',true),{s,order}=await buy(item);await startPay(s,order);await rejected(()=>shipping(order,'890.00'),'ORDER_STATE');const unchanged=await orders.getOrder(s,order.id);assert.equal(unchanged.shippingVersion,order.shippingVersion);assert.equal(unchanged.shippingCostRubles,order.shippingCostRubles);});
  await check('late ordinary payment racing expiration cannot debit released stock',async()=>{const item=await fixture(1,'170.00',true),{s,order}=await buy(item),started=await startPay(s,order),event=testPaymentAdapter.event(started);await makeDue(order.id);await orderRace(order.id,()=>payments.applyPaymentEvent(event.event,event.signature),workerTick);await workerTick();assert.equal((await orders.getOrder(s,order.id)).status,'manual_review');assert.deepEqual(await state(item.skuId),{on_hand:1,reserved:0});assert.equal((await moves(order.id)).filter(m=>m.reserved_delta===-1).length,1);assert.equal((await moves(order.id)).filter(m=>m.stock_delta<0).length,0);});
  await check('late preorder payment racing expiration restores once and requires manual review',async()=>{const item=await fixture(0,'170.00',true),{s,order}=await buy(item);await receipt(item.skuId,1);const confirmed=await confirm(order.id),started=await startPay(s,confirmed),event=testPaymentAdapter.event(started);await makeDue(order.id);await orderRace(order.id,()=>payments.applyPaymentEvent(event.event,event.signature),workerTick);await payments.applyPaymentEvent(event.event,event.signature);await workerTick();const current=await orders.getOrder(s,order.id);assert.equal(current.status,'manual_review');assert.equal(current.paymentStatus,'review');assert.equal(current.canPay,false);assert.deepEqual(await state(item.skuId),{on_hand:1,reserved:0});assert.equal((await moves(order.id)).filter(m=>m.stock_delta===1).length,1);});
  await check('late payment after cancellation goes to review without changing available stock',async()=>{const item=await fixture(1,'170.00',true),{s,order}=await buy(item),started=await startPay(s,order),event=testPaymentAdapter.event(started);await cancel(s,order.id);await payments.applyPaymentEvent(event.event,event.signature);assert.equal((await orders.getOrder(s,order.id)).status,'manual_review');assert.deepEqual(await state(item.skuId),{on_hand:1,reserved:0});});
  await check('access: order UUID, number and unconfirmed matching email never expose another session',async()=>{const item=await fixture(1,'170.00',true),{s,order}=await buy(item),other=await session();await rejected(()=>orders.getOrder(other,order.id),'FORBIDDEN');assert.equal((await orders.listOrders(other)).length,0);await rejected(()=>orders.getOrder(other,order.number),'INVALID_ID');await rejected(()=>payments.initiatePayment(other,{orderId:order.id,shippingVersion:order.shippingVersion,method:'card',idempotencyKey:randomUUID()}),'FORBIDDEN');assert.equal((await orders.getOrder(s,order.id)).id,order.id);});
  await check('worker outbox: duplicate ticks deliver each test message once with a heartbeat',async()=>{await Promise.all([workerTick(),workerTick()]);assert.equal(Number((await one("SELECT count(*) n FROM ar_mail_outbox WHERE status='pending'")).n),0);assert.equal(Number((await one("SELECT count(*) n FROM ar_mail_outbox WHERE status='delivered' AND delivered_at IS NULL")).n),0);assert.equal(Number((await one("SELECT count(*) n FROM ar_worker_heartbeat WHERE name='commerce' AND last_error IS NULL")).n),1);});
 }catch(error){report.setupError=error instanceof Error?error.message:String(error);throw error;}finally{
  await appPool?.end();await owner?.end();
  if(created){try{assert.match(database,/^ar_qa_commerce_\d+_\d+$/);assert.notEqual(database,source);adminSql(`DROP DATABASE ${database} WITH (FORCE);`);report.cleanup=true;}catch(error){report.cleanupError=error instanceof Error?error.message:String(error);}}
  report.finishedAt=new Date().toISOString();report.passed=report.cleanup&&!report.setupError&&report.checks.length>0&&report.checks.every(check=>check.passed);mkdirSync(`${root}/artifacts/stage-4`,{recursive:true});writeFileSync(`${root}/artifacts/stage-4/commerce-check.json`,JSON.stringify(report,null,2)+'\n');assert.equal(report.cleanup,true,'Temporary commerce QA database must be removed');
 }
});
