import test from 'node:test';
import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import {readFileSync,mkdirSync,writeFileSync} from 'node:fs';
import {randomBytes,randomUUID} from 'node:crypto';
import pg from 'pg';

test('content publication, aliases and media in isolated PostgreSQL',{skip:process.env.AR_CONTENT_TESTS!=='1',timeout:60000},async t=>{
 const env=Object.fromEntries(readFileSync('.env','utf8').split(/\r?\n/).filter(l=>l&&!l.startsWith('#')&&l.includes('=')).map(l=>{const i=l.indexOf('=');return[l.slice(0,i),l.slice(i+1)];}));assert.equal(env.POSTGRES_DB,'autoreelz2026_new');assert.equal(env.COMPOSE_PROJECT_NAME,'autoreelz2026-new');
 const database=`ar_qa_content_${process.pid}_${Date.now()}`,compose=['compose','-p','autoreelz2026-new','exec','-T','db'];assert.match(database,/^ar_qa_content_\d+_\d+$/);
 const execute=(args:string[],input?:string)=>{const r=spawnSync('docker',args,{input,encoding:'utf8',timeout:30000,maxBuffer:128*1024*1024});if(r.status!==0)throw new Error(r.stderr||'Content QA command failed');return r.stdout;};
 const sql=(statement:string,db:string)=>{assert.ok(db===database||db==='autoreelz2026_new');return execute([...compose,'psql','-X','-q','-v','ON_ERROR_STOP=1','-U','ar_migrator','-d',db],statement);};
 const dump=execute([...compose,'pg_dump','-U','ar_migrator','-d','autoreelz2026_new','--no-password']);sql(`CREATE DATABASE ${database};`,'autoreelz2026_new');
 process.env.AR_DATABASE_NAME=database;process.env.AR_DB_HOST='127.0.0.1';process.env.AR_DB_PORT=env.DB_PORT||'65432';process.env.APP_DB_PASSWORD=env.APP_DB_PASSWORD;process.env.APP_SECRET=randomBytes(48).toString('hex');
 const owner=new pg.Pool({host:'127.0.0.1',port:Number(env.DB_PORT||65432),database,user:'ar_migrator',password:env.POSTGRES_PASSWORD});
 const db=await import('../src/server/db.ts'),{getContent,isPublishedArticleMedia}=await import('../src/server/content.ts'),{resolveContent}=await import('../src/lib/content.ts');
 const report:{database:string;checks:{name:string;passed:boolean}[];cleanup:boolean;passed?:boolean}={database,checks:[],cleanup:false};
 t.after(async()=>{await db.getPool().end();await owner.end();sql(`DROP DATABASE IF EXISTS ${database} WITH (FORCE);`,'autoreelz2026_new');report.cleanup=true;report.passed=report.checks.every(c=>c.passed)&&report.checks.length>=7;mkdirSync('artifacts/stage-5',{recursive:true});writeFileSync('artifacts/stage-5/content-check.json',JSON.stringify(report,null,2));});
 sql(dump,database);
 async function check(name:string,fn:()=>Promise<void>){await t.test(name,async()=>{try{await fn();report.checks.push({name,passed:true});}catch(error){report.checks.push({name,passed:false});throw error;}});}
 const categoryId=randomUUID(),articleId=randomUUID(),pageId=randomUUID(),tagId=randomUUID(),cover=randomUUID();
 await owner.query("INSERT INTO ar_blog_categories(id,name,slug,status) VALUES($1,'QA Content','qa-content','published')",[categoryId]);
 await owner.query("INSERT INTO ar_articles(id,title,slug,category_id,status,body,cover_file_id) VALUES($1,'QA Article','qa-article',$2,'draft',$3,$4)",[articleId,categoryId,'Текст\n\n<script>window.qaContentXss=1</script>',cover]);
 await owner.query("INSERT INTO ar_pages(id,title,slug,status,is_legal,is_draft_text) VALUES($1,'QA Page','qa-page','draft',true,true)",[pageId]);
 await owner.query("INSERT INTO ar_blog_tags(id,name,slug) VALUES($1,'QA Tag','qa-tag')",[tagId]);await owner.query('INSERT INTO ar_article_tags(article_id,tag_id) VALUES($1,$2)',[articleId,tagId]);
 await check('draft pages/articles and their tag associations are absent from the public snapshot',async()=>{const c=await getContent();assert.ok(!c.pages.some(p=>p.id===pageId));assert.ok(!c.articles.some(a=>a.id===articleId));assert.ok(!c.tags.some(tag=>tag.id===tagId));assert.equal(await isPublishedArticleMedia(cover),false);});
 await check('publishing takes effect on a fresh request with plain text and legal draft flag preserved',async()=>{await owner.query("UPDATE ar_pages SET status='published' WHERE id=$1",[pageId]);await owner.query("UPDATE ar_articles SET status='published' WHERE id=$1",[articleId]);const c=await getContent(),article=c.articles.find(a=>a.id===articleId)!;assert.ok(article);assert.ok(article.body.includes('<script>'));assert.equal(article.tags[0]?.id,tagId);assert.ok(c.pages.find(p=>p.id===pageId)?.isDraftText);assert.equal(await isPublishedArticleMedia(cover),true);});
 await check('unpublished parent hides article, its tags and its cover',async()=>{await owner.query("UPDATE ar_blog_categories SET status='draft' WHERE id=$1",[categoryId]);const c=await getContent();assert.ok(!c.articles.some(a=>a.id===articleId));assert.ok(!c.tags.some(tag=>tag.id===tagId));assert.equal(await isPublishedArticleMedia(cover),false);await owner.query("UPDATE ar_blog_categories SET status='published' WHERE id=$1",[categoryId]);});
 await check('future publication does not leak article or cover before its date',async()=>{await owner.query("UPDATE ar_articles SET published_at=now()+interval '1 day' WHERE id=$1",[articleId]);assert.ok(!(await getContent()).articles.some(a=>a.id===articleId));assert.equal(await isPublishedArticleMedia(cover),false);await owner.query('UPDATE ar_articles SET published_at=NULL WHERE id=$1',[articleId]);});
 await check('old content addresses redirect to current published addresses and remain claimed',async()=>{await owner.query("UPDATE ar_articles SET slug='qa-renamed' WHERE id=$1",[articleId]);assert.deepEqual(resolveContent(await getContent(),'article','qa-article'),{id:articleId,slug:'qa-renamed',redirect:true});await assert.rejects(owner.query("INSERT INTO ar_articles(title,slug,category_id) VALUES('QA Collision','qa-article',$1)",[categoryId]),/Адрес уже использован/);await owner.query("UPDATE ar_articles SET status='draft' WHERE id=$1",[articleId]);assert.equal(resolveContent(await getContent(),'article','qa-article'),null);await owner.query("UPDATE ar_articles SET status='published' WHERE id=$1",[articleId]);});
 await check('only normalized supported video URLs reach public DTOs',async()=>{await owner.query("UPDATE ar_articles SET video_url='javascript:alert(1)' WHERE id=$1",[articleId]);let article=(await getContent()).articles.find(a=>a.id===articleId)!;assert.equal(article.video,null);assert.equal(article.invalidVideo,true);await owner.query("UPDATE ar_articles SET video_url='https://vkvideo.ru/video_ext.php?oid=-123&id=456&hash=abcd1234&autoplay=1' WHERE id=$1",[articleId]);article=(await getContent()).articles.find(a=>a.id===articleId)!;assert.equal(article.video?.embedUrl,'https://vkvideo.ru/video_ext.php?oid=-123&id=456&hash=abcd1234&autoplay=0');});
 await check('public SQL role remains read-only for content; existing article/category foreign keys remain enforced',async()=>{await assert.rejects(db.query("UPDATE ar_articles SET title='changed' WHERE id=$1",[articleId]),/permission denied/);await assert.rejects(owner.query('UPDATE ar_articles SET category_id=$1 WHERE id=$2',[randomUUID(),articleId]),/foreign key/);});
});
