import {test} from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {contentHtml,safeRichHtml,contentImageIds,previewContentHtml,richContentText} from '../src/server/rich-content.ts';import {normalizeContent} from '../src/server/content-editor.ts';import {emptyContent} from '../src/lib/content-editor.ts';
test('legacy page/article content remains escaped, with existing headings, URLs and line breaks',()=>{const input='## Заголовок\n\nТекст <script>alert(1)</script>\nСтрока https://auto.ru/test';const article=contentHtml(input,'plain','article');assert.ok(article.includes('<h2>Заголовок</h2>'));assert.ok(article.includes('&lt;script&gt;'));assert.ok(article.includes('<br>'));assert.ok(article.includes('href="https://auto.ru/test"'));assert.ok(contentHtml(input,'plain','page').startsWith('<p>## Заголовок</p>'));});
test('rich content allows formatting but rejects scripts, handlers, unsafe links, CSS, embeds and remote images',()=>{const id=randomUUID();const html=safeRichHtml(`<h2>Название</h2><p class="ql-align-center evil" style="text-align:center;color:red;position:fixed" onclick="bad()"><strong>Текст</strong></p><script>alert(1)</script><svg onload="alert(2)"><text>SVG</text></svg><iframe src="https://evil.invalid"></iframe><a href="jav&#x61;script:alert(3)">Ссылка</a><a href="//evil.invalid">Другая</a><img src="https://evil.invalid/x.png"><img src="data:image/png,x"><img src="/media/${id}" alt="Описание &quot; тест" width="50%" onerror="bad()">`);assert.ok(html.includes('ql-align-center'));assert.ok(html.includes('<strong>Текст</strong>'));assert.ok(html.includes('width="50%"'));for(const word of ['onclick','onerror','<script','<iframe','<svg','javascript:','evil.invalid','position:','color:','data:image'])assert.equal(html.includes(word),false,word);assert.deepEqual(contentImageIds(html),[id]);assert.ok(previewContentHtml(html).includes('/api/manager/product-image?id='+id));});
test('Quill image URLs normalize to public UUID paths, preserving alt and size without allowing attribute injection',()=>{const id=randomUUID();const html=safeRichHtml(`<img src="/api/manager/product-image?id=${id}" alt="&quot; onerror=&quot;alert(1)" width="99"/><a href='https://example.test/&quot; onclick=&quot;bad()'>link</a>`);assert.ok(html.includes('/media/'+id));assert.ok(html.includes('alt="&quot; onerror=&quot;alert(1)"'));assert.equal(/\swidth=/.test(html),false);assert.equal(html.includes('<script'),false);assert.equal(safeRichHtml('<img src="/media/not-an-id">'),'');});
test('normalization preserves complete fields and bounds rich content, taxonomy and dates',()=>{const value={...emptyContent(),title:'Тест',body:'<p>Текст</p>',tagIds:[randomUUID()],publishedAt:'2026-10-03T12:00:00+03:00',videoDuration:'20',isLegal:true,isDraftText:true};const data=normalizeContent(value);assert.equal(data.publishedAt,'2026-10-03T09:00:00.000Z');assert.equal(data.isDraftText,true);assert.throws(()=>normalizeContent({...value,body:'x'.repeat(100001)}));assert.throws(()=>normalizeContent({...value,tagIds:[value.tagIds[0],value.tagIds[0]]}));for(const publishedAt of ['invalid','2026-02-31T10:00:00Z','0000-01-01T00:00:00Z'])assert.throws(()=>normalizeContent({...value,publishedAt}));assert.throws(()=>normalizeContent({...value,videoDuration:'0'}));});
test('home/SEO plain excerpts do not expose HTML or encoded entities',()=>{assert.equal(richContentText('<h2>О нас</h2><p>Текст &amp; детали<br>Строка</p>'),'О нас\n\nТекст & детали\n\nСтрока');});

test('only actual image nodes claim media, not escaped markup or image-like text',()=>{const id=randomUUID();for(const text of [`<p>src="/media/${id}"</p>`,`<p>&lt;img src="/media/${id}"&gt;</p>`,`<script><img src="/media/${id}"></script>`])assert.deepEqual(contentImageIds(text),[]);});
