import fs from 'node:fs';import assert from 'node:assert/strict';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'/Users/magomedrasul/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs');
const base=process.env.AR_DASHBOARD_URL||'http://127.0.0.1:14331',out=process.env.AR_DASHBOARD_OUTPUT||'artifacts/dashboard/browser';fs.mkdirSync(out,{recursive:true});
const report={base,fixtureData:true,checks:[],viewports:[],passed:false};
function fixture(period='7',filter='all'){
 const now=new Date(),days=period==='today'?1:Number(period),sum=period==='today'?'100.00':period==='30'?'9000.00':'3800.50';
 const series=Array.from({length:days},(_,i)=>({day:new Date(now.getTime()-(days-1-i)*86400000).toISOString().slice(0,10),productRubles:i===days-1?sum:'0.00',shippingRubles:i===days-1?'500.10':'0.00',orders:i===days-1?2:0}));
 const orders=[{id:'00000000-0000-4000-8000-000000000001',number:'QA-1048',kind:'ordinary',status:'paid',paymentStatus:'paid',deliveryStatus:'quoted',createdAt:now.toISOString(),productTotalRubles:'1800.00',shippingCostRubles:'200.00'},{id:'00000000-0000-4000-8000-000000000002',number:'QA-1047',kind:'preorder',status:'preorder_pending',paymentStatus:'unpaid',deliveryStatus:'pending_quote',createdAt:now.toISOString(),productTotalRubles:'2000.50',shippingCostRubles:null}].filter(o=>filter==='all'||filter===o.kind||filter==='packing'&&o.status==='paid'||['quote','confirm'].includes(filter)&&o.kind==='preorder');
 return{generatedAt:now.toISOString(),period,filter,from:series[0].day+'T00:00:00Z',testOnly:true,metrics:{productRubles:sum,shippingRubles:'500.10',paidOrders:2,averageRubles:period==='today'?'50.00':period==='30'?'4500.00':'1900.25',ordinary:1,preorder:1,inWork:7},series,tasks:{packing:3,quote:2,confirm:1,review:0,reviews:2},orders,orderCount:orders.length,stock:[{skuId:'30000000-0000-4000-8000-000000000001',productId:'20000000-0000-4000-8000-000000000001',article:'QA-GREEN',name:'Зелёная подсветка',productName:'QA Блок отопителя',status:'published',onHand:5,reserved:3,available:2},{skuId:'30000000-0000-4000-8000-000000000002',productId:'20000000-0000-4000-8000-000000000002',article:'QA-CONSOLE',name:'Матовая',productName:'QA Консоль',status:'published',onHand:12,reserved:2,available:10}],quality:[{id:'20000000-0000-4000-8000-000000000002',name:'QA Консоль',status:'published',issues:['Нет упаковки','Совместимость не подтверждена']}],bundles:[{id:'20000000-0000-4000-8000-000000000003',name:'QA Комплект интерьера',available:1}]};
}
const browser=await chromium.launch({channel:'chrome',headless:true});
try{
 for(const width of [1440,768,375]){
  const context=await browser.newContext({viewport:{width,height:1000}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));let gate=401,fail=false,requests=0,delay=false;await page.clock.install();
  await page.route('**/api/manager/dashboard?**',async route=>{requests++;if(gate!==200)return route.fulfill({status:gate,json:{error:{message:gate===403?'Нет прав на торговые операции.':'Войдите в кабинет.'}}});if(fail)return route.fulfill({status:503,json:{error:{message:'Проверочный сбой обновления.'}}});const u=new URL(route.request().url());if(delay&&u.searchParams.get('period')==='today')await new Promise(r=>setTimeout(r,500));return route.fulfill({json:fixture(u.searchParams.get('period'),u.searchParams.get('filter'))}).catch(()=>{});});
  await page.route('**/api/manager/logout',async route=>{gate=401;return route.fulfill({json:{ok:true}});});
  await page.route('**/api/manager/login',async route=>{gate=200;return route.fulfill({json:{ok:true}});});
  assert.equal((await page.goto(base+'/manager',{waitUntil:'networkidle'})).status(),200);assert.equal(await page.locator('[data-dash-content]').isVisible(),false);assert.equal(await page.locator('[data-dash-login]').isVisible(),true);
  await page.locator('[data-dash-login-form] [name=email]').fill('qa-owner@example.invalid');await page.locator('[data-dash-login-form] [name=password]').fill('QA-only-not-a-real-password');await page.locator('[data-dash-login-form] button').click();await page.locator('[data-dash-content]').waitFor({state:'visible'});assert.equal(await page.locator('[name=password]').inputValue(),'');
  assert.match(await page.locator('[data-kpi=products]').innerText(),/3.*800,50/);await page.locator('[data-task=packing]').click();await page.waitForFunction(()=>document.querySelector('[data-list-title]').textContent.includes('ждут сборки'));assert.equal(await page.locator('[data-orders] tr').count(),1);assert.match(await page.locator('[data-orders] a').getAttribute('href'),/\/manager\/orders\?order=/);
  await page.locator('[data-threshold]').selectOption('20');assert.equal(await page.locator('[data-stock] tr').count(),2);await page.locator('[data-stock-search]').fill('QA-CONSOLE');assert.equal(await page.locator('[data-stock] tr').count(),1);await page.locator('[data-stock-search]').fill('');
  delay=true;await page.locator('[data-period]').selectOption('today');await page.locator('[data-period]').selectOption('30');await page.waitForFunction(()=>document.querySelector('[data-kpi=products]').textContent.includes('9'));await page.waitForTimeout(650);assert.match(await page.locator('[data-kpi=products]').innerText(),/9.*000/);delay=false;
  fail=true;await page.locator('[data-refresh]').click();await page.locator('[data-dash-error]').waitFor({state:'visible'});assert.match(await page.locator('[data-dash-error]').innerText(),/последнего успешного/);assert.match(await page.locator('[data-kpi=products]').innerText(),/9.*000/);fail=false;
  await page.locator('[data-refresh]').click();await page.locator('[data-dash-error]').waitFor({state:'hidden'});
  const before=requests;await page.clock.fastForward(61000);await page.waitForFunction(()=>!document.querySelector('[data-refresh]').disabled);assert.ok(requests>before,'Auto refresh');assert.equal(await page.locator('[data-period]').inputValue(),'30');assert.equal(await page.locator('[data-threshold]').inputValue(),'20');
  await page.reload({waitUntil:'networkidle'});assert.equal(await page.locator('[data-period]').inputValue(),'30');assert.equal(await page.locator('[data-threshold]').inputValue(),'20');assert.match(await page.locator('[data-list-title]').innerText(),/ждут сборки/);
  await page.locator('[data-period]').selectOption('7');await page.locator('[data-filter=all]').click();await page.locator('[data-threshold]').selectOption('3');await page.waitForFunction(()=>document.querySelectorAll('[data-orders] tr').length===2);await page.evaluate(()=>document.activeElement?.blur());
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);assert.deepEqual(await page.locator('img').evaluateAll(imgs=>imgs.filter(img=>!img.complete||img.naturalWidth===0).map(img=>img.src)),[]);
  await page.screenshot({path:`${out}/dashboard-${width}.png`,fullPage:true});
  assert.equal(await page.getByRole('link',{name:'Открыть CMS',exact:true}).getAttribute('href'),'/cms/admin');
  await page.locator('[data-staff-logout]').click();await page.waitForURL('**/manager?logged_out=1');await page.locator('[data-dash-login]').waitFor({state:'visible'});assert.equal(await page.locator('[data-dash-content]').isVisible(),false);
  await page.locator('[name=email]').fill('qa-owner@example.invalid');await page.locator('[name=password]').fill('QA-only-not-a-real-password');await page.locator('[data-dash-login-form] button').click();await page.locator('[data-dash-content]').waitFor({state:'visible'});
  gate=403;await page.locator('[data-refresh]').click();await page.locator('[data-dash-login]').waitFor({state:'visible'});assert.equal(await page.locator('[data-dash-content]').isVisible(),false);assert.equal(await page.locator('[data-orders] tr').count(),0);assert.deepEqual(errors,[]);if(width===1440){const items=fixture().stock;await page.route('**/api/manager/orders*',route=>route.fulfill({json:{orders:[]}}));await page.route('**/api/manager/stock',route=>route.fulfill({json:{items}}));await page.goto(base+'/manager/orders?sku='+items[0].skuId+'#manager-stock-adjust',{waitUntil:'networkidle'});assert.equal(await page.locator('[data-adjust-stock-select]').inputValue(),items[0].skuId);await page.locator('[data-adjust-stock-select]').selectOption(items[1].skuId);await page.locator('[data-reload-manager]').click();await page.waitForTimeout(300);assert.equal(await page.locator('[data-adjust-stock-select]').inputValue(),items[1].skuId);assert.equal(await page.getByRole('link',{name:'Открыть CMS',exact:true}).getAttribute('href'),'/cms/admin');assert.equal(await page.locator('[data-staff-logout]').count(),1);}
  report.viewports.push({width,passed:true,errors});await context.close();
 }
 report.checks=['login/401/403 and data hidden','order task deep link','stock threshold and search','stale responses ignored','failed refresh retains previous metrics','automatic refresh and filter persistence','reload preferences','responsive layout and logo','CMS points to server path','logout hides data and returns to login','stock deep link applied once; later selection preserved'];report.passed=true;
}finally{await browser.close();fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2));}
console.log(JSON.stringify(report));
