import {testOrderTerms} from '../src/lib/checkout-confirmations.ts';
import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdirSync,writeFileSync} from 'node:fs';
import {qaDatabase} from './helpers/qa-db.mjs';

test('stage 5 management in isolated PostgreSQL',{skip:process.env.AR_STAGE5_TESTS!=='1',timeout:120000},async t=>{
 const db=await qaDatabase('management'),q=db.query,report={checks:[] as {name:string;passed:boolean}[],cleanup:false,passed:false};
 const cart=await import('../src/server/cart.ts'),orders=await import('../src/server/orders.ts'),payments=await import('../src/server/payments.ts'),ops=await import('../src/server/management.ts'),gen=await import('../src/server/description-generation.ts'),notices=await import('../src/server/notifications.ts'),security=await import('../src/server/security.ts'),{query,getPool}=await import('../src/server/db.ts');
 const actor={id:randomUUID()},other={id:randomUUID()},key=()=>randomUUID();
 const check=async(name:string,fn:()=>Promise<void>)=>{await t.test(name,async()=>{await fn();report.checks.push({name,passed:true});});};
 const rejected=async(fn:()=>Promise<any>,code:string)=>assert.rejects(fn,(e:any)=>e.code===code);
 async function fixture(stock=5){
  const productId=key(),skuId=key(),pack=key();const cat=(await q('SELECT id FROM ar_categories ORDER BY id LIMIT 1')).rows[0].id;
  await q("INSERT INTO ar_products(id,name,slug,category_id,status,description,meta_description,seo_title,is_demo) VALUES($1,'QA товар',$2,$3,'published','Исходное описание товара','Исходная мета-информация','Ручной title',true)",[productId,'qa-stage5-'+productId,cat]);
  await q("INSERT INTO ar_packages(id,name,weight_g,length_mm,width_mm,height_mm) VALUES($1,'QA тестовая коробка',100,100,100,100)",[pack]);
  await q("INSERT INTO ar_skus(id,product_id,article,name,price_rubles,status,package_id) VALUES($1,$2,$3,'QA исполнение','100.10','published',$4)",[skuId,productId,'QA-'+skuId,pack]);
  await q('INSERT INTO ar_stock(sku_id,on_hand) VALUES($1,$2)',[skuId,stock]);return{productId,skuId};
 }
 async function buy(paid=false){
  const f=await fixture(),sid=key(),s={id:sid,csrfToken:key(),email:null,expiresAt:new Date(Date.now()+3600000).toISOString()};
  await q("INSERT INTO ar_web_sessions(id,token_hash,csrf_token,expires_at) VALUES($1,$2,$3,now()+interval '1 hour')",[sid,key(),s.csrfToken]);
  const c=await cart.changeCart(s,{...f,quantity:1,mode:'add',cartVersion:0,idempotencyKey:key()});
  const quote=await cart.createQuote(s,{cartVersion:c.version,customer:{name:'QA Покупатель',email:'qa-'+sid+'@example.invalid',phone:'+79990000000'},delivery:{method:'pickup_point',city:'QA Москва',address:'QA адрес проверки'}});
  let order=(await orders.checkout(s,{confirmation:{accepted:true,version:testOrderTerms.version},quoteId:quote.id,cartVersion:c.version,idempotencyKey:key()})).orders[0];
  if(paid)order=await payments.payOrder(s,{orderId:order.id,shippingVersion:order.shippingVersion,method:'card',idempotencyKey:key()});
  return{...f,s,order};
 }
 const state=async(id:string)=>(await q('SELECT on_hand,reserved FROM ar_stock WHERE sku_id=$1',[id])).rows[0];
 const carrier=(orderId:string,status:'packing'|'shipped'|'delivered',at=Date.now(),trackingNumber='QA-TRACK')=>({eventId:'qa-'+key(),orderId,status,occurredAt:new Date(at).toISOString(),trackingNumber});
 const apply=(e:ops.CarrierEvent)=>ops.applyCarrierEvent(e,security.sign('delivery:'+security.canonical(e)));
 try{
  await check('stock adjustments preserve reservations and deduplicate',async()=>{const f=await buy();await rejected(()=>ops.adjustStock(actor,{skuId:f.skuId,onHand:0,reason:'QA причина',idempotencyKey:key()}),'RESERVED_STOCK');const body={skuId:f.skuId,onHand:8,reason:'QA инвентаризация',idempotencyKey:key()};await ops.adjustStock(actor,body);await ops.adjustStock(actor,body);assert.deepEqual(await state(f.skuId),{on_hand:8,reserved:1});assert.equal((await q("SELECT count(*)::int n FROM ar_stock_movements WHERE sku_id=$1 AND operation_key LIKE 'adjust:%'",[f.skuId])).rows[0].n,1);await rejected(()=>ops.adjustStock(actor,{...body,onHand:9}),'KEY_REUSED');});
  await check('internal notes are idempotent and absent from the buyer response',async()=>{const f=await buy(),body={orderId:f.order.id,note:'Секретная внутренняя заметка QA\nВторая строка',idempotencyKey:key()};await ops.addNote(actor,body);const view=await ops.addNote(actor,body);assert.equal(view.notes.length,1);assert.equal(view.notes[0].body,body.note);assert.ok(!JSON.stringify(await orders.getOrder(f.s,f.order.id)).includes(body.note));});
  await check('manager cancellation releases unpaid stock once and rejects paid cancellation',async()=>{const f=await buy(),body={orderId:f.order.id,reason:'QA отмена покупателем',idempotencyKey:key()};await ops.cancelByManager(actor,body);await ops.cancelByManager(actor,body);assert.deepEqual(await state(f.skuId),{on_hand:5,reserved:0});const paid=await buy(true);await rejected(()=>ops.cancelByManager(actor,{...body,orderId:paid.order.id,idempotencyKey:key()}),'REFUND_REQUIRED');});
  await check('fulfillment requires payment, sequence and tracking, records delivered receipt',async()=>{const unpaid=await buy();await rejected(()=>ops.fulfill(actor,{orderId:unpaid.order.id,status:'packing',reason:'QA сборка',idempotencyKey:key()}),'PAYMENT_REQUIRED');const f=await buy(true);await rejected(()=>ops.fulfill(actor,{orderId:f.order.id,status:'shipped',trackingNumber:'QA-123',reason:'QA',idempotencyKey:key()}),'DELIVERY_SEQUENCE');await ops.fulfill(actor,{orderId:f.order.id,status:'packing',reason:'QA сборка',idempotencyKey:key()});await rejected(()=>ops.fulfill(actor,{orderId:f.order.id,status:'shipped',reason:'QA отправка',idempotencyKey:key()}),'TRACKING_REQUIRED');for(const status of ['shipped','delivered'])await ops.fulfill(actor,{orderId:f.order.id,status,trackingNumber:'QA-123',reason:'QA подтверждение',idempotencyKey:key()});const view=await ops.managerOrder(f.order.id);assert.ok(view.deliveredAt);assert.equal(view.deliverySource,'manager');assert.equal(view.deliveryOverride,true);assert.equal(view.trackingNumber,'QA-123');});
  await check('carrier events cannot overwrite manual status and retain tracking for resuming',async()=>{const f=await buy(true);await ops.fulfill(actor,{orderId:f.order.id,status:'packing',reason:'QA сборка',idempotencyKey:key()});const e=carrier(f.order.id,'shipped');assert.equal((await apply(e)).applied,false);let view=await ops.managerOrder(f.order.id);assert.equal(view.deliveryStatus,'packing');assert.equal(view.deliveryEvents.at(-1)?.source,'carrier');view=await ops.overrideDelivery(actor,{orderId:f.order.id,status:null,reason:'QA вернуться к перевозчику',idempotencyKey:key()});assert.equal(view.deliveryStatus,'shipped');assert.equal(view.trackingNumber,'QA-TRACK');assert.equal(view.deliveryOverride,false);assert.equal(view.deliverySource,'carrier');});
  await check('signed carrier event duplicate is safe and changed payload is rejected',async()=>{const f=await buy(true),e=carrier(f.order.id,'shipped');await rejected(()=>ops.applyCarrierEvent(e,'invalid'),'DELIVERY_SIGNATURE');assert.equal((await apply(e)).applied,true);assert.equal((await apply(e)).duplicate,true);await rejected(()=>apply({...e,status:'delivered'}),'EVENT_REUSED');assert.equal((await q('SELECT count(*)::int n FROM ar_delivery_events WHERE provider_event_id=$1',[e.eventId])).rows[0].n,1);});
  await check('older, regressive, unpaid and future carrier events cannot change delivery',async()=>{const f=await buy(true);await apply(carrier(f.order.id,'delivered',Date.now()+1000));await apply(carrier(f.order.id,'shipped',Date.now()+2000));await apply(carrier(f.order.id,'packing',Date.now()-1000));assert.equal((await ops.managerOrder(f.order.id)).deliveryStatus,'delivered');await rejected(()=>apply(carrier(f.order.id,'delivered',Date.now()+600000)),'EVENT_TIME');const unpaid=await buy();assert.equal((await apply(carrier(unpaid.order.id,'delivered'))).applied,false);assert.equal((await ops.managerOrder(unpaid.order.id)).deliveredAt,null);});
  await check('carrier simulator protects the manager command key',async()=>{const f=await buy(true),body={orderId:f.order.id,status:'shipped',trackingNumber:'QA-123',occurredAt:new Date().toISOString(),providerEventId:key(),idempotencyKey:key()};await ops.simulateCarrier(actor,body);await ops.simulateCarrier(actor,body);await rejected(()=>ops.simulateCarrier(actor,{...body,status:'delivered'}),'KEY_REUSED');});
  await check('generation preview and provider errors preserve both current texts and manual title',async()=>{const f=await fixture(),original=(await q('SELECT description,meta_description,seo_title FROM ar_products WHERE id=$1',[f.productId])).rows[0];const d=await gen.generateDescription(actor,{productId:f.productId,idempotencyKey:key()});assert.equal(d.state,'preview');assert.deepEqual((await q('SELECT description,meta_description,seo_title FROM ar_products WHERE id=$1',[f.productId])).rows[0],original);await rejected(()=>gen.generateDescription(actor,{productId:f.productId,simulateFailure:true,idempotencyKey:key()}),'GENERATOR_UNAVAILABLE');assert.deepEqual((await q('SELECT description,meta_description,seo_title FROM ar_products WHERE id=$1',[f.productId])).rows[0],original);});
  await check('apply changes exactly two text fields and is idempotent',async()=>{const f=await fixture(),d=await gen.generateDescription(actor,{productId:f.productId,idempotencyKey:key()}),body={draftId:d.id,description:'Отредактированное описание проверенного товара',metaDescription:'Отдельная мета-информация для проверки',idempotencyKey:key()};const applied=await gen.applyDescription(actor,body);assert.equal(applied.product.description,body.description);assert.equal(applied.product.metaDescription,body.metaDescription);assert.equal(applied.product.seoTitle,'Ручной title');assert.deepEqual(await gen.applyDescription(actor,body),applied);});
  await check('concurrent CMS edit and another actor cannot be overwritten with a draft',async()=>{const f=await fixture(),d=await gen.generateDescription(actor,{productId:f.productId,idempotencyKey:key()}),body={draftId:d.id,description:'QA новое описание товара',metaDescription:'QA новая мета-информация товара',idempotencyKey:key()};await rejected(()=>gen.applyDescription(other,body),'NOT_FOUND');await q("UPDATE ar_products SET description='Новая правка из CMS' WHERE id=$1",[f.productId]);await rejected(()=>gen.applyDescription(actor,body),'PRODUCT_CHANGED');assert.equal((await q('SELECT description FROM ar_products WHERE id=$1',[f.productId])).rows[0].description,'Новая правка из CMS');});
  await check('store SQL role cannot overwrite SEO title',async()=>{const f=await fixture();await assert.rejects(()=>query("UPDATE ar_products SET seo_title='wrong' WHERE id=$1",[f.productId]),(e:any)=>e.code==='42501');});
  await check('owner MAX/email outbox is local and duplicate delivery does not repeat',async()=>{const f=await buy(true);const rows=(await q('SELECT * FROM ar_owner_notifications WHERE order_id=$1',[f.order.id])).rows;assert.equal(rows.length,4);await notices.deliverOwnerNotifications();await notices.deliverOwnerNotifications();const sent=(await q('SELECT status,attempts FROM ar_owner_notifications WHERE order_id=$1',[f.order.id])).rows;assert.ok(sent.every(x=>x.status==='delivered'&&x.attempts===1));});
  await check('notification failure and repeated retry preserve one outbox item',async()=>{const f=await buy();await notices.deliverOwnerNotifications(true);const item=(await q('SELECT * FROM ar_owner_notifications WHERE order_id=$1 LIMIT 1',[f.order.id])).rows[0];assert.equal(item.status,'failed');const body={notificationId:item.id,idempotencyKey:key()};await notices.retryNotification(actor,body);await notices.retryNotification(actor,body);await notices.deliverOwnerNotifications();const after=(await q('SELECT * FROM ar_owner_notifications WHERE id=$1',[item.id])).rows[0];assert.equal(after.status,'delivered');assert.equal(after.attempts,2);});
  await check('unmodified multi-paragraph generator output can be applied',async()=>{const f=await fixture(),d=await gen.generateDescription(actor,{productId:f.productId,idempotencyKey:key()});assert.ok(d.description.includes('\n'));const result=await gen.applyDescription(actor,{draftId:d.id,description:d.description,metaDescription:d.metaDescription,idempotencyKey:key()});assert.equal(result.product.description,d.description);assert.equal(result.product.seoTitle,'Ручной title');});
  await check('a completed generation retry bypasses quota without generating twice',async()=>{const limited={id:key()},f=await fixture(),body={productId:f.productId,idempotencyKey:key()},draft=await gen.generateDescription(limited,body);await q('UPDATE ar_rate_limits SET count=20 WHERE key=$1',[security.sign('description:'+limited.id)]);assert.deepEqual(await gen.generateDescription(limited,body),draft);await rejected(()=>gen.generateDescription(limited,{...body,idempotencyKey:key()}),'RATE_LIMIT');});
  report.passed=report.checks.length===16;
 }finally{await getPool().end();await db.close();report.cleanup=true;mkdirSync('artifacts/stage-5',{recursive:true});writeFileSync('artifacts/stage-5/management-check.json',JSON.stringify(report,null,2)+'\n');}
});
