import {testOrderTerms} from '../src/lib/checkout-confirmations.ts';
/** Stage 5 owner acceptance. Real HTTP and browser UI, writes only in a unique QA clone. */
import assert from 'node:assert/strict';
import {spawn,spawnSync} from 'node:child_process';
import {createRequire} from 'node:module';
import {readFileSync,mkdirSync,writeFileSync,existsSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {basename,join} from 'node:path';
import {randomBytes,randomUUID} from 'node:crypto';
import pg from 'pg';
import sharp from 'sharp';
const root=fileURLToPath(new URL('..',import.meta.url));process.chdir(root);
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||(process.env.HOME+'/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
const env=Object.fromEntries(readFileSync('.env','utf8').split(/\r?\n/).filter(line=>line&&!line.startsWith('#')&&line.includes('=')).map(line=>{const at=line.indexOf('=');return[line.slice(0,at),line.slice(at+1)];}));
const source='autoreelz2026_new',project='autoreelz2026-new',base='http://127.0.0.1:14326';assert.equal(env.POSTGRES_DB,source);assert.equal(env.COMPOSE_PROJECT_NAME,project);
const database=`ar_qa_owner_${process.pid}_${Date.now()}`;assert.match(database,/^ar_qa_owner_\d+_\d+$/);
const output='artifacts/stage-5',privateDir=`tmp/stage-5/${database}`,uploads=join(root,privateDir,'uploads');mkdirSync(output,{recursive:true});mkdirSync(uploads,{recursive:true});
const report={database,source,startedAt:new Date().toISOString(),browser:'Chrome headless, real HTTP, no API interception',checks:[],screenshots:[],consoleErrors:[],cleanup:false,passed:false};
const secrets=[env.ADMIN_EMAIL,env.ADMIN_PASSWORD,env.EDITOR_EMAIL,env.EDITOR_PASSWORD,env.APP_DB_PASSWORD,env.POSTGRES_PASSWORD].filter(Boolean);
const scrub=value=>{let result=String(value);for(const secret of secrets)result=result.replaceAll(secret,'[redacted]');return result;};
const compose=['compose','-p',project,'exec','-T','db'];let created=false,browser,owner;const children=[],logs={};
const execute=(args,input)=>{const result=spawnSync('docker',args,{cwd:root,input,encoding:'utf8',timeout:30000,maxBuffer:128*1024*1024});if(result.error)throw result.error;if(result.status!==0)throw new Error(scrub(result.stderr||'QA Docker command failed'));return result.stdout;};
const admin=(sql,db=source)=>{assert.ok(db===database||db===source);return execute([...compose,'psql','-X','-q','-v','ON_ERROR_STOP=1','-U','ar_migrator','-d',db],sql);};
const sql=(statement,values=[])=>owner.query(statement,values),pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const product='00000000-0000-4000-8000-000000000100',sku='00000000-0000-4000-8000-000000001001';
const customer={name:'QA Покупатель этапа 5',phone:'+79990000000',email:'owner-browser@example.invalid'},delivery={method:'pickup_point',city:'QA Москва',address:'QA пункт выдачи, 1'};
const privateNote='QA внутренняя заметка владельца.\nПокупателю этот текст не передаётся.';
async function check(name,fn){try{await fn();report.checks.push({name,passed:true});console.log(`PASS ${name}`);}catch(error){report.checks.push({name,passed:false,error:scrub(error.message)});throw error;}}
async function waitUntil(fn,message,timeout=15000){const until=Date.now()+timeout;while(Date.now()<until){if(await fn())return;await pause(150);}throw new Error(message);}
async function createPage(){const ctx=await browser.newContext({viewport:{width:1440,height:1000},locale:'ru-RU',reducedMotion:'reduce'}),page=await ctx.newPage();page.setDefaultTimeout(15000);page.on('pageerror',error=>report.consoleErrors.push(scrub(error.message)));return{ctx,page};}
async function ready(page,path){await page.goto(base+path,{waitUntil:'networkidle'});await page.locator('[data-page-loading],[data-owner-loading]').waitFor({state:'hidden'}).catch(()=>{});}
async function api(ctx,path,body){const session=await(await ctx.request.get(base+'/api/commerce/session')).json();const response=body===undefined?await ctx.request.get(base+path):await ctx.request.post(base+path,{headers:{Origin:base,'Content-Type':'application/json','X-CSRF-Token':session.csrfToken},data:{...body,idempotencyKey:randomUUID()}});return{status:response.status(),value:await response.json()};}
async function response(page,path,action,expected=200){const pending=page.waitForResponse(res=>new URL(res.url()).pathname===path&&res.request().method()==='POST');await action();const res=await pending,payload=await res.json();assert.equal(res.status(),expected,`${path}: ${res.status()} ${payload.error?.code??''}`);return payload;}
async function responsive(page,name){for(const width of [1440,1024,768,375]){await page.setViewportSize({width,height:1000});await page.evaluate(()=>{if(document.activeElement instanceof HTMLElement)document.activeElement.blur();scrollTo(0,0);});await pause(100);const widths=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,width:innerWidth}));if(widths.scroll>widths.width+1){report.overflow={name,width,elements:await page.evaluate(()=>[...document.querySelectorAll('main *')].map(e=>({tag:e.tagName,class:e.className,right:e.getBoundingClientRect().right,width:e.getBoundingClientRect().width,text:e.textContent?.slice(0,60)})).filter(e=>e.right>innerWidth+1).slice(0,12))};await page.screenshot({path:privateDir+'/overflow.png',fullPage:true});}assert.ok(widths.scroll<=widths.width+1,`${name}: overflow at ${width}`);if(width===1440||width===375){const path=`${output}/${name}-${width}.png`;await page.screenshot({path,fullPage:true,mask:[page.locator('input[name=password]'),page.locator('input[name=code]'),page.locator('[data-manager-mail] pre')]});report.screenshots.push(path);}}await page.setViewportSize({width:1440,height:1000});}
async function stop(child){if(child.exitCode!==null||child.signalCode!==null)return;child.kill('SIGTERM');await Promise.race([new Promise(resolve=>child.once('exit',resolve)),pause(7000)]);if(child.exitCode===null&&child.signalCode===null){child.kill('SIGKILL');await new Promise(resolve=>child.once('exit',resolve));}}
try{
 assert.ok(existsSync('dist/server/entry.mjs'),'Build current stage 5 code first');assert.equal(await fetch(base+'/').then(()=>true).catch(()=>false),false,'QA port 14326 must be free');
 const dump=execute([...compose,'pg_dump','-U','ar_migrator','-d',source,'--no-password']);admin(`CREATE DATABASE ${database};`);created=true;admin(dump,database);
 owner=new pg.Pool({host:'127.0.0.1',port:Number(env.DB_PORT||65432),database,user:'ar_migrator',password:env.POSTGRES_PASSWORD,max:4});
 await sql('TRUNCATE ar_customers,ar_web_sessions,ar_rate_limits,ar_mail_outbox RESTART IDENTITY CASCADE');await sql('UPDATE ar_stock SET reserved=0,on_hand=CASE WHEN sku_id=$1 THEN 10 ELSE on_hand END',[sku]);await sql("UPDATE ar_products SET description='QA исходное описание товара.',meta_description='QA исходное краткое описание.',seo_title='QA ручной заголовок — сохранить' WHERE id=$1",[product]);
 const files=(await sql("SELECT DISTINCT f.filename_disk FROM directus_files f JOIN (SELECT file_id FROM ar_product_media UNION SELECT file_id FROM ar_sku_media) m ON m.file_id=f.id WHERE f.storage='local'")).rows;for(const file of files){assert.equal(basename(file.filename_disk),file.filename_disk);execute(['compose','-p',project,'cp',`cms:/directus/uploads/${file.filename_disk}`,join(uploads,file.filename_disk)]);}
 const node=join(root,'.tools/node-v24.21.0-darwin-arm64/bin/node');assert.ok(existsSync(node));const runtimeEnv={...process.env,AR_DATABASE_NAME:database,AR_DB_HOST:'127.0.0.1',AR_DB_PORT:String(env.DB_PORT||65432),APP_DB_PASSWORD:env.APP_DB_PASSWORD,APP_SECRET:randomBytes(48).toString('hex'),APP_ORIGIN:base,PORT:'14326',HOST:'127.0.0.1',STORE_MODE:'local-test',CMS_INTERNAL_URL:`http://127.0.0.1:${env.CMS_PORT||28055}`,CMS_UPLOADS_PATH:uploads};
 for(const [entry,key]of [['dist/server/entry.mjs','server'],['scripts/commerce-worker.ts','worker']]){const child=spawn(node,[entry],{cwd:root,env:runtimeEnv,stdio:['ignore','pipe','pipe']});children.push(child);child.stdout.on('data',data=>logs[key]=((logs[key]??'')+data).slice(-2000));child.stderr.on('data',data=>logs[key]=((logs[key]??'')+data).slice(-2000));}
 await waitUntil(()=>fetch(base+'/api/commerce/session').then(res=>res.ok).catch(()=>false),'Stage 5 QA server did not start');browser=await chromium.launch({channel:'chrome',headless:true});
 const manager=await createPage(),buyer=await createPage(),visitor=await createPage(),editor=await createPage();let paidOrder,openOrder,reviewId;
 async function openTools(id){const card=manager.page.locator(`[data-manager-order="${id}"]`);await card.waitFor();const details=card.locator('[data-owner-order-tools]');if(!await details.evaluate(el=>el.open))await details.locator(':scope>summary').click();return card;}
 async function managerMutation(path,action){const refreshed=manager.page.waitForResponse(res=>new URL(res.url()).pathname==='/api/manager/orders'&&res.request().method()==='GET');const result=await response(manager.page,path,action);await refreshed;await pause(100);return result;}
 async function purchase(ctx,email=customer.email){const cart=await api(ctx,'/api/commerce/cart'),added=await api(ctx,'/api/commerce/cart',{productId:product,skuId:sku,quantity:1,mode:'add',cartVersion:cart.value.version});assert.equal(added.status,200);const preview=await api(ctx,'/api/commerce/quote',{customer:{...customer,email},delivery,cartVersion:added.value.version});assert.equal(preview.status,200);const result=await api(ctx,'/api/commerce/checkout',{confirmation:{accepted:true,version:testOrderTerms.version},quoteId:preview.value.id,cartVersion:preview.value.cartVersion});assert.equal(result.status,200);return result.value.orders[0];}
 await check('real admin login and paid order expose owner tools; internal multiline note stays private',async()=>{
  await ready(manager.page,'/manager');await manager.page.locator('#manager-login-form [name=email]').fill(env.ADMIN_EMAIL);await manager.page.locator('#manager-login-form [name=password]').fill(env.ADMIN_PASSWORD);await response(manager.page,'/api/manager/login',()=>manager.page.locator('#manager-login-form button[type=submit]').click());await manager.page.locator('[data-manager-content]').waitFor();const order=await purchase(buyer.ctx);const quoted=await api(manager.ctx,'/api/manager/shipping',{orderId:order.id,costRubles:'350.50',note:'QA расчёт доставки'});assert.equal(quoted.status,200);const paid=await api(buyer.ctx,'/api/commerce/pay',{orderId:order.id,shippingVersion:quoted.value.shippingVersion,method:'card'});assert.equal(paid.status,200);assert.equal(paid.value.status,'paid');paidOrder=paid.value;
  await ready(manager.page,'/manager');let card=await openTools(paidOrder.id);await card.locator('[data-order-note-form] [name=note]').fill(privateNote);await managerMutation('/api/manager/note',()=>card.locator('[data-order-note-form] button[type=submit]').click());card=await openTools(paidOrder.id);await card.locator('.owner-note').filter({hasText:'QA внутренняя заметка'}).waitFor();const publicOrder=await api(buyer.ctx,`/api/commerce/order?id=${paidOrder.id}`);assert.equal('notes'in publicOrder.value,false);assert.equal('deliveryEvents'in publicOrder.value,false);assert.equal(JSON.stringify(publicOrder.value).includes('Покупателю этот текст'),false);await responsive(manager.page,'owner-note');
 });
 await check('fulfillment preserves manual override; carrier event is recorded until owner explicitly resumes it',async()=>{
  let card=await openTools(paidOrder.id);await card.locator('[data-fulfillment-form] [name=reason]').fill('QA товар собран');const packed=await managerMutation('/api/manager/fulfillment',()=>card.locator('[data-fulfillment-form] button[type=submit]').click());assert.equal(packed.deliveryStatus,'packing');assert.equal(packed.deliveryOverride,true);card=await openTools(paidOrder.id);await card.locator('[data-fulfillment-form] [name=trackingNumber]').fill('QA-TRACK-555');await card.locator('[data-fulfillment-form] [name=reason]').fill('QA отправление передано');const shipped=await managerMutation('/api/manager/fulfillment',()=>card.locator('[data-fulfillment-form] button[type=submit]').click());assert.equal(shipped.deliveryStatus,'shipped');
  card=await openTools(paidOrder.id);await card.locator('[data-carrier-test-tools]>summary').click();await card.locator('[data-carrier-test-form] [name=status]').selectOption('delivered');const timestamp=new Date(Date.now()+1000);const local=new Date(timestamp.getTime()-timestamp.getTimezoneOffset()*60000).toISOString().slice(0,19);await card.locator('[data-carrier-test-form] [name=occurredAt]').fill(local);await card.locator('[data-carrier-test-form] [name=providerEventId]').fill('qa-owner-carrier-delivered');const held=await managerMutation('/api/manager/carrier-test',()=>card.locator('[data-carrier-test-form] button[type=submit]').click());assert.equal(held.deliveryStatus,'shipped');assert.equal(held.deliveryOverride,true);assert.ok(held.deliveryEvents.some(event=>event.source==='carrier'&&event.applied===false&&event.status==='delivered'));
  card=await openTools(paidOrder.id);await card.locator('[data-delivery-history]>summary').click();await responsive(manager.page,'owner-delivery-override');await card.locator('[data-delivery-override-tools]>summary').click();await card.locator('[data-delivery-override-form] [name=reason]').fill('QA проверка завершена, разрешены статусы перевозчика');const resumed=await managerMutation('/api/manager/delivery-override',()=>card.locator('[data-clear-delivery-override]').click());assert.equal(resumed.deliveryOverride,false);assert.equal(resumed.deliveryStatus,'delivered');assert.ok(resumed.deliveredAt);await ready(buyer.page,`/orders/${paidOrder.id}`);await buyer.page.getByText('Трек-номер: QA-TRACK-555',{exact:true}).waitFor();await buyer.page.getByText(/^Получен:/).waitFor();assert.equal(await buyer.page.getByText('Покупателю этот текст',{exact:false}).count(),0);await responsive(buyer.page,'customer-delivered-tracking');
 });
 await check('stock correction respects reservations; owner cancels an unpaid order with a private reason',async()=>{
  openOrder=await purchase(visitor.ctx,'owner-open@example.invalid');await ready(manager.page,'/manager');const p=manager.page;await p.locator('#manager-stock-adjust-form [name=skuId]').selectOption(sku);assert.equal(await p.locator('#manager-stock-adjust-form [name=onHand]').getAttribute('min'),'1');const denied=await api(manager.ctx,'/api/manager/stock-adjust',{skuId:sku,onHand:0,reason:'QA ниже резерва'});assert.equal(denied.status,409);await p.locator('#manager-stock-adjust-form [name=onHand]').fill('11');await p.locator('#manager-stock-adjust-form [name=reason]').fill('QA пересчёт склада');await managerMutation('/api/manager/stock-adjust',()=>p.locator('#manager-stock-adjust-form button[type=submit]').click());assert.deepEqual((await sql('SELECT on_hand,reserved FROM ar_stock WHERE sku_id=$1',[sku])).rows[0],{on_hand:11,reserved:1});const card=await openTools(openOrder.id);await card.locator('[data-owner-cancel-tools]>summary').click();await card.locator('[data-owner-cancel-form] [name=reason]').fill('QA отмена после согласования');const cancelled=await managerMutation('/api/manager/order-cancel',()=>card.locator('[data-owner-cancel-form] button[type=submit]').click());assert.equal(cancelled.status,'cancelled');assert.deepEqual((await sql('SELECT on_hand,reserved FROM ar_stock WHERE sku_id=$1',[sku])).rows[0],{on_hand:11,reserved:0});assert.equal(JSON.stringify((await api(visitor.ctx,`/api/commerce/order?id=${openOrder.id}`)).value).includes('QA отмена после согласования'),false);const paidCard=await openTools(paidOrder.id);assert.equal(await paidCard.locator('[data-owner-cancel-form]').count(),0);
 });
 await check('owner notifications show local MAX/email and retry the same failed row',async()=>{
  await waitUntil(async()=>Number((await sql("SELECT count(*) n FROM ar_owner_notifications WHERE status='delivered'")).rows[0].n)>0,'Owner worker did not deliver notifications');const row=(await sql("SELECT id,attempts FROM ar_owner_notifications WHERE status='delivered' ORDER BY created_at DESC LIMIT 1")).rows[0];await sql("UPDATE ar_owner_notifications SET status='failed',last_error='QA локальная ошибка' WHERE id=$1",[row.id]);const count=(await sql('SELECT count(*) n FROM ar_owner_notifications')).rows[0].n;await manager.page.locator('[data-load-notifications]').click();const card=manager.page.locator(`[data-notification-id="${row.id}"]`);await card.locator('[data-retry-notification]').waitFor();await response(manager.page,'/api/manager/notification-retry',()=>card.locator('[data-retry-notification]').click());await waitUntil(async()=>(await sql('SELECT status FROM ar_owner_notifications WHERE id=$1',[row.id])).rows[0].status==='delivered','Retried notification did not complete');assert.equal((await sql('SELECT count(*) n FROM ar_owner_notifications')).rows[0].n,count);assert.equal((await sql('SELECT attempts FROM ar_owner_notifications WHERE id=$1',[row.id])).rows[0].attempts,row.attempts+1);await manager.page.locator('[data-load-notifications]').click();await responsive(manager.page,'owner-notifications');
 });
 await check('generator previews two editable fields, applies only those fields, and preserves manual title',async()=>{
  const p=manager.page;await ready(p,`/manager/content?product=${product}`);await p.locator('[data-generation-current]').waitFor();assert.equal(await p.locator('[data-generation-product]').inputValue(),product);assert.equal(await p.locator('[data-generation-title]').inputValue(),'QA ручной заголовок — сохранить');assert.equal(await p.locator('[data-generation-title]').evaluate(input=>input.readOnly),true);const before=(await sql('SELECT description,meta_description,seo_title FROM ar_products WHERE id=$1',[product])).rows[0];const draft=await response(p,'/api/manager/generate',()=>p.locator('[data-generate]').click());assert.match(draft.description,/\n\n/);await p.locator('[data-generation-preview]').waitFor();assert.deepEqual((await sql('SELECT description,meta_description,seo_title FROM ar_products WHERE id=$1',[product])).rows[0],before);await p.locator('#apply-description-form [name=description]').fill('QA проверенное описание.\n\nQA второй абзац без вымышленных обещаний.');await p.locator('#apply-description-form [name=metaDescription]').fill('QA проверенный meta description товара AUTO REELZ.');await responsive(p,'description-editable-preview');await response(p,'/api/manager/apply-description',()=>p.locator('#apply-description-form button[type=submit]').click());await p.locator('[data-owner-success]').waitFor();const after=(await sql('SELECT description,meta_description,seo_title FROM ar_products WHERE id=$1',[product])).rows[0];assert.equal(after.description,'QA проверенное описание.\n\nQA второй абзац без вымышленных обещаний.');assert.equal(after.meta_description,'QA проверенный meta description товара AUTO REELZ.');assert.equal(after.seo_title,before.seo_title);
 });
 await check('generator rejects a stale draft and shows a simulated failure without overwriting CMS copy',async()=>{
  const p=manager.page;await response(p,'/api/manager/generate',()=>p.locator('[data-generate]').click());await p.locator('[data-generation-preview]').waitFor();const draftText=await p.locator('#apply-description-form [name=description]').inputValue();await sql("UPDATE ar_products SET description='QA параллельная правка в CMS' WHERE id=$1",[product]);await response(p,'/api/manager/apply-description',()=>p.locator('#apply-description-form button[type=submit]').click(),409);await p.locator('[data-generation-conflict]').waitFor();assert.equal(await p.locator('#apply-description-form [name=description]').inputValue(),draftText);assert.equal((await sql('SELECT description FROM ar_products WHERE id=$1',[product])).rows[0].description,'QA параллельная правка в CMS');await p.locator('#generation-form .owner-test-tools>summary').click();await p.locator('[name=simulateFailure]').check();await response(p,'/api/manager/generate',()=>p.locator('[data-generate]').click(),503);await p.locator('[data-owner-error]').waitFor();assert.equal((await sql('SELECT description FROM ar_products WHERE id=$1',[product])).rows[0].description,'QA параллельная правка в CMS');await responsive(p,'description-conflict');
 });
 await check('received buyer submits a photo review; owner preview is private; publication and rejection use real moderation UI',async()=>{
  const requested=await api(buyer.ctx,'/api/auth/request',{email:customer.email});assert.equal(requested.status,200);const challenge=requested.value.challengeId;let message;await waitUntil(async()=>{const inbox=await api(manager.ctx,'/api/manager/mail');message=inbox.value.messages.find(item=>item.to===customer.email&&/код входа:/i.test(item.body));return Boolean(message);},'OTP test mail was not delivered by worker');const code=message?.body.match(/код входа: (\d{6})/i)?.[1];assert.ok(code);secrets.push(code);assert.equal((await api(buyer.ctx,'/api/auth/verify',{challengeId:challenge,code})).status,200);const session=(await api(buyer.ctx,'/api/commerce/session')).value;const photo=await sharp({create:{width:32,height:24,channels:3,background:'#cb181a'}}).png().toBuffer();const submitted=await buyer.ctx.request.post(base+'/api/social/reviews',{headers:{Origin:base,'X-CSRF-Token':session.csrfToken},multipart:{productId:product,orderId:paidOrder.id,authorName:'QA Покупатель',body:'QA проверка отзыва после получения товара. Текст для модерации и тестовая фотография.',idempotencyKey:randomUUID(),files:{name:'qa-review.png',mimeType:'image/png',buffer:photo}}});assert.equal(submitted.status(),201);const review=await submitted.json();reviewId=review.id??review.review?.id;assert.ok(reviewId);let publicReviews=await api(visitor.ctx,`/api/social/reviews?productId=${product}`);assert.equal(publicReviews.value.reviews.some(item=>item.id===reviewId),false);
  const p=manager.page;await ready(p,'/manager/reviews');const card=p.locator(`[data-review-id="${reviewId}"]`);await card.waitFor();await card.locator('img').waitFor();await waitUntil(()=>card.locator('img').evaluate(image=>image.complete&&image.naturalWidth>0),'Private review image did not load for owner');const previewUrl=await card.locator('img').getAttribute('src');assert.ok([401,403,404].includes((await visitor.ctx.request.get(base+previewUrl)).status()));await responsive(p,'review-pending');await card.locator('[name=note]').fill('QA отзыв проверен');await response(p,'/api/social/moderation',()=>card.locator('[data-review-decision=approved]').click());await p.locator('[data-review-filter]').selectOption('approved');await p.locator(`[data-review-id="${reviewId}"]`).waitFor();publicReviews=await api(visitor.ctx,`/api/social/reviews?productId=${product}`);const published=publicReviews.value.reviews.find(item=>item.id===reviewId);assert.ok(published);assert.equal((await visitor.ctx.request.get(base+published.media[0].url)).status(),200);await responsive(p,'review-approved');const approved=p.locator(`[data-review-id="${reviewId}"]`);await approved.locator('[name=note]').fill('QA повторная проверка — скрыть тестовый отзыв');await response(p,'/api/social/moderation',()=>approved.locator('[data-review-decision=rejected]').click());publicReviews=await api(visitor.ctx,`/api/social/reviews?productId=${product}`);assert.equal(publicReviews.value.reviews.some(item=>item.id===reviewId),false);assert.ok([403,404].includes((await visitor.ctx.request.get(base+published.media[0].url)).status()));
 });
 await check('content editor cannot access owner generation, private notes, moderation or notifications',async()=>{
  await ready(editor.page,'/manager/content');await editor.page.locator('#owner-login-form [name=email]').fill(env.EDITOR_EMAIL);await editor.page.locator('#owner-login-form [name=password]').fill(env.EDITOR_PASSWORD);await response(editor.page,'/api/manager/login',()=>editor.page.locator('#owner-login-form button[type=submit]').click());await editor.page.locator('[data-owner-error]').waitFor();assert.match(await editor.page.locator('[data-owner-error]').innerText(),/только администратору/);assert.equal(await editor.page.locator('[data-owner-content]').isVisible(),false);for(const path of ['/api/manager/products','/api/manager/notifications','/api/social/moderation'])assert.equal((await api(editor.ctx,path)).status,403);assert.equal((await api(editor.ctx,'/api/manager/note',{orderId:paidOrder.id,note:'QA forbidden note'})).status,403);await ready(editor.page,'/manager/reviews');await editor.page.locator('[data-owner-error]').waitFor();assert.equal(await editor.page.locator('[data-owner-content]').isVisible(),false);
 });
 assert.deepEqual(report.consoleErrors,[]);report.passed=true;
}catch(error){report.error=scrub(error.stack||error.message);report.processLogs=Object.fromEntries(Object.entries(logs).map(([key,value])=>[key,scrub(value)]));console.error(scrub(error.message));process.exitCode=1;}finally{try{await browser?.close();for(const child of children)await stop(child);await owner?.end();if(created){assert.match(database,/^ar_qa_owner_\d+_\d+$/);admin(`DROP DATABASE ${database} WITH (FORCE);`);}report.cleanup=true;}catch(error){report.cleanupError=scrub(error.message);report.passed=false;process.exitCode=1;}report.finishedAt=new Date().toISOString();writeFileSync(`${output}/owner-browser-check.json`,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({passed:report.passed,checks:report.checks.length,cleanup:report.cleanup,error:report.error?.split('\n')[0]}));}
