import {testOrderTerms} from '../src/lib/checkout-confirmations.ts';
/** Real browser acceptance. Every shop write targets an ephemeral QA clone. No API interception. */
import assert from 'node:assert/strict';
import {spawn,spawnSync} from 'node:child_process';
import {createRequire} from 'node:module';
import {readFileSync,mkdirSync,writeFileSync,existsSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {basename,join} from 'node:path';
import {randomBytes,randomUUID} from 'node:crypto';
import pg from 'pg';
const root=fileURLToPath(new URL('..',import.meta.url));process.chdir(root);
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||(process.env.HOME+'/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
const env=Object.fromEntries(readFileSync('.env','utf8').split(/\r?\n/).filter(s=>s&&!s.startsWith('#')&&s.includes('=')).map(s=>{const i=s.indexOf('=');return[s.slice(0,i),s.slice(i+1)];}));
const source='autoreelz2026_new',project='autoreelz2026-new',base='http://127.0.0.1:14325';
assert.equal(env.POSTGRES_DB,source);assert.equal(env.COMPOSE_PROJECT_NAME,project);
const database=`ar_qa_e2e_${process.pid}_${Date.now()}`;assert.match(database,/^ar_qa_e2e_\d+_\d+$/);
const viewportWidth=Number(process.env.AR_PURCHASE_VIEWPORT||1440);assert.ok([375,1440].includes(viewportWidth));
const output=process.env.AR_PURCHASE_OUTPUT||'artifacts/stage-4',privateDir=`tmp/stage-4/${database}`,uploads=join(root,privateDir,'uploads');mkdirSync(output,{recursive:true});mkdirSync(uploads,{recursive:true});
const report={database,source,startedAt:new Date().toISOString(),browser:'Chrome headless, actual HTTP APIs',viewportWidth,checks:[],screenshots:[],consoleErrors:[],limitations:[],cleanup:false,passed:false};
const secrets=[env.ADMIN_EMAIL,env.ADMIN_PASSWORD,env.EDITOR_EMAIL,env.EDITOR_PASSWORD,env.APP_DB_PASSWORD,env.POSTGRES_PASSWORD].filter(Boolean);
const scrub=value=>{let result=String(value);for(const secret of secrets)result=result.replaceAll(secret,'[redacted]');return result;};
const compose=['compose','-p',project,'exec','-T','db'];let created=false,server,worker,browser,owner;
const children=[];const childLogs={};
const execute=(args,input)=>{const r=spawnSync('docker',args,{cwd:root,input,encoding:'utf8',timeout:30000,maxBuffer:128*1024*1024});if(r.error)throw r.error;if(r.status!==0)throw new Error(scrub(r.stderr||'QA Docker command failed'));return r.stdout;};
const admin=(statement,db=source)=>{assert.ok(db===database||db===source);return execute([...compose,'psql','-X','-q','-v','ON_ERROR_STOP=1','-U','ar_migrator','-d',db],statement);};
const pause=ms=>new Promise(r=>setTimeout(r,ms));
const sql=(statement,values=[])=>owner.query(statement,values);
const state=async id=>(await sql('SELECT on_hand,reserved FROM ar_stock WHERE sku_id=$1',[id])).rows[0];
const red='00000000-0000-4000-8000-000000001001',white='00000000-0000-4000-8000-000000001003',product='00000000-0000-4000-8000-000000000100';
const customer={name:'Тестовый Покупатель',phone:'+79990000000',email:'browser-acceptance@example.invalid'};
const delivery={method:'pickup_point',city:'Тестовая Москва',address:'Тестовый пункт выдачи, 1'};
async function check(name,fn){try{await fn();report.checks.push({name,passed:true});console.log(`PASS ${name}`);}catch(e){report.checks.push({name,passed:false,error:scrub(e.message)});throw e;}}
async function waitUntil(fn,message,timeout=15000){const end=Date.now()+timeout;while(Date.now()<end){if(await fn())return;await pause(200);}throw new Error(message);}
async function createPage(){const ctx=await browser.newContext({viewport:{width:viewportWidth,height:1000},locale:'ru-RU',reducedMotion:'reduce'});const page=await ctx.newPage();page.setDefaultTimeout(15000);page.on('pageerror',e=>report.consoleErrors.push(scrub(e.message)));return{ctx,page};}
async function ready(page,path){await page.goto(base+path,{waitUntil:'networkidle'});await page.locator('[data-page-loading]').waitFor({state:'hidden'}).catch(()=>{});}
async function responsive(page,name){for(const width of [1440,1024,768,375]){await page.setViewportSize({width,height:1000});await page.evaluate(()=>{if(document.activeElement instanceof HTMLElement)document.activeElement.blur();window.scrollTo(0,0);});await pause(120);const overflow=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));assert.ok(overflow.scroll<=overflow.width+1,`${name} overflow ${width}: ${overflow.scroll}`);if(width===1440||width===375){const path=`${output}/${name}-${width}.png`;await page.screenshot({path,fullPage:true,mask:[page.locator('[data-manager-mail] pre'),page.locator('input[name=code]'),page.locator('input[name=password]')]});report.screenshots.push(path);}}await page.setViewportSize({width:viewportWidth,height:1000});}
async function clickResponse(page,path,action){const response=page.waitForResponse(r=>new URL(r.url()).pathname===path&&r.request().method()==='POST').then(async r=>{const value=await r.json();assert.ok(r.ok(),`${path}: ${r.status()} ${value.error?.code??''}`);return value;});await action();return await response;}
async function api(ctx,path,body,headers={}){const session=await(await ctx.request.get(base+'/api/commerce/session')).json();const r=body===undefined?await ctx.request.get(base+path):await ctx.request.post(base+path,{headers:{Origin:base,'Content-Type':'application/json','X-CSRF-Token':session.csrfToken,...headers},data:{...body,idempotencyKey:randomUUID()}});return{status:r.status(),value:await r.json()};}
async function loginManager(page,role='admin'){await ready(page,'/manager');await page.locator('#manager-login-form [name=email]').fill(role==='admin'?env.ADMIN_EMAIL:env.EDITOR_EMAIL);await page.locator('#manager-login-form [name=password]').fill(role==='admin'?env.ADMIN_PASSWORD:env.EDITOR_PASSWORD);await clickResponse(page,'/api/manager/login',()=>page.locator('#manager-login-form button[type=submit]').click());}
async function shipping(page,id,cost){const card=page.locator(`[data-manager-order="${id}"]`);await card.locator('[name=cost]').fill(cost);await card.getByLabel('Основание расчёта', {exact:true}).fill('Тестовый ручной расчёт доставки');const updated=await clickResponse(page,'/api/manager/shipping',()=>card.getByRole('button',{name:'Сохранить доставку',exact:true}).click());assert.equal(updated.shippingCostRubles,`${cost}.00`);assert.equal((await sql('SELECT shipping_cost_rubles FROM ar_orders WHERE id=$1',[id])).rows[0].shipping_cost_rubles,updated.shippingCostRubles);await card.locator('[name=cost]').waitFor();}
async function stop(child){if(!child||child.exitCode!==null||child.signalCode!==null)return;child.kill('SIGTERM');await Promise.race([new Promise(r=>child.once('exit',r)),pause(7000)]);if(child.exitCode===null&&child.signalCode===null){child.kill('SIGKILL');await new Promise(r=>child.once('exit',r));}}
try{
 assert.ok(existsSync('dist/server/entry.mjs'),'Build the current app before running browser acceptance');
 assert.equal(await fetch(base+'/').then(()=>true).catch(()=>false),false,'QA port 14325 must be unused');
 const dump=execute([...compose,'pg_dump','-U','ar_migrator','-d',source,'--no-password']);admin(`CREATE DATABASE ${database};`);created=true;admin(dump,database);
 owner=new pg.Pool({host:'127.0.0.1',port:Number(env.DB_PORT||65432),database,user:'ar_migrator',password:env.POSTGRES_PASSWORD,max:4});
 await sql('TRUNCATE ar_customers,ar_web_sessions,ar_rate_limits,ar_mail_outbox RESTART IDENTITY CASCADE');
 await sql('UPDATE ar_stock SET reserved=0,on_hand=CASE WHEN sku_id=$1 THEN 7 WHEN sku_id=$2 THEN 0 ELSE on_hand END',[red,white]);
 const files=(await sql("SELECT DISTINCT f.filename_disk FROM directus_files f JOIN (SELECT file_id FROM ar_product_media UNION SELECT file_id FROM ar_sku_media) m ON m.file_id=f.id WHERE f.storage='local'")).rows;
 for(const file of files){assert.equal(basename(file.filename_disk),file.filename_disk);execute(['compose','-p',project,'cp',`cms:/directus/uploads/${file.filename_disk}`,join(uploads,file.filename_disk)]);}
 const node=join(root,'.tools/node-v24.21.0-darwin-arm64/bin/node');assert.ok(existsSync(node));
 const runtimeEnv={...process.env,AR_DATABASE_NAME:database,AR_DB_HOST:'127.0.0.1',AR_DB_PORT:String(env.DB_PORT||65432),APP_DB_PASSWORD:env.APP_DB_PASSWORD,APP_SECRET:randomBytes(48).toString('hex'),APP_ORIGIN:base,PORT:'14325',HOST:'127.0.0.1',STORE_MODE:'local-test',CMS_INTERNAL_URL:`http://127.0.0.1:${env.CMS_PORT||28055}`,CMS_UPLOADS_PATH:uploads};
 for(const [entry,key]of [['dist/server/entry.mjs','server'],['scripts/commerce-worker.ts','worker']]){const child=spawn(node,[entry],{cwd:root,env:runtimeEnv,stdio:['ignore','pipe','pipe']});children.push(child);let log='';child.stdout.on('data',d=>childLogs[key]=log=(log+d).slice(-2000));child.stderr.on('data',d=>childLogs[key]=log=(log+d).slice(-2000));child.once('exit',code=>{if(code&&code!==143)report.consoleErrors.push(`${key} exited ${code}: ${scrub(log)}`);});if(key==='server')server=child;else worker=child;}
 await waitUntil(async()=>fetch(base+'/api/commerce/session').then(r=>r.ok).catch(()=>false),'QA server did not start');
 browser=await chromium.launch({channel:'chrome',headless:true});
 const buyer=await createPage(),manager=await createPage(),outsider=await createPage(),editor=await createPage();
 let ordinary,preorder,challengeId,otp;
 await check('browser selects vehicle, exposes unknown fitment honestly and adds two exact SKU',async()=>{
  const p=buyer.page;await ready(p,'/');await responsive(p,'home');await p.locator('#selection [name=vehicle]').selectOption('priora-2');await p.locator('#selection [name=year]').fill('2015');await p.locator('#selection [name=ac]').selectOption('yes');await p.locator('#selection button[type=submit],#selection button.button').click();await p.waitForURL('**/catalog?**');await p.getByRole('heading',{name:'Подтверждённых совпадений пока нет'}).waitFor();await p.getByRole('link',{name:/Показать товары.*неизвестной совместимостью/}).click();await p.locator('.cat-product-grid .product-card').first().waitFor();await p.locator('.card-title[href*="heater-control"]').click();await p.waitForURL('**/product/heater-control?**');assert.ok((await p.locator('[data-current-sku]').getAttribute('data-current-sku'))===red);await clickResponse(p,'/api/commerce/cart',()=>p.locator('.buy-button[data-add-product]').click());await p.locator(`.variant-option[href*="${white}"]`).click();await p.waitForURL(`**sku=${white}**`);assert.equal(await p.locator('[data-price-rubles]').getAttribute('data-price-rubles'),'5300.00');assert.equal((await sql('SELECT price_rubles FROM ar_skus WHERE id=$1',[white])).rows[0].price_rubles,'5300.00');await clickResponse(p,'/api/commerce/cart',()=>p.locator('.buy-button[data-add-product]').click());await ready(p,'/cart');await p.locator('.commerce-line').nth(1).waitFor();assert.equal(await p.locator('.commerce-line').count(),2);assert.equal(await p.locator('.commerce-kind.preorder').count(),1);await responsive(p,'cart-mixed');
 });
 await check('browser checkout splits ordinary and preorder; unknown shipping blocks both payments',async()=>{
  const p=buyer.page;await p.getByRole('link',{name:'Перейти к оформлению',exact:true}).click();await p.locator('#checkout-form').waitFor();for(const[name,value]of Object.entries({...customer,...delivery}))if(name==='method')await p.locator(`#checkout-form [name=${name}]`).selectOption(value);else await p.locator(`#checkout-form [name=${name}]`).fill(value);await responsive(p,'checkout-form');const quote=await clickResponse(p,'/api/commerce/quote',()=>p.locator('#checkout-form button[type=submit]').click());assert.equal(quote.groups.length,2);assert.ok(quote.groups.every(g=>g.shipping.costRubles===null&&g.totalRubles===null));await p.locator('[data-quote-review]').waitFor();await responsive(p,'checkout-review');const checkoutResponse=p.waitForResponse(r=>r.url().endsWith('/api/commerce/checkout')&&r.request().method()==='POST');await p.locator('[data-accept-checkout]').check();await p.locator('[data-confirm-checkout]').click();assert.equal((await checkoutResponse).status(),200);await p.waitForURL('**/orders/**');const result=(await api(buyer.ctx,'/api/commerce/orders')).value;ordinary=result.orders.find(o=>o.kind==='ordinary');preorder=result.orders.find(o=>o.kind==='preorder');assert.ok(ordinary&&preorder);await p.waitForURL('**/orders/**');await p.locator('[data-order-content] .commerce-grid').waitFor();assert.equal(await p.locator('.payment-form').count(),0);assert.deepEqual(await state(red),{on_hand:7,reserved:1});assert.deepEqual(await state(white),{on_hand:0,reserved:0});assert.equal((await sql('SELECT 1 FROM ar_stock_movements WHERE order_id=$1',[preorder.id])).rowCount,0);await responsive(p,'order-delivery-pending');
 });
 await check('unauthenticated browser cannot read an order or the private test mailbox; CSRF and Origin enforced',async()=>{
  const denied=await api(outsider.ctx,`/api/commerce/order?id=${ordinary.id}`);assert.ok([403,404].includes(denied.status));assert.equal((await api(outsider.ctx,'/api/manager/mail')).status,401);
  assert.equal((await api(buyer.ctx,'/api/commerce/cart',{productId:product,skuId:red,quantity:1,mode:'add',cartVersion:0},{Origin:'https://untrusted.example.invalid'})).status,403);
  assert.equal((await api(buyer.ctx,'/api/commerce/cart',{productId:product,skuId:red,quantity:1,mode:'add',cartVersion:0},{'X-CSRF-Token':'wrong'})).status,403);
 });
 await check('real Directus editor login succeeds but trading commands and private mailbox are forbidden',async()=>{await loginManager(editor.page,'editor');await editor.page.locator('[data-page-error]').waitFor();assert.match(await editor.page.locator('[data-page-error]').innerText(),/нет прав/);assert.equal((await api(editor.ctx,'/api/manager/mail')).status,403);assert.equal((await api(editor.ctx,'/api/manager/orders')).status,403);assert.equal((await api(editor.ctx,'/api/manager/stock',{skuId:white,quantity:1,reason:'Forbidden editor QA command'})).status,403);assert.equal((await api(editor.ctx,'/api/manager/shipping',{orderId:ordinary.id,costRubles:'0.01',note:'Forbidden editor QA command'})).status,403);assert.deepEqual(await state(white),{on_hand:0,reserved:0});});
 await check('real admin UI quotes ordinary delivery; buyer completes card test payment',async()=>{
  await loginManager(manager.page);await manager.page.locator('[data-manager-content]').waitFor();await shipping(manager.page,ordinary.id,'350');await ready(buyer.page,`/orders/${ordinary.id}`);await buyer.page.locator('.payment-form').waitFor();await responsive(buyer.page,'order-ready-to-pay');await buyer.page.locator('.payment-form [value=card]').check();const paid=await clickResponse(buyer.page,'/api/commerce/pay',()=>buyer.page.getByRole('button',{name:'Оплатить тестово',exact:true}).click());assert.equal(paid.status,'paid');assert.equal(paid.productTotalRubles,'4900.00');assert.equal(paid.shippingCostRubles,'350.00');assert.equal(paid.totalRubles,'5250.00');assert.equal((await sql("SELECT amount_rubles FROM ar_payments WHERE order_id=$1 AND status='succeeded'",[ordinary.id])).rows[0].amount_rubles,'5250.00');await buyer.page.locator('.status-pill.paid').waitFor();assert.deepEqual(await state(red),{on_hand:6,reserved:0});await responsive(buyer.page,'order-paid-card');
 });
 await check('manager receives stock and confirms whole preorder; SBP does not debit components twice',async()=>{
  const p=manager.page;await p.locator('#manager-stock-form [name=skuId]').selectOption(white);await p.locator('#manager-stock-form [name=quantity]').fill('1');await p.locator('#manager-stock-form [name=reason]').fill('Тестовый приход для предзаказа');await clickResponse(p,'/api/manager/stock',()=>p.locator('#manager-stock-form button[type=submit]').click());assert.deepEqual(await state(white),{on_hand:1,reserved:0});await shipping(p,preorder.id,'420');const card=p.locator(`[data-manager-order="${preorder.id}"]`);await card.locator('[name=terms]').fill('Тестовые условия: отправка после проверки заказа менеджером.');const confirmed=await clickResponse(p,'/api/manager/confirm',()=>card.getByRole('button',{name:'Подтвердить и открыть оплату',exact:true}).click());assert.equal(confirmed.status,'awaiting_payment');assert.deepEqual(await state(white),{on_hand:0,reserved:0});await ready(buyer.page,`/orders/${preorder.id}`);await buyer.page.locator('.payment-form').waitFor();await buyer.page.locator('.payment-form [value=sbp]').check();const paid=await clickResponse(buyer.page,'/api/commerce/pay',()=>buyer.page.getByRole('button',{name:'Оплатить тестово',exact:true}).click());assert.equal(paid.status,'paid');assert.equal(paid.productTotalRubles,'5300.00');assert.equal(paid.shippingCostRubles,'420.00');assert.equal(paid.totalRubles,'5720.00');assert.deepEqual(await state(white),{on_hand:0,reserved:0});const movements=(await sql('SELECT stock_delta FROM ar_stock_movements WHERE order_id=$1',[preorder.id])).rows;assert.equal(movements.reduce((n,m)=>n+m.stock_delta,0),-1);await buyer.page.locator('.status-pill.paid').waitFor();await responsive(buyer.page,'order-paid-preorder');await p.locator('[data-reload-manager]').click();await responsive(p,'manager-orders');
 });
 await check('OTP arrives in private manager UI; wrong and reused code rejected; new browser gains exact email history',async()=>{
  const p=outsider.page;await ready(p,'/account');await p.locator('#request-code-form [name=email]').fill(customer.email);const requested=await clickResponse(p,'/api/auth/request',()=>p.locator('#request-code-form button[type=submit]').click());challengeId=requested.challengeId;assert.equal(Object.keys(requested).includes('code'),false);await p.locator('#verify-code-form').waitFor();await waitUntil(async()=>(await sql('SELECT status FROM ar_mail_outbox WHERE deduplication_key=$1',[`login:${challengeId}`])).rows[0]?.status==='delivered','Background worker did not deliver the private test email',10000);
  await manager.page.locator('[data-load-mail]').click();const message=manager.page.locator('.mail-message').filter({has:manager.page.getByRole('heading',{name:'Код входа в AUTO REELZ',exact:true})}).filter({hasText:customer.email});await message.waitFor();otp=(await message.locator('pre').innerText()).match(/код входа: (\d{6})/i)?.[1];assert.ok(otp);secrets.push(otp);const wrong=otp==='000000'?'000001':'000000';await p.locator('#verify-code-form [name=code]').fill(wrong);const rejected=p.waitForResponse(r=>r.url().endsWith('/api/auth/verify'));await p.locator('#verify-code-form button[type=submit]').click();assert.equal((await rejected).status(),400);await p.locator('[data-page-error]').waitFor();await p.locator('#verify-code-form [name=code]').fill(otp);await clickResponse(p,'/api/auth/verify',()=>p.locator('#verify-code-form button[type=submit]').click());await p.locator('[data-account-identity]').waitFor();await waitUntil(async()=>await p.locator('[data-account-orders] .order-card').count()===2,'Verified history should contain two orders');assert.equal((await api(outsider.ctx,`/api/commerce/order?id=${ordinary.id}`)).status,200);assert.equal((await api(outsider.ctx,'/api/auth/verify',{challengeId,code:otp})).status,400);await responsive(p,'account-verified');await responsive(manager.page,'manager-private-mail');
 });
 await check('background worker expires an unpaid order without a page visit and releases its reservation once',async()=>{
  const expiring=await createPage();const c=await api(expiring.ctx,'/api/commerce/cart');const add=await api(expiring.ctx,'/api/commerce/cart',{productId:product,skuId:red,quantity:1,mode:'add',cartVersion:c.value.version});assert.equal(add.status,200);const quote=await api(expiring.ctx,'/api/commerce/quote',{customer:{...customer,email:'expiry-browser@example.invalid'},delivery,cartVersion:add.value.version});assert.equal(quote.status,200);const purchase=await api(expiring.ctx,'/api/commerce/checkout',{confirmation:{accepted:true,version:testOrderTerms.version},quoteId:quote.value.id,cartVersion:quote.value.cartVersion});assert.equal(purchase.status,200);const order=purchase.value.orders[0];assert.deepEqual(await state(red),{on_hand:6,reserved:1});await sql("UPDATE ar_orders SET expires_at=now()-interval '1 second' WHERE id=$1",[order.id]);await waitUntil(async()=>(await sql('SELECT status FROM ar_orders WHERE id=$1',[order.id])).rows[0]?.status==='expired','Worker did not expire unpaid order',12000);assert.deepEqual(await state(red),{on_hand:6,reserved:0});const before=(await sql('SELECT count(*) n FROM ar_stock_movements WHERE order_id=$1',[order.id])).rows[0].n;await pause(5200);assert.equal((await sql('SELECT count(*) n FROM ar_stock_movements WHERE order_id=$1',[order.id])).rows[0].n,before);await ready(expiring.page,`/orders/${order.id}`);await expiring.page.locator('.status-pill.expired').waitFor();await responsive(expiring.page,'order-expired');await expiring.ctx.close();
 });
 await check('logout removes the confirmed email identity and access to its order history',async()=>{await outsider.page.locator('[data-logout]').click();await outsider.page.locator('#request-code-form').waitFor();await waitUntil(async()=>await outsider.page.locator('[data-account-orders] .order-card').count()===0,'History remains visible after logout');assert.ok([403,404].includes((await api(outsider.ctx,`/api/commerce/order?id=${ordinary.id}`)).status));await responsive(outsider.page,'account-guest');});
 assert.deepEqual(report.consoleErrors,[]);report.passed=true;
}catch(error){report.error=scrub(error.stack||error.message);report.processLogs=Object.fromEntries(Object.entries(childLogs).map(([key,value])=>[key,scrub(value)]));console.error(scrub(error.message));process.exitCode=1;}
finally{
 try{await browser?.close();for(const child of children)await stop(child);await owner?.end();if(created)admin(`DROP DATABASE IF EXISTS ${database} WITH (FORCE);`);report.cleanup=true;}catch(error){report.cleanupError=scrub(error.message);report.passed=false;process.exitCode=1;}
 report.finishedAt=new Date().toISOString();writeFileSync(`${output}/browser-check.json`,JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,checks:report.checks.length,cleanup:report.cleanup,error:report.error?.split('\n')[0]}));
}
