// Presentation metadata only; PostgreSQL structure is owned by migrations/.
export const collections = {
 ar_categories:['Категории','account_tree','{{name}}','Три уровня: раздел → категория → подкатегория.'],
 ar_products:['Товары','inventory_2','{{name}}','Отдельные товары и фиксированные комплекты. Демо-данные отмечены отдельно.'],
 ar_skus:['Исполнения (SKU)','style','{{article}} · {{name}}','Физические исполнения. Сохраняйте существующие артикулы; цены в рублях.'],
 ar_bundle_components:['Составы комплектов','deployed_code','{{bundle_id.name}} · {{sku_id.article}}','Только конкретные SKU отдельных деталей. Нет собственного остатка комплекта.'],
 ar_vehicles:['Автомобили','directions_car','{{name}}','Приора 1 и Приора 2 — разные записи.'],
 ar_vehicle_versions:['Модификации автомобилей','car_repair','{{vehicle_id.name}} · {{name}}','Заполняйте только подтверждённые модификации.'],
 ar_fitment:['Совместимость','rule','{{product_id.name}} · {{vehicle_id.name}}','Неизвестно не означает подходит всем. Год и кондиционер — подтверждённые признаки.'],
 ar_attributes:['Характеристики','tune','{{name}}','Добавляйте определения и типы данных без изменения кода.'],
 ar_attribute_values:['Значения характеристик','list','{{attribute_id.name}} · {{label}}','Значения выпадающих списков: подсветка, поверхность, материал и другие.'],
 ar_category_attributes:['Характеристики категорий','filter_alt','{{category_id.name}} · {{attribute_id.name}}','Какие характеристики применяются и используются в фильтрах.'],
 ar_product_attributes:['Характеристики товаров','fact_check','{{product_id.name}} · {{attribute_id.name}}','Общие значения; SKU наследует их, если не задано переопределение.'],
 ar_sku_attributes:['Характеристики SKU','checklist','{{sku_id.article}} · {{attribute_id.name}}','Переопределяет только указанную характеристику товара.'],
 ar_product_media:['Фотографии товаров','photo_library','{{product_id.name}} · {{alt}}','Общие фотографии товара.'],
 ar_sku_media:['Фотографии SKU','photo','{{sku_id.article}} · {{alt}}','Применяются при выборе режима «Собственные фотографии».'],
 ar_product_categories:['Дополнительные категории','category','{{product_id.name}} · {{category_id.name}}','Основная категория выбирается в товаре.'],
 ar_packages:['Упаковки','package_2','{{name}}','Только измеренные масса и габариты. Габариты сборной посылки не суммировать.'],
 ar_stock:['Остатки — только чтение','warehouse','{{sku_id.article}}','Корректировки через торговые команды появятся на следующем этапе.'],
 ar_slug_history:['История адресов','history','{{old_slug}}','Заполняется автоматически при изменении slug.'],
};
export const labels={
 id:'ID',parent_id:'Родительский раздел',name:'Название',slug:'Адрес (slug)',status:'Публикация',sort:'Порядок',seo_title:'SEO-заголовок',meta_description:'Meta description',
 make:'Марка',model:'Модель',generation:'Поколение / версия',year_from:'Год от',year_to:'Год до',vehicle_id:'Автомобиль',version_id:'Модификация',note:'Примечание',
 code:'Код',value_type:'Тип значения',unit:'Единица измерения',filterable:'Можно использовать как фильтр',attribute_id:'Характеристика',label:'Подпись',color:'Цвет HEX',
 category_id:'Категория',required:'Обязательное значение',show_filter:'Показывать в фильтрах',kind:'Вид товара',description:'Описание',discount_percent:'Скидка комплекта, %',is_demo:'Демонстрационные данные',created_at:'Создано',updated_at:'Обновлено',
 product_id:'Товар',sku_id:'Исполнение (SKU)',bundle_id:'Комплект',quantity:'Количество',article:'Артикул',price_rubles:'Цена, ₽',media_mode:'Фотографии',fitment_mode:'Совместимость SKU',package_id:'Упаковка',
 file_id:'Файл',alt:'Описание изображения',value_id:'Значение из справочника',text_value:'Текстовое значение',number_value:'Числовое значение',boolean_value:'Логическое значение',
 air_conditioning:'Кондиционер',state:'Статус совместимости',on_hand:'Физический остаток',reserved:'Зарезервировано',entity_type:'Тип страницы',entity_id:'ID страницы',old_slug:'Прежний адрес',
 weight_g:'Масса с упаковкой, г',length_mm:'Длина, мм',width_mm:'Ширина, мм',height_mm:'Высота, мм',
};
export const choices={
 status:[['draft','Черновик'],['published','Опубликовано'],['archived','Архив']],
 kind:[['single','Отдельный товар'],['bundle','Готовый комплект']],
 value_type:[['select','Значение из справочника'],['text','Текст'],['number','Число'],['boolean','Да / нет']],
 media_mode:[['inherit','Фотографии товара'],['replace','Собственные фотографии']],
 fitment_mode:[['inherit','Правила товара'],['replace','Собственные правила SKU']],
 air_conditioning:[['unknown','Неизвестно'],['yes','Есть'],['no','Нет'],['any','Не влияет']],
 state:[['unknown','Не подтверждено'],['compatible','Подходит'],['incompatible','Не подходит']],
};
// [many collection, FK, one collection, reverse alias, reverse label]
export const relations=[
 ['ar_categories','parent_id','ar_categories','children','Дочерние категории'],
 ['ar_products','category_id','ar_categories',null,null],
 ['ar_skus','product_id','ar_products','skus','Исполнения товара'],
 ['ar_bundle_components','bundle_id','ar_products','components','Состав комплекта'],
 ['ar_bundle_components','sku_id','ar_skus',null,null],
 ['ar_vehicle_versions','vehicle_id','ar_vehicles','versions','Модификации'],
 ['ar_attribute_values','attribute_id','ar_attributes','values','Возможные значения'],
 ['ar_category_attributes','category_id','ar_categories','attributes','Характеристики категории'],
 ['ar_category_attributes','attribute_id','ar_attributes',null,null],
 ['ar_product_attributes','product_id','ar_products','attributes','Характеристики товара'],
 ['ar_sku_attributes','sku_id','ar_skus','attributes','Переопределения характеристик'],
 ['ar_product_attributes','attribute_id','ar_attributes',null,null],
 ['ar_product_attributes','value_id','ar_attribute_values',null,null],
 ['ar_sku_attributes','attribute_id','ar_attributes',null,null],
 ['ar_sku_attributes','value_id','ar_attribute_values',null,null],
 ['ar_fitment','product_id','ar_products','fitment','Совместимость товара'],
 ['ar_fitment','sku_id','ar_skus','fitment','Совместимость исполнения'],
 ['ar_fitment','vehicle_id','ar_vehicles',null,null],
 ['ar_fitment','version_id','ar_vehicle_versions',null,null],
 ['ar_product_media','product_id','ar_products','media','Фотографии товара'],
 ['ar_sku_media','sku_id','ar_skus','media','Фотографии исполнения'],
 ['ar_product_media','file_id','directus_files',null,null],
 ['ar_sku_media','file_id','directus_files',null,null],
 ['ar_product_categories','product_id','ar_products','extra_categories','Дополнительные категории'],
 ['ar_product_categories','category_id','ar_categories',null,null],
 ['ar_skus','package_id','ar_packages',null,null],
 ['ar_stock','sku_id','ar_skus',null,null],
];
